/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sun Feb  2 16:46:22 IST 2014
 * 
 */
extern "C" {
  unsigned int getRandom();
  void setSeed(unsigned int );
}
