/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sun Feb  2 19:04:14 IST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "mkBoothTb.h"
#include "imported_BDPI_functions.h"

namespace bluesim
{
  
  /* String declarations */
  static std::string const __str_literal_2(" ", 1u);
  static std::string const __str_literal_4("%0d * %0d = %0d", 15u);
  static std::string const __str_literal_3("%s%0d * %s%0d = %s%0d, but you returned %s%0d", 45u);
  static std::string const __str_literal_1("-", 1u);
  static std::string const __str_literal_5("PASSED", 6u);
  
  
  /* Constructor */
  MOD_mkBoothTb::MOD_mkBoothTb(char const *name, Module *parent)
    : Module(name, parent),
      __clk_handle_0(BAD_CLOCK_HANDLE),
      INST_deqCount("deqCount", this, 16u, 0u, (tUInt8)0u),
      INST_enqCount("enqCount", this, 16u, 0u, (tUInt8)0u),
      INST_f_data("f_data", this, 32u),
      INST_f_data_1("f_data_1", this, 32u),
      INST_f_data_2("f_data_2", this, 32u),
      INST_f_data_3("f_data_3", this, 32u),
      INST_f_deqEn_dummy("f_deqEn_dummy", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy2("f_deqEn_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqEn_dummy2_1("f_deqEn_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqEn_dummy2_2("f_deqEn_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqEn_dummy_1("f_deqEn_dummy_1", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_2("f_deqEn_dummy_2", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_3("f_deqEn_dummy_3", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_4("f_deqEn_dummy_4", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_5("f_deqEn_dummy_5", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_6("f_deqEn_dummy_6", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_7("f_deqEn_dummy_7", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_8("f_deqEn_dummy_8", this, 2u, (tUInt8)0u),
      INST_f_deqEn_lat("f_deqEn_lat", this, 1u, (tUInt8)0u),
      INST_f_deqEn_lat_1("f_deqEn_lat_1", this, 1u, (tUInt8)0u),
      INST_f_deqEn_lat_2("f_deqEn_lat_2", this, 1u, (tUInt8)0u),
      INST_f_deqEn_rl("f_deqEn_rl", this, 1u, (tUInt8)0u, (tUInt8)0u),
      INST_f_deqP_dummy("f_deqP_dummy", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy2("f_deqP_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqP_dummy2_1("f_deqP_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqP_dummy2_2("f_deqP_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqP_dummy_1("f_deqP_dummy_1", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_2("f_deqP_dummy_2", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_3("f_deqP_dummy_3", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_4("f_deqP_dummy_4", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_5("f_deqP_dummy_5", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_6("f_deqP_dummy_6", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_7("f_deqP_dummy_7", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_8("f_deqP_dummy_8", this, 5u, (tUInt8)0u),
      INST_f_deqP_lat("f_deqP_lat", this, 4u, (tUInt8)0u),
      INST_f_deqP_lat_1("f_deqP_lat_1", this, 4u, (tUInt8)0u),
      INST_f_deqP_lat_2("f_deqP_lat_2", this, 4u, (tUInt8)0u),
      INST_f_deqP_rl("f_deqP_rl", this, 4u, (tUInt8)0u, (tUInt8)0u),
      INST_f_enqEn_dummy("f_enqEn_dummy", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy2("f_enqEn_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqEn_dummy2_1("f_enqEn_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqEn_dummy2_2("f_enqEn_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqEn_dummy_1("f_enqEn_dummy_1", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_2("f_enqEn_dummy_2", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_3("f_enqEn_dummy_3", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_4("f_enqEn_dummy_4", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_5("f_enqEn_dummy_5", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_6("f_enqEn_dummy_6", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_7("f_enqEn_dummy_7", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_8("f_enqEn_dummy_8", this, 2u, (tUInt8)0u),
      INST_f_enqEn_lat("f_enqEn_lat", this, 1u, (tUInt8)0u),
      INST_f_enqEn_lat_1("f_enqEn_lat_1", this, 1u, (tUInt8)0u),
      INST_f_enqEn_lat_2("f_enqEn_lat_2", this, 1u, (tUInt8)0u),
      INST_f_enqEn_rl("f_enqEn_rl", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy("f_enqP_dummy", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy2("f_enqP_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy2_1("f_enqP_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy2_2("f_enqP_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy_1("f_enqP_dummy_1", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_2("f_enqP_dummy_2", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_3("f_enqP_dummy_3", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_4("f_enqP_dummy_4", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_5("f_enqP_dummy_5", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_6("f_enqP_dummy_6", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_7("f_enqP_dummy_7", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_8("f_enqP_dummy_8", this, 5u, (tUInt8)0u),
      INST_f_enqP_lat("f_enqP_lat", this, 4u, (tUInt8)0u),
      INST_f_enqP_lat_1("f_enqP_lat_1", this, 4u, (tUInt8)0u),
      INST_f_enqP_lat_2("f_enqP_lat_2", this, 4u, (tUInt8)0u),
      INST_f_enqP_rl("f_enqP_rl", this, 4u, (tUInt8)0u, (tUInt8)0u),
      INST_f_tempData_dummy("f_tempData_dummy", this, 33u, (tUInt8)0u),
      INST_f_tempData_dummy2("f_tempData_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempData_dummy2_1("f_tempData_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempData_dummy_1("f_tempData_dummy_1", this, 33u, (tUInt8)0u),
      INST_f_tempData_dummy_2("f_tempData_dummy_2", this, 33u, (tUInt8)0u),
      INST_f_tempData_dummy_3("f_tempData_dummy_3", this, 33u, (tUInt8)0u),
      INST_f_tempData_lat("f_tempData_lat", this, 32u, (tUInt8)0u),
      INST_f_tempData_lat_1("f_tempData_lat_1", this, 32u, (tUInt8)0u),
      INST_f_tempData_rl("f_tempData_rl", this, 32u, 2863311530u, (tUInt8)0u),
      INST_f_tempEnqP_dummy("f_tempEnqP_dummy", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_dummy2("f_tempEnqP_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempEnqP_dummy2_1("f_tempEnqP_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempEnqP_dummy_1("f_tempEnqP_dummy_1", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_dummy_2("f_tempEnqP_dummy_2", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_dummy_3("f_tempEnqP_dummy_3", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_lat("f_tempEnqP_lat", this, 5u, (tUInt8)0u),
      INST_f_tempEnqP_lat_1("f_tempEnqP_lat_1", this, 5u, (tUInt8)0u),
      INST_f_tempEnqP_rl("f_tempEnqP_rl", this, 5u, (tUInt8)31u & (tUInt8)10u, (tUInt8)0u),
      INST_mult_a("mult_a", this, 33u),
      INST_mult_i("mult_i", this, 5u, (tUInt8)16u, (tUInt8)0u),
      INST_mult_p("mult_p", this, 33u),
      INST_mult_s("mult_s", this, 33u),
      INST_randomVal1_init("randomVal1_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      INST_randomVal2_init("randomVal2_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      PORT_RST_N((tUInt8)1u),
      DEF_TASK_getRandom___d179(2863311530u),
      DEF_TASK_getRandom___d174(2863311530u)
  {
    symbol_count = 114u;
    symbols = new tSym[symbol_count];
    init_symbols_0();
  }
  
  
  /* Symbol init fns */
  
  void MOD_mkBoothTb::init_symbols_0()
  {
    init_symbol(&symbols[0u], "_read__h193", SYM_DEF, &DEF__read__h193, 5u);
    init_symbol(&symbols[1u], "deqCount", SYM_MODULE, &INST_deqCount);
    init_symbol(&symbols[2u], "enqCount", SYM_MODULE, &INST_enqCount);
    init_symbol(&symbols[3u], "f_data", SYM_MODULE, &INST_f_data);
    init_symbol(&symbols[4u], "f_data_1", SYM_MODULE, &INST_f_data_1);
    init_symbol(&symbols[5u], "f_data_2", SYM_MODULE, &INST_f_data_2);
    init_symbol(&symbols[6u], "f_data_3", SYM_MODULE, &INST_f_data_3);
    init_symbol(&symbols[7u], "f_deqEn_dummy", SYM_MODULE, &INST_f_deqEn_dummy);
    init_symbol(&symbols[8u], "f_deqEn_dummy2", SYM_MODULE, &INST_f_deqEn_dummy2);
    init_symbol(&symbols[9u], "f_deqEn_dummy2_1", SYM_MODULE, &INST_f_deqEn_dummy2_1);
    init_symbol(&symbols[10u], "f_deqEn_dummy2_2", SYM_MODULE, &INST_f_deqEn_dummy2_2);
    init_symbol(&symbols[11u], "f_deqEn_dummy2_2__h11741", SYM_DEF, &DEF_f_deqEn_dummy2_2__h11741, 1u);
    init_symbol(&symbols[12u], "f_deqEn_dummy_1", SYM_MODULE, &INST_f_deqEn_dummy_1);
    init_symbol(&symbols[13u], "f_deqEn_dummy_2", SYM_MODULE, &INST_f_deqEn_dummy_2);
    init_symbol(&symbols[14u], "f_deqEn_dummy_3", SYM_MODULE, &INST_f_deqEn_dummy_3);
    init_symbol(&symbols[15u], "f_deqEn_dummy_4", SYM_MODULE, &INST_f_deqEn_dummy_4);
    init_symbol(&symbols[16u], "f_deqEn_dummy_5", SYM_MODULE, &INST_f_deqEn_dummy_5);
    init_symbol(&symbols[17u], "f_deqEn_dummy_6", SYM_MODULE, &INST_f_deqEn_dummy_6);
    init_symbol(&symbols[18u], "f_deqEn_dummy_7", SYM_MODULE, &INST_f_deqEn_dummy_7);
    init_symbol(&symbols[19u], "f_deqEn_dummy_8", SYM_MODULE, &INST_f_deqEn_dummy_8);
    init_symbol(&symbols[20u], "f_deqEn_lat", SYM_MODULE, &INST_f_deqEn_lat);
    init_symbol(&symbols[21u], "f_deqEn_lat_1", SYM_MODULE, &INST_f_deqEn_lat_1);
    init_symbol(&symbols[22u], "f_deqEn_lat_2", SYM_MODULE, &INST_f_deqEn_lat_2);
    init_symbol(&symbols[23u], "f_deqEn_rl", SYM_MODULE, &INST_f_deqEn_rl);
    init_symbol(&symbols[24u], "f_deqEn_rl__h7670", SYM_DEF, &DEF_f_deqEn_rl__h7670, 1u);
    init_symbol(&symbols[25u], "f_deqP_dummy", SYM_MODULE, &INST_f_deqP_dummy);
    init_symbol(&symbols[26u], "f_deqP_dummy2", SYM_MODULE, &INST_f_deqP_dummy2);
    init_symbol(&symbols[27u], "f_deqP_dummy2_1", SYM_MODULE, &INST_f_deqP_dummy2_1);
    init_symbol(&symbols[28u], "f_deqP_dummy2_2", SYM_MODULE, &INST_f_deqP_dummy2_2);
    init_symbol(&symbols[29u], "f_deqP_dummy_1", SYM_MODULE, &INST_f_deqP_dummy_1);
    init_symbol(&symbols[30u], "f_deqP_dummy_2", SYM_MODULE, &INST_f_deqP_dummy_2);
    init_symbol(&symbols[31u], "f_deqP_dummy_3", SYM_MODULE, &INST_f_deqP_dummy_3);
    init_symbol(&symbols[32u], "f_deqP_dummy_4", SYM_MODULE, &INST_f_deqP_dummy_4);
    init_symbol(&symbols[33u], "f_deqP_dummy_5", SYM_MODULE, &INST_f_deqP_dummy_5);
    init_symbol(&symbols[34u], "f_deqP_dummy_6", SYM_MODULE, &INST_f_deqP_dummy_6);
    init_symbol(&symbols[35u], "f_deqP_dummy_7", SYM_MODULE, &INST_f_deqP_dummy_7);
    init_symbol(&symbols[36u], "f_deqP_dummy_8", SYM_MODULE, &INST_f_deqP_dummy_8);
    init_symbol(&symbols[37u], "f_deqP_lat", SYM_MODULE, &INST_f_deqP_lat);
    init_symbol(&symbols[38u], "f_deqP_lat_1", SYM_MODULE, &INST_f_deqP_lat_1);
    init_symbol(&symbols[39u], "f_deqP_lat_2", SYM_MODULE, &INST_f_deqP_lat_2);
    init_symbol(&symbols[40u], "f_deqP_rl", SYM_MODULE, &INST_f_deqP_rl);
    init_symbol(&symbols[41u], "f_enqEn_dummy", SYM_MODULE, &INST_f_enqEn_dummy);
    init_symbol(&symbols[42u], "f_enqEn_dummy2", SYM_MODULE, &INST_f_enqEn_dummy2);
    init_symbol(&symbols[43u], "f_enqEn_dummy2_1", SYM_MODULE, &INST_f_enqEn_dummy2_1);
    init_symbol(&symbols[44u], "f_enqEn_dummy2_2", SYM_MODULE, &INST_f_enqEn_dummy2_2);
    init_symbol(&symbols[45u], "f_enqEn_dummy2_2__h10238", SYM_DEF, &DEF_f_enqEn_dummy2_2__h10238, 1u);
    init_symbol(&symbols[46u], "f_enqEn_dummy_1", SYM_MODULE, &INST_f_enqEn_dummy_1);
    init_symbol(&symbols[47u], "f_enqEn_dummy_2", SYM_MODULE, &INST_f_enqEn_dummy_2);
    init_symbol(&symbols[48u], "f_enqEn_dummy_3", SYM_MODULE, &INST_f_enqEn_dummy_3);
    init_symbol(&symbols[49u], "f_enqEn_dummy_4", SYM_MODULE, &INST_f_enqEn_dummy_4);
    init_symbol(&symbols[50u], "f_enqEn_dummy_5", SYM_MODULE, &INST_f_enqEn_dummy_5);
    init_symbol(&symbols[51u], "f_enqEn_dummy_6", SYM_MODULE, &INST_f_enqEn_dummy_6);
    init_symbol(&symbols[52u], "f_enqEn_dummy_7", SYM_MODULE, &INST_f_enqEn_dummy_7);
    init_symbol(&symbols[53u], "f_enqEn_dummy_8", SYM_MODULE, &INST_f_enqEn_dummy_8);
    init_symbol(&symbols[54u], "f_enqEn_lat", SYM_MODULE, &INST_f_enqEn_lat);
    init_symbol(&symbols[55u], "f_enqEn_lat_1", SYM_MODULE, &INST_f_enqEn_lat_1);
    init_symbol(&symbols[56u], "f_enqEn_lat_2", SYM_MODULE, &INST_f_enqEn_lat_2);
    init_symbol(&symbols[57u], "f_enqEn_rl", SYM_MODULE, &INST_f_enqEn_rl);
    init_symbol(&symbols[58u], "f_enqEn_rl__h6069", SYM_DEF, &DEF_f_enqEn_rl__h6069, 1u);
    init_symbol(&symbols[59u], "f_enqP_dummy", SYM_MODULE, &INST_f_enqP_dummy);
    init_symbol(&symbols[60u], "f_enqP_dummy2", SYM_MODULE, &INST_f_enqP_dummy2);
    init_symbol(&symbols[61u], "f_enqP_dummy2_1", SYM_MODULE, &INST_f_enqP_dummy2_1);
    init_symbol(&symbols[62u], "f_enqP_dummy2_2", SYM_MODULE, &INST_f_enqP_dummy2_2);
    init_symbol(&symbols[63u], "f_enqP_dummy_1", SYM_MODULE, &INST_f_enqP_dummy_1);
    init_symbol(&symbols[64u], "f_enqP_dummy_2", SYM_MODULE, &INST_f_enqP_dummy_2);
    init_symbol(&symbols[65u], "f_enqP_dummy_3", SYM_MODULE, &INST_f_enqP_dummy_3);
    init_symbol(&symbols[66u], "f_enqP_dummy_4", SYM_MODULE, &INST_f_enqP_dummy_4);
    init_symbol(&symbols[67u], "f_enqP_dummy_5", SYM_MODULE, &INST_f_enqP_dummy_5);
    init_symbol(&symbols[68u], "f_enqP_dummy_6", SYM_MODULE, &INST_f_enqP_dummy_6);
    init_symbol(&symbols[69u], "f_enqP_dummy_7", SYM_MODULE, &INST_f_enqP_dummy_7);
    init_symbol(&symbols[70u], "f_enqP_dummy_8", SYM_MODULE, &INST_f_enqP_dummy_8);
    init_symbol(&symbols[71u], "f_enqP_lat", SYM_MODULE, &INST_f_enqP_lat);
    init_symbol(&symbols[72u], "f_enqP_lat_1", SYM_MODULE, &INST_f_enqP_lat_1);
    init_symbol(&symbols[73u], "f_enqP_lat_2", SYM_MODULE, &INST_f_enqP_lat_2);
    init_symbol(&symbols[74u], "f_enqP_rl", SYM_MODULE, &INST_f_enqP_rl);
    init_symbol(&symbols[75u], "f_tempData_dummy", SYM_MODULE, &INST_f_tempData_dummy);
    init_symbol(&symbols[76u], "f_tempData_dummy2", SYM_MODULE, &INST_f_tempData_dummy2);
    init_symbol(&symbols[77u], "f_tempData_dummy2_1", SYM_MODULE, &INST_f_tempData_dummy2_1);
    init_symbol(&symbols[78u], "f_tempData_dummy_1", SYM_MODULE, &INST_f_tempData_dummy_1);
    init_symbol(&symbols[79u], "f_tempData_dummy_2", SYM_MODULE, &INST_f_tempData_dummy_2);
    init_symbol(&symbols[80u], "f_tempData_dummy_3", SYM_MODULE, &INST_f_tempData_dummy_3);
    init_symbol(&symbols[81u], "f_tempData_lat", SYM_MODULE, &INST_f_tempData_lat);
    init_symbol(&symbols[82u], "f_tempData_lat_1", SYM_MODULE, &INST_f_tempData_lat_1);
    init_symbol(&symbols[83u], "f_tempData_rl", SYM_MODULE, &INST_f_tempData_rl);
    init_symbol(&symbols[84u], "f_tempEnqP_dummy", SYM_MODULE, &INST_f_tempEnqP_dummy);
    init_symbol(&symbols[85u], "f_tempEnqP_dummy2", SYM_MODULE, &INST_f_tempEnqP_dummy2);
    init_symbol(&symbols[86u], "f_tempEnqP_dummy2_1", SYM_MODULE, &INST_f_tempEnqP_dummy2_1);
    init_symbol(&symbols[87u], "f_tempEnqP_dummy_1", SYM_MODULE, &INST_f_tempEnqP_dummy_1);
    init_symbol(&symbols[88u], "f_tempEnqP_dummy_2", SYM_MODULE, &INST_f_tempEnqP_dummy_2);
    init_symbol(&symbols[89u], "f_tempEnqP_dummy_3", SYM_MODULE, &INST_f_tempEnqP_dummy_3);
    init_symbol(&symbols[90u], "f_tempEnqP_lat", SYM_MODULE, &INST_f_tempEnqP_lat);
    init_symbol(&symbols[91u], "f_tempEnqP_lat_1", SYM_MODULE, &INST_f_tempEnqP_lat_1);
    init_symbol(&symbols[92u], "f_tempEnqP_rl", SYM_MODULE, &INST_f_tempEnqP_rl);
    init_symbol(&symbols[93u], "mult_a", SYM_MODULE, &INST_mult_a);
    init_symbol(&symbols[94u], "mult_i", SYM_MODULE, &INST_mult_i);
    init_symbol(&symbols[95u], "mult_p", SYM_MODULE, &INST_mult_p);
    init_symbol(&symbols[96u], "mult_s", SYM_MODULE, &INST_mult_s);
    init_symbol(&symbols[97u], "RL_deq", SYM_RULE);
    init_symbol(&symbols[98u], "RL_enq", SYM_RULE);
    init_symbol(&symbols[99u], "RL_f_canonicalize", SYM_RULE);
    init_symbol(&symbols[100u], "RL_f_deqEn_canon", SYM_RULE);
    init_symbol(&symbols[101u], "RL_f_deqP_canon", SYM_RULE);
    init_symbol(&symbols[102u], "RL_f_enqEn_canon", SYM_RULE);
    init_symbol(&symbols[103u], "RL_f_enqP_canon", SYM_RULE);
    init_symbol(&symbols[104u], "RL_f_tempData_canon", SYM_RULE);
    init_symbol(&symbols[105u], "RL_f_tempEnqP_canon", SYM_RULE);
    init_symbol(&symbols[106u], "RL_fin", SYM_RULE);
    init_symbol(&symbols[107u], "RL_mult_mulStep", SYM_RULE);
    init_symbol(&symbols[108u], "RL_randomVal1_initialize", SYM_RULE);
    init_symbol(&symbols[109u], "RL_randomVal2_initialize", SYM_RULE);
    init_symbol(&symbols[110u], "randomVal1_init", SYM_MODULE, &INST_randomVal1_init);
    init_symbol(&symbols[111u], "randomVal2_init", SYM_MODULE, &INST_randomVal2_init);
    init_symbol(&symbols[112u], "x__h14887", SYM_DEF, &DEF_x__h14887, 16u);
    init_symbol(&symbols[113u], "x__h15872", SYM_DEF, &DEF_x__h15872, 16u);
  }
  
  
  /* Rule actions */
  
  void MOD_mkBoothTb::RL_mult_mulStep()
  {
    tUInt8 DEF_x__h666;
    tUInt64 DEF_x__h229;
    tUInt8 DEF_mult_p_BIT_0___h491;
    tUInt8 DEF_mult_p_BIT_1___h459;
    tUInt64 DEF_mult_p_PLUS_mult_a___d261;
    tUInt64 DEF_mult_p_PLUS_mult_s_6___d262;
    tUInt64 DEF_y__h417;
    tUInt64 DEF_y__h586;
    DEF_mult_p__h15599 = INST_mult_p.METH_read();
    DEF_y__h586 = INST_mult_s.METH_read();
    DEF_y__h417 = INST_mult_a.METH_read();
    DEF__read__h193 = INST_mult_i.METH_read();
    DEF_mult_p_PLUS_mult_s_6___d262 = 8589934591llu & (DEF_mult_p__h15599 + DEF_y__h586);
    DEF_mult_p_PLUS_mult_a___d261 = 8589934591llu & (DEF_mult_p__h15599 + DEF_y__h417);
    DEF_res__h15368 = (tUInt32)(DEF_mult_p__h15599 >> 1u);
    DEF_mult_p_BIT_32___h625 = (tUInt8)(DEF_mult_p__h15599 >> 32u);
    DEF_mult_p_BIT_1___h459 = (tUInt8)((tUInt8)1u & (DEF_mult_p__h15599 >> 1u));
    DEF_mult_p_BIT_0___h491 = (tUInt8)((tUInt8)1u & DEF_mult_p__h15599);
    DEF_x__h229 = !DEF_mult_p_BIT_1___h459 && DEF_mult_p_BIT_0___h491 ? 8589934591llu & ((((tUInt64)((tUInt8)(DEF_mult_p_PLUS_mult_a___d261 >> 32u))) << 32u) | (tUInt64)((tUInt32)(DEF_mult_p_PLUS_mult_a___d261 >> 1u))) : (DEF_mult_p_BIT_1___h459 && !DEF_mult_p_BIT_0___h491 ? 8589934591llu & ((((tUInt64)((tUInt8)(DEF_mult_p_PLUS_mult_s_6___d262 >> 32u))) << 32u) | (tUInt64)((tUInt32)(DEF_mult_p_PLUS_mult_s_6___d262 >> 1u))) : 8589934591llu & ((((tUInt64)(DEF_mult_p_BIT_32___h625)) << 32u) | (tUInt64)(DEF_res__h15368)));
    DEF_x__h666 = (tUInt8)31u & (DEF__read__h193 + (tUInt8)1u);
    INST_mult_p.METH_write(DEF_x__h229);
    INST_mult_i.METH_write(DEF_x__h666);
  }
  
  void MOD_mkBoothTb::RL_randomVal1_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3735928559u);
    INST_randomVal1_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkBoothTb::RL_randomVal2_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3405691582u);
    INST_randomVal2_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkBoothTb::RL_f_enqP_canon()
  {
    tUInt8 DEF_x__h2648;
    tUInt8 DEF_upd__h2800;
    DEF_upd__h14458 = INST_f_enqP_rl.METH_read();
    DEF_upd__h2800 = INST_f_enqP_lat_2.METH_wget();
    DEF_upd__h10581 = INST_f_enqP_lat_1.METH_wget();
    DEF_upd__h10614 = INST_f_enqP_lat.METH_wget();
    DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272 = INST_f_enqP_lat_1.METH_whas() ? DEF_upd__h10581 : (INST_f_enqP_lat.METH_whas() ? DEF_upd__h10614 : DEF_upd__h14458);
    DEF_x__h2648 = INST_f_enqP_lat_2.METH_whas() ? DEF_upd__h2800 : DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272;
    INST_f_enqP_rl.METH_write(DEF_x__h2648);
  }
  
  void MOD_mkBoothTb::RL_f_deqP_canon()
  {
    tUInt8 DEF_x__h4224;
    tUInt8 DEF_upd__h4376;
    DEF_upd__h15110 = INST_f_deqP_rl.METH_read();
    DEF_upd__h4376 = INST_f_deqP_lat_2.METH_wget();
    DEF_upd__h10861 = INST_f_deqP_lat_1.METH_wget();
    DEF_upd__h10894 = INST_f_deqP_lat.METH_wget();
    DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274 = INST_f_deqP_lat_1.METH_whas() ? DEF_upd__h10861 : (INST_f_deqP_lat.METH_whas() ? DEF_upd__h10894 : DEF_upd__h15110);
    DEF_x__h4224 = INST_f_deqP_lat_2.METH_whas() ? DEF_upd__h4376 : DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274;
    INST_f_deqP_rl.METH_write(DEF_x__h4224);
  }
  
  void MOD_mkBoothTb::RL_f_enqEn_canon()
  {
    tUInt8 DEF_IF_f_enqEn_lat_2_whas__1_THEN_f_enqEn_lat_2_wg_ETC___d60;
    DEF_f_enqEn_lat_1_whas____d286 = INST_f_enqEn_lat_1.METH_whas();
    DEF_f_enqEn_rl__h6069 = INST_f_enqEn_rl.METH_read();
    DEF_f_enqEn_lat_1_wget____d279 = INST_f_enqEn_lat_1.METH_wget();
    DEF_f_enqEn_lat_whas____d285 = INST_f_enqEn_lat.METH_whas();
    DEF_f_enqEn_lat_wget____d278 = INST_f_enqEn_lat.METH_wget();
    DEF_IF_f_enqEn_lat_2_whas__1_THEN_f_enqEn_lat_2_wg_ETC___d60 = INST_f_enqEn_lat_2.METH_whas() ? INST_f_enqEn_lat_2.METH_wget() : (DEF_f_enqEn_lat_1_whas____d286 ? DEF_f_enqEn_lat_1_wget____d279 : (DEF_f_enqEn_lat_whas____d285 ? DEF_f_enqEn_lat_wget____d278 : DEF_f_enqEn_rl__h6069));
    INST_f_enqEn_rl.METH_write(DEF_IF_f_enqEn_lat_2_whas__1_THEN_f_enqEn_lat_2_wg_ETC___d60);
  }
  
  void MOD_mkBoothTb::RL_f_deqEn_canon()
  {
    tUInt8 DEF_IF_f_deqEn_lat_2_whas__1_THEN_f_deqEn_lat_2_wg_ETC___d70;
    DEF_f_deqEn_lat_1_whas____d288 = INST_f_deqEn_lat_1.METH_whas();
    DEF_f_deqEn_rl__h7670 = INST_f_deqEn_rl.METH_read();
    DEF_f_deqEn_lat_1_wget____d281 = INST_f_deqEn_lat_1.METH_wget();
    DEF_f_deqEn_lat_whas____d287 = INST_f_deqEn_lat.METH_whas();
    DEF_f_deqEn_lat_wget____d280 = INST_f_deqEn_lat.METH_wget();
    DEF_IF_f_deqEn_lat_2_whas__1_THEN_f_deqEn_lat_2_wg_ETC___d70 = INST_f_deqEn_lat_2.METH_whas() ? INST_f_deqEn_lat_2.METH_wget() : (DEF_f_deqEn_lat_1_whas____d288 ? DEF_f_deqEn_lat_1_wget____d281 : (DEF_f_deqEn_lat_whas____d287 ? DEF_f_deqEn_lat_wget____d280 : DEF_f_deqEn_rl__h7670));
    INST_f_deqEn_rl.METH_write(DEF_IF_f_deqEn_lat_2_whas__1_THEN_f_deqEn_lat_2_wg_ETC___d70);
  }
  
  void MOD_mkBoothTb::RL_f_tempData_canon()
  {
    tUInt32 DEF_IF_f_tempData_lat_1_whas__1_THEN_f_tempData_la_ETC___d77;
    tUInt32 DEF_ab__h8727;
    DEF_ab__h8773 = INST_f_tempData_rl.METH_read();
    DEF_ab__h8727 = INST_f_tempData_lat_1.METH_wget();
    DEF_ab__h8769 = INST_f_tempData_lat.METH_wget();
    DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266 = INST_f_tempData_lat.METH_whas() ? DEF_ab__h8769 : DEF_ab__h8773;
    DEF_IF_f_tempData_lat_1_whas__1_THEN_f_tempData_la_ETC___d77 = INST_f_tempData_lat_1.METH_whas() ? DEF_ab__h8727 : DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266;
    INST_f_tempData_rl.METH_write(DEF_IF_f_tempData_lat_1_whas__1_THEN_f_tempData_la_ETC___d77);
  }
  
  void MOD_mkBoothTb::RL_f_tempEnqP_canon()
  {
    tUInt8 DEF_IF_f_tempEnqP_lat_1_whas__8_THEN_f_tempEnqP_la_ETC___d99;
    tUInt8 DEF_IF_f_tempEnqP_lat_1_whas__8_THEN_f_tempEnqP_la_ETC___d267;
    tUInt8 DEF_f_tempEnqP_lat_1_wget__9_BIT_4___d293;
    tUInt8 DEF_f_tempEnqP_lat_1_whas____d290;
    tUInt8 DEF_f_tempEnqP_lat_1_wget____d284;
    DEF_f_tempEnqP_rl___d296 = INST_f_tempEnqP_rl.METH_read();
    DEF_f_tempEnqP_lat_1_wget____d284 = INST_f_tempEnqP_lat_1.METH_wget();
    DEF_f_tempEnqP_lat_wget____d283 = INST_f_tempEnqP_lat.METH_wget();
    DEF_f_tempEnqP_lat_1_whas____d290 = INST_f_tempEnqP_lat_1.METH_whas();
    DEF_f_tempEnqP_lat_whas____d289 = INST_f_tempEnqP_lat.METH_whas();
    DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277 = (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_lat_wget____d283);
    DEF_f_tempEnqP_rl_4_BIT_4___d295 = (tUInt8)(DEF_f_tempEnqP_rl___d296 >> 4u);
    DEF_f_tempEnqP_lat_1_wget__9_BIT_4___d293 = (tUInt8)(DEF_f_tempEnqP_lat_1_wget____d284 >> 4u);
    DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 = (tUInt8)(DEF_f_tempEnqP_lat_wget____d283 >> 4u);
    DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271 = DEF_f_tempEnqP_lat_whas____d289 ? DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 : DEF_f_tempEnqP_rl_4_BIT_4___d295;
    DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259 = DEF_f_tempEnqP_lat_whas____d289 ? !DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 : !DEF_f_tempEnqP_rl_4_BIT_4___d295;
    DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276 = DEF_f_tempEnqP_lat_whas____d289 ? DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277 : (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_rl___d296);
    DEF_IF_f_tempEnqP_lat_1_whas__8_THEN_f_tempEnqP_la_ETC___d267 = DEF_f_tempEnqP_lat_1_whas____d290 ? (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_lat_1_wget____d284) : DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276;
    DEF_IF_f_tempEnqP_lat_1_whas__8_THEN_f_tempEnqP_la_ETC___d99 = (tUInt8)31u & (((DEF_f_tempEnqP_lat_1_whas____d290 ? DEF_f_tempEnqP_lat_1_wget__9_BIT_4___d293 : DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271) << 4u) | ((DEF_f_tempEnqP_lat_1_whas____d290 ? !DEF_f_tempEnqP_lat_1_wget__9_BIT_4___d293 : DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259) ? DEF_IF_f_tempEnqP_lat_1_whas__8_THEN_f_tempEnqP_la_ETC___d267 : DEF_IF_f_tempEnqP_lat_1_whas__8_THEN_f_tempEnqP_la_ETC___d267));
    INST_f_tempEnqP_rl.METH_write(DEF_IF_f_tempEnqP_lat_1_whas__8_THEN_f_tempEnqP_la_ETC___d99);
  }
  
  void MOD_mkBoothTb::RL_f_canonicalize()
  {
    tUInt8 DEF_f_enqEn_lat_1_whas__3_CONCAT_IF_f_enqEn_lat_1__ETC___d126;
    tUInt8 DEF_f_enqEn_lat_whas__5_CONCAT_IF_f_enqEn_lat_whas_ETC___d124;
    tUInt8 DEF_f_deqEn_lat_whas__5_CONCAT_IF_f_deqEn_lat_whas_ETC___d138;
    tUInt8 DEF_f_deqEn_lat_1_whas__3_CONCAT_IF_f_deqEn_lat_1__ETC___d140;
    tUInt8 DEF__0_CONCAT_DONTCARE___d282;
    tUInt8 DEF_f_tempEnqP_lat_whas__1_CONCAT_IF_f_tempEnqP_la_ETC___d162;
    tUInt8 DEF_x__h10965;
    tUInt8 DEF_y__h10964;
    tUInt8 DEF_x__h10963;
    tUInt8 DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d122;
    tUInt8 DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d136;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d152;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d148;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d154;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d156;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143;
    tUInt8 DEF_IF_f_enqEn_lat_1_whas__3_THEN_NOT_f_enqEn_lat__ETC___d268;
    tUInt8 DEF_IF_f_deqEn_lat_1_whas__3_THEN_NOT_f_deqEn_lat__ETC___d270;
    tUInt8 DEF_IF_f_tempEnqP_lat_wget__2_BIT_4_3_THEN_f_tempE_ETC___d269;
    tUInt8 DEF_cnt__h10036;
    tUInt8 DEF_IF_f_tempEnqP_dummy2_1_41_THEN_IF_f_tempEnqP_l_ETC___d265;
    tUInt32 DEF_IF_f_tempData_dummy2_1_49_THEN_IF_f_tempData_l_ETC___d303;
    tUInt8 DEF_n__read__h10695;
    tUInt8 DEF_n__read__h10415;
    tUInt8 DEF_f_tempData_dummy2_1__h13088;
    tUInt8 DEF_f_tempEnqP_dummy2_1_41_AND_IF_f_tempEnqP_lat_w_ETC___d144;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_41___d142;
    tUInt8 DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d106;
    tUInt8 DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d133;
    tUInt8 DEF_x__h12637;
    tUInt8 DEF_f_tempEnqP_dummy2_1__h12546;
    DEF_f_tempEnqP_dummy2_1__h12546 = INST_f_tempEnqP_dummy2_1.METH_read();
    DEF_f_deqEn_dummy2_2__h11741 = INST_f_deqEn_dummy2_2.METH_read();
    DEF_f_enqEn_dummy2_2__h10238 = INST_f_enqEn_dummy2_2.METH_read();
    DEF_NOT_f_tempEnqP_dummy2_1_41___d142 = !DEF_f_tempEnqP_dummy2_1__h12546;
    DEF_f_deqEn_lat_1_whas____d288 = INST_f_deqEn_lat_1.METH_whas();
    DEF_f_enqEn_lat_1_whas____d286 = INST_f_enqEn_lat_1.METH_whas();
    DEF_ab__h8773 = INST_f_tempData_rl.METH_read();
    DEF_ab__h8769 = INST_f_tempData_lat.METH_wget();
    DEF_f_tempEnqP_rl___d296 = INST_f_tempEnqP_rl.METH_read();
    DEF_f_tempEnqP_lat_wget____d283 = INST_f_tempEnqP_lat.METH_wget();
    DEF_upd__h15110 = INST_f_deqP_rl.METH_read();
    DEF_upd__h10861 = INST_f_deqP_lat_1.METH_wget();
    DEF_upd__h10894 = INST_f_deqP_lat.METH_wget();
    DEF_upd__h14458 = INST_f_enqP_rl.METH_read();
    DEF_upd__h10581 = INST_f_enqP_lat_1.METH_wget();
    DEF_upd__h10614 = INST_f_enqP_lat.METH_wget();
    DEF_f_tempEnqP_lat_whas____d289 = INST_f_tempEnqP_lat.METH_whas();
    DEF_f_tempData_dummy2_1__h13088 = INST_f_tempData_dummy2_1.METH_read();
    DEF_f_deqEn_rl__h7670 = INST_f_deqEn_rl.METH_read();
    DEF_f_deqEn_lat_1_wget____d281 = INST_f_deqEn_lat_1.METH_wget();
    DEF_f_deqEn_lat_whas____d287 = INST_f_deqEn_lat.METH_whas();
    DEF_f_deqEn_lat_wget____d280 = INST_f_deqEn_lat.METH_wget();
    DEF_f_enqEn_rl__h6069 = INST_f_enqEn_rl.METH_read();
    DEF_f_enqEn_lat_1_wget____d279 = INST_f_enqEn_lat_1.METH_wget();
    DEF_f_enqEn_lat_whas____d285 = INST_f_enqEn_lat.METH_whas();
    DEF_f_enqEn_lat_wget____d278 = INST_f_enqEn_lat.METH_wget();
    DEF_f_deqP_dummy2_2__h10822 = INST_f_deqP_dummy2_2.METH_read();
    DEF_f_enqP_dummy2_2__h10542 = INST_f_enqP_dummy2_2.METH_read();
    DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277 = (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_lat_wget____d283);
    DEF_f_tempEnqP_rl_4_BIT_4___d295 = (tUInt8)(DEF_f_tempEnqP_rl___d296 >> 4u);
    DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 = (tUInt8)(DEF_f_tempEnqP_lat_wget____d283 >> 4u);
    DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271 = DEF_f_tempEnqP_lat_whas____d289 ? DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 : DEF_f_tempEnqP_rl_4_BIT_4___d295;
    DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259 = DEF_f_tempEnqP_lat_whas____d289 ? !DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 : !DEF_f_tempEnqP_rl_4_BIT_4___d295;
    DEF_f_tempEnqP_dummy2_1_41_AND_IF_f_tempEnqP_lat_w_ETC___d144 = DEF_f_tempEnqP_dummy2_1__h12546 && DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259;
    DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266 = INST_f_tempData_lat.METH_whas() ? DEF_ab__h8769 : DEF_ab__h8773;
    DEF_IF_f_tempData_dummy2_1_49_THEN_IF_f_tempData_l_ETC___d303 = DEF_f_tempData_dummy2_1__h13088 ? DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266 : DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266;
    DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276 = DEF_f_tempEnqP_lat_whas____d289 ? DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277 : (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_rl___d296);
    DEF_IF_f_tempEnqP_dummy2_1_41_THEN_IF_f_tempEnqP_l_ETC___d265 = DEF_f_tempEnqP_dummy2_1__h12546 ? DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276 : DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276;
    DEF_x__h12637 = DEF_f_tempEnqP_dummy2_1_41_AND_IF_f_tempEnqP_lat_w_ETC___d144 ? DEF_IF_f_tempEnqP_dummy2_1_41_THEN_IF_f_tempEnqP_l_ETC___d265 : DEF_IF_f_tempEnqP_dummy2_1_41_THEN_IF_f_tempEnqP_l_ETC___d265;
    DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274 = INST_f_deqP_lat_1.METH_whas() ? DEF_upd__h10861 : (INST_f_deqP_lat.METH_whas() ? DEF_upd__h10894 : DEF_upd__h15110);
    DEF_n__read__h10695 = DEF_f_deqP_dummy2_2__h10822 ? DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274 : DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274;
    DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272 = INST_f_enqP_lat_1.METH_whas() ? DEF_upd__h10581 : (INST_f_enqP_lat.METH_whas() ? DEF_upd__h10614 : DEF_upd__h14458);
    DEF_n__read__h10415 = DEF_f_enqP_dummy2_2__h10542 ? DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272 : DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272;
    DEF_IF_f_tempEnqP_lat_wget__2_BIT_4_3_THEN_f_tempE_ETC___d269 = DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 ? DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277 : DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277;
    DEF_IF_f_deqEn_lat_1_whas__3_THEN_NOT_f_deqEn_lat__ETC___d270 = DEF_f_deqEn_lat_1_whas____d288 ? !DEF_f_deqEn_lat_1_wget____d281 : (DEF_f_deqEn_lat_whas____d287 ? !DEF_f_deqEn_lat_wget____d280 : !DEF_f_deqEn_rl__h7670);
    DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d133 = DEF_f_deqEn_dummy2_2__h11741 ? DEF_IF_f_deqEn_lat_1_whas__3_THEN_NOT_f_deqEn_lat__ETC___d270 : DEF_IF_f_deqEn_lat_1_whas__3_THEN_NOT_f_deqEn_lat__ETC___d270;
    DEF_IF_f_enqEn_lat_1_whas__3_THEN_NOT_f_enqEn_lat__ETC___d268 = DEF_f_enqEn_lat_1_whas____d286 ? !DEF_f_enqEn_lat_1_wget____d279 : (DEF_f_enqEn_lat_whas____d285 ? !DEF_f_enqEn_lat_wget____d278 : !DEF_f_enqEn_rl__h6069);
    DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d106 = DEF_f_enqEn_dummy2_2__h10238 ? DEF_IF_f_enqEn_lat_1_whas__3_THEN_NOT_f_enqEn_lat__ETC___d268 : DEF_IF_f_enqEn_lat_1_whas__3_THEN_NOT_f_enqEn_lat__ETC___d268;
    DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143 = DEF_NOT_f_tempEnqP_dummy2_1_41___d142 || DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271;
    DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d156 = DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143 && DEF_x__h12637 == (tUInt8)3u;
    DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d154 = DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143 && DEF_x__h12637 == (tUInt8)2u;
    DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d148 = DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143 && DEF_x__h12637 == (tUInt8)0u;
    DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d152 = DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143 && DEF_x__h12637 == (tUInt8)1u;
    DEF_y__h10964 = (tUInt8)15u & ((tUInt8)((tUInt8)3u & DEF_n__read__h10695));
    DEF_x__h10965 = (tUInt8)15u & ((tUInt8)((tUInt8)3u & DEF_n__read__h10415));
    DEF_x__h10963 = (tUInt8)15u & (DEF_x__h10965 + (tUInt8)4u);
    DEF_cnt__h10036 = DEF_n__read__h10415 < DEF_n__read__h10695 ? (tUInt8)15u & (DEF_x__h10963 - DEF_y__h10964) : (tUInt8)15u & (DEF_n__read__h10415 - DEF_n__read__h10695);
    DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d136 = DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d133 && !(DEF_cnt__h10036 == (tUInt8)0u);
    DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d122 = DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d106 && !(DEF_cnt__h10036 == (tUInt8)4u);
    DEF_f_tempEnqP_lat_whas__1_CONCAT_IF_f_tempEnqP_la_ETC___d162 = (tUInt8)63u & ((DEF_f_tempEnqP_lat_whas____d289 << 5u) | (DEF_f_tempEnqP_lat_whas____d289 ? (tUInt8)31u & ((DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 << 4u) | DEF_IF_f_tempEnqP_lat_wget__2_BIT_4_3_THEN_f_tempE_ETC___d269) : (tUInt8)31u & ((DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 << 4u) | DEF_IF_f_tempEnqP_lat_wget__2_BIT_4_3_THEN_f_tempE_ETC___d269)));
    DEF__0_CONCAT_DONTCARE___d282 = (tUInt8)31u & (tUInt8)10u;
    DEF_f_deqEn_lat_1_whas__3_CONCAT_IF_f_deqEn_lat_1__ETC___d140 = (tUInt8)3u & ((DEF_f_deqEn_lat_1_whas____d288 << 1u) | (DEF_f_deqEn_lat_1_whas____d288 ? DEF_f_deqEn_lat_1_wget____d281 : DEF_f_deqEn_lat_1_wget____d281));
    DEF_f_deqEn_lat_whas__5_CONCAT_IF_f_deqEn_lat_whas_ETC___d138 = (tUInt8)3u & ((DEF_f_deqEn_lat_whas____d287 << 1u) | (DEF_f_deqEn_lat_whas____d287 ? DEF_f_deqEn_lat_wget____d280 : DEF_f_deqEn_lat_wget____d280));
    DEF_f_enqEn_lat_whas__5_CONCAT_IF_f_enqEn_lat_whas_ETC___d124 = (tUInt8)3u & ((DEF_f_enqEn_lat_whas____d285 << 1u) | (DEF_f_enqEn_lat_whas____d285 ? DEF_f_enqEn_lat_wget____d278 : DEF_f_enqEn_lat_wget____d278));
    DEF_f_enqEn_lat_1_whas__3_CONCAT_IF_f_enqEn_lat_1__ETC___d126 = (tUInt8)3u & ((DEF_f_enqEn_lat_1_whas____d286 << 1u) | (DEF_f_enqEn_lat_1_whas____d286 ? DEF_f_enqEn_lat_1_wget____d279 : DEF_f_enqEn_lat_1_wget____d279));
    if (DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d122)
      INST_f_enqEn_lat_2.METH_wset((tUInt8)1u);
    if (DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d122)
      INST_f_enqEn_dummy2_2.METH_write((tUInt8)1u);
    if (DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d122)
      INST_f_enqEn_dummy_6.METH_wset(DEF_f_enqEn_lat_whas__5_CONCAT_IF_f_enqEn_lat_whas_ETC___d124);
    if (DEF_IF_f_enqEn_dummy2_2_00_THEN_IF_f_enqEn_lat_1_w_ETC___d122)
      INST_f_enqEn_dummy_7.METH_wset(DEF_f_enqEn_lat_1_whas__3_CONCAT_IF_f_enqEn_lat_1__ETC___d126);
    if (DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d136)
      INST_f_deqEn_lat_2.METH_wset((tUInt8)1u);
    if (DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d136)
      INST_f_deqEn_dummy2_2.METH_write((tUInt8)1u);
    if (DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d136)
      INST_f_deqEn_dummy_7.METH_wset(DEF_f_deqEn_lat_1_whas__3_CONCAT_IF_f_deqEn_lat_1__ETC___d140);
    if (DEF_IF_f_deqEn_dummy2_2_27_THEN_IF_f_deqEn_lat_1_w_ETC___d136)
      INST_f_deqEn_dummy_6.METH_wset(DEF_f_deqEn_lat_whas__5_CONCAT_IF_f_deqEn_lat_whas_ETC___d138);
    if (DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d148)
      INST_f_data.METH_write(DEF_IF_f_tempData_dummy2_1_49_THEN_IF_f_tempData_l_ETC___d303);
    if (DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d152)
      INST_f_data_1.METH_write(DEF_IF_f_tempData_dummy2_1_49_THEN_IF_f_tempData_l_ETC___d303);
    if (DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d154)
      INST_f_data_2.METH_write(DEF_IF_f_tempData_dummy2_1_49_THEN_IF_f_tempData_l_ETC___d303);
    if (DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d156)
      INST_f_data_3.METH_write(DEF_IF_f_tempData_dummy2_1_49_THEN_IF_f_tempData_l_ETC___d303);
    if (DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143)
      INST_f_tempEnqP_lat_1.METH_wset(DEF__0_CONCAT_DONTCARE___d282);
    if (DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143)
      INST_f_tempEnqP_dummy2_1.METH_write((tUInt8)1u);
    if (DEF_NOT_f_tempEnqP_dummy2_1_41_42_OR_IF_f_tempEnqP_ETC___d143)
      INST_f_tempEnqP_dummy_2.METH_wset(DEF_f_tempEnqP_lat_whas__1_CONCAT_IF_f_tempEnqP_la_ETC___d162);
  }
  
  void MOD_mkBoothTb::RL_enq()
  {
    tUInt8 DEF_x__h14636;
    tUInt8 DEF__4_CONCAT_IF_f_enqP_dummy2_83_AND_f_enqP_dummy2_ETC___d189;
    tUInt32 DEF_TASK_getRandom_74_BITS_15_TO_0_75_CONCAT_TASK__ETC___d182;
    tUInt64 DEF_x__h14036;
    tUInt64 DEF_x__h14064;
    tUInt64 DEF_x__h14091;
    tUInt32 DEF_x__h14868;
    tUInt8 DEF_x__h14673;
    tUInt32 DEF_x__h14289;
    tUInt32 DEF_x__h14290;
    tUInt8 DEF_f_enqP_dummy2__h14501;
    tUInt8 DEF_f_enqP_dummy2_1__h14513;
    DEF_x__h14887 = INST_enqCount.METH_read();
    DEF_upd__h14458 = INST_f_enqP_rl.METH_read();
    DEF_f_enqP_dummy2_2__h10542 = INST_f_enqP_dummy2_2.METH_read();
    DEF_f_enqP_dummy2__h14501 = INST_f_enqP_dummy2.METH_read();
    DEF_f_enqP_dummy2_1__h14513 = INST_f_enqP_dummy2_1.METH_read();
    DEF_x__h14673 = (DEF_f_enqP_dummy2__h14501 && DEF_f_enqP_dummy2_1__h14513) && DEF_f_enqP_dummy2_2__h10542 ? DEF_upd__h14458 : DEF_upd__h14458;
    DEF_x__h14868 = 65535u & (DEF_x__h14887 + 1u);
    DEF__4_CONCAT_IF_f_enqP_dummy2_83_AND_f_enqP_dummy2_ETC___d189 = (tUInt8)31u & (((tUInt8)4u << 2u) | (tUInt8)((tUInt8)3u & DEF_x__h14673));
    DEF_x__h14636 = (tUInt8)15u & ((tUInt8)((tUInt8)7u & ((tUInt8)15u & (DEF_x__h14673 + (tUInt8)1u))));
    if (!(PORT_RST_N == (tUInt8)0u))
      DEF_TASK_getRandom___d174 = getRandom();
    DEF_x__h14289 = (tUInt32)(65535u & DEF_TASK_getRandom___d174);
    DEF_x__h14064 = 8589934591llu & ((((tUInt64)(65535u & -DEF_x__h14289)) << 17u) | (tUInt64)(0u));
    DEF_x__h14036 = 8589934591llu & ((((tUInt64)(DEF_x__h14289)) << 17u) | (tUInt64)(0u));
    if (!(PORT_RST_N == (tUInt8)0u))
      DEF_TASK_getRandom___d179 = getRandom();
    DEF_x__h14290 = (tUInt32)(65535u & DEF_TASK_getRandom___d179);
    DEF_x__h14091 = 8589934591llu & ((((tUInt64)(DEF_x__h14290)) << 1u) | (tUInt64)((tUInt8)0u));
    DEF_TASK_getRandom_74_BITS_15_TO_0_75_CONCAT_TASK__ETC___d182 = (DEF_x__h14289 << 16u) | DEF_x__h14290;
    INST_mult_a.METH_write(DEF_x__h14036);
    INST_mult_s.METH_write(DEF_x__h14064);
    INST_mult_p.METH_write(DEF_x__h14091);
    INST_mult_i.METH_write((tUInt8)0u);
    INST_f_tempData_lat.METH_wset(DEF_TASK_getRandom_74_BITS_15_TO_0_75_CONCAT_TASK__ETC___d182);
    INST_f_tempData_dummy2.METH_write((tUInt8)1u);
    INST_f_tempEnqP_lat.METH_wset(DEF__4_CONCAT_IF_f_enqP_dummy2_83_AND_f_enqP_dummy2_ETC___d189);
    INST_f_tempEnqP_dummy2.METH_write((tUInt8)1u);
    INST_f_enqP_lat.METH_wset(DEF_x__h14636);
    INST_f_enqP_dummy2.METH_write((tUInt8)1u);
    INST_f_enqEn_lat.METH_wset((tUInt8)0u);
    INST_f_enqEn_dummy2.METH_write((tUInt8)1u);
    INST_enqCount.METH_write(DEF_x__h14868);
  }
  
  void MOD_mkBoothTb::RL_deq()
  {
    tUInt8 DEF_x__h15042;
    tUInt32 DEF_x__h15868;
    tUInt32 DEF_v2__h15370;
    tUInt32 DEF_v1__h15369;
    tUInt8 DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dum_ETC___d241;
    tUInt8 DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d299;
    tUInt8 DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d300;
    tUInt8 DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d298;
    tUInt8 DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d292;
    tUInt32 DEF_k1__h15626;
    tUInt32 DEF_k2__h15627;
    tUInt32 DEF_k3__h15628;
    tUInt32 DEF_k4__h15629;
    tUInt32 DEF_val2__h14900;
    tUInt8 DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d263;
    tUInt32 DEF_val1__h14899;
    tUInt8 DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d260;
    tUInt8 DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d264;
    tUInt8 DEF_x__h15094;
    tUInt8 DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d297;
    tUInt32 DEF__read_snd__h15503;
    tUInt32 DEF__read_fst__h15502;
    tUInt32 DEF__read_snd__h15507;
    tUInt32 DEF__read_fst__h15506;
    tUInt32 DEF__read_snd__h15511;
    tUInt32 DEF__read_fst__h15510;
    tUInt32 DEF__read_snd__h15515;
    tUInt32 DEF__read_fst__h15514;
    tUInt64 DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d291;
    tUInt32 DEF_actual__h15371;
    tUInt8 DEF_f_deqP_dummy2__h15153;
    tUInt8 DEF_f_deqP_dummy2_1__h15165;
    tUInt32 DEF_ab__h15500;
    tUInt32 DEF_ab__h15504;
    tUInt32 DEF_ab__h15508;
    tUInt32 DEF_ab__h15512;
    DEF_mult_p__h15599 = INST_mult_p.METH_read();
    DEF_ab__h15512 = INST_f_data_3.METH_read();
    DEF_ab__h15508 = INST_f_data_2.METH_read();
    DEF_ab__h15504 = INST_f_data_1.METH_read();
    DEF_ab__h15500 = INST_f_data.METH_read();
    DEF_upd__h15110 = INST_f_deqP_rl.METH_read();
    DEF_x__h15872 = INST_deqCount.METH_read();
    DEF_f_deqP_dummy2_2__h10822 = INST_f_deqP_dummy2_2.METH_read();
    DEF_f_deqP_dummy2_1__h15165 = INST_f_deqP_dummy2_1.METH_read();
    DEF_f_deqP_dummy2__h15153 = INST_f_deqP_dummy2.METH_read();
    DEF_res__h15368 = (tUInt32)(DEF_mult_p__h15599 >> 1u);
    DEF__read_fst__h15514 = (tUInt32)(DEF_ab__h15512 >> 16u);
    DEF__read_snd__h15515 = (tUInt32)(65535u & DEF_ab__h15512);
    DEF__read_snd__h15511 = (tUInt32)(65535u & DEF_ab__h15508);
    DEF__read_fst__h15510 = (tUInt32)(DEF_ab__h15508 >> 16u);
    DEF__read_fst__h15506 = (tUInt32)(DEF_ab__h15504 >> 16u);
    DEF__read_snd__h15507 = (tUInt32)(65535u & DEF_ab__h15504);
    DEF__read_fst__h15502 = (tUInt32)(DEF_ab__h15500 >> 16u);
    DEF__read_snd__h15503 = (tUInt32)(65535u & DEF_ab__h15500);
    DEF_x__h15094 = (DEF_f_deqP_dummy2__h15153 && DEF_f_deqP_dummy2_1__h15165) && DEF_f_deqP_dummy2_2__h10822 ? DEF_upd__h15110 : DEF_upd__h15110;
    DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d297 = (tUInt8)((tUInt8)3u & DEF_x__h15094);
    DEF_mult_p_BIT_32___h625 = (tUInt8)(DEF_mult_p__h15599 >> 32u);
    DEF_str3__h15624 = DEF_mult_p_BIT_32___h625 ? __str_literal_1 : __str_literal_2;
    DEF_k3__h15628 = DEF_mult_p_BIT_32___h625 ? -DEF_res__h15368 : DEF_res__h15368;
    DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d292 = DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d297 == (tUInt8)0u;
    DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d298 = DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d297 == (tUInt8)1u;
    DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d300 = DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d297 == (tUInt8)3u;
    DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d299 = DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d297 == (tUInt8)2u;
    DEF_val1__h14899 = DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d292 ? DEF__read_fst__h15502 : (DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d298 ? DEF__read_fst__h15506 : (DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d299 ? DEF__read_fst__h15510 : (DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d300 ? DEF__read_fst__h15514 : DEF__read_fst__h15514)));
    DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d260 = (tUInt8)(DEF_val1__h14899 >> 15u);
    DEF_val2__h14900 = DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d292 ? DEF__read_snd__h15503 : (DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d298 ? DEF__read_snd__h15507 : (DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d299 ? DEF__read_snd__h15511 : (DEF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04_05__ETC___d300 ? DEF__read_snd__h15515 : DEF__read_snd__h15515)));
    DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d263 = (tUInt8)(DEF_val2__h14900 >> 15u);
    DEF_str2__h15623 = DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d263 ? __str_literal_1 : __str_literal_2;
    DEF_str1__h15622 = DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d260 ? __str_literal_1 : __str_literal_2;
    DEF_k2__h15627 = DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d263 ? 65535u & -DEF_val2__h14900 : DEF_val2__h14900;
    DEF_k1__h15626 = DEF_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2_1_04__ETC___d260 ? 65535u & -DEF_val1__h14899 : DEF_val1__h14899;
    DEF_v1__h15369 = primSignExt32(32u, 16u, (tUInt32)(DEF_val1__h14899));
    DEF_v2__h15370 = primSignExt32(32u, 16u, (tUInt32)(DEF_val2__h14900));
    DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d291 = ((tUInt64)(DEF_v1__h15369)) * ((tUInt64)(DEF_v2__h15370));
    DEF_actual__h15371 = (tUInt32)(DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d291);
    DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d264 = (tUInt8)((tUInt8)1u & (DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d291 >> 31u));
    DEF_str4__h15625 = DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d264 ? __str_literal_1 : __str_literal_2;
    DEF_k4__h15629 = DEF_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dummy2__ETC___d264 ? -DEF_actual__h15371 : DEF_actual__h15371;
    DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dum_ETC___d241 = !(DEF_actual__h15371 == DEF_res__h15368);
    DEF_x__h15868 = 65535u & (DEF_x__h15872 + 1u);
    DEF_x__h15042 = (tUInt8)15u & ((tUInt8)((tUInt8)7u & ((tUInt8)15u & (DEF_x__h15094 + (tUInt8)1u))));
    INST_f_deqP_lat.METH_wset(DEF_x__h15042);
    INST_f_deqP_dummy2.METH_write((tUInt8)1u);
    INST_f_deqEn_lat.METH_wset((tUInt8)0u);
    INST_f_deqEn_dummy2.METH_write((tUInt8)1u);
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      if (DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dum_ETC___d241)
	dollar_display(this,
		       "s,s,16,s,16,s,32,s,32",
		       &__str_literal_3,
		       &DEF_str1__h15622,
		       DEF_k1__h15626,
		       &DEF_str2__h15623,
		       DEF_k2__h15627,
		       &DEF_str4__h15625,
		       DEF_k4__h15629,
		       &DEF_str3__h15624,
		       DEF_k3__h15628);
      if (DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_03_AND_f_deqP_dum_ETC___d241)
	dollar_finish("32", 1u);
      dollar_display(this,
		     "s,16,16,32",
		     &__str_literal_4,
		     DEF_val1__h14899,
		     DEF_val2__h14900,
		     DEF_res__h15368);
    }
    INST_deqCount.METH_write(DEF_x__h15868);
  }
  
  void MOD_mkBoothTb::RL_fin()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      dollar_display(this, "s", &__str_literal_5);
      dollar_finish("32", 1u);
    }
  }
  
  
  /* Methods */
  
  
  /* Reset routines */
  
  void MOD_mkBoothTb::reset_RST_N(tUInt8 ARG_rst_in)
  {
    PORT_RST_N = ARG_rst_in;
    INST_randomVal2_init.reset_RST_N(ARG_rst_in);
    INST_randomVal1_init.reset_RST_N(ARG_rst_in);
    INST_mult_i.reset_RST_N(ARG_rst_in);
    INST_f_tempEnqP_rl.reset_RST_N(ARG_rst_in);
    INST_f_tempEnqP_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_tempEnqP_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_tempData_rl.reset_RST_N(ARG_rst_in);
    INST_f_tempData_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_tempData_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_enqP_rl.reset_RST_N(ARG_rst_in);
    INST_f_enqP_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_enqP_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_enqP_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_rl.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_deqP_rl.reset_RST_N(ARG_rst_in);
    INST_f_deqP_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_deqP_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_deqP_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_rl.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_dummy2.reset_RST_N(ARG_rst_in);
    INST_enqCount.reset_RST_N(ARG_rst_in);
    INST_deqCount.reset_RST_N(ARG_rst_in);
  }
  
  
  /* Static handles to reset routines */
  
  
  /* Functions for the parent module to register its reset fns */
  
  
  /* Functions to set the elaborated clock id */
  
  void MOD_mkBoothTb::set_clk_0(char const *s)
  {
    __clk_handle_0 = bk_get_or_define_clock(s);
  }
  
  
  /* State dumping routine */
  void MOD_mkBoothTb::dump_state(unsigned int indent)
  {
    printf("%*s%s:\n", indent, "", inst_name);
    INST_deqCount.dump_state(indent + 2u);
    INST_enqCount.dump_state(indent + 2u);
    INST_f_data.dump_state(indent + 2u);
    INST_f_data_1.dump_state(indent + 2u);
    INST_f_data_2.dump_state(indent + 2u);
    INST_f_data_3.dump_state(indent + 2u);
    INST_f_deqEn_dummy.dump_state(indent + 2u);
    INST_f_deqEn_dummy2.dump_state(indent + 2u);
    INST_f_deqEn_dummy2_1.dump_state(indent + 2u);
    INST_f_deqEn_dummy2_2.dump_state(indent + 2u);
    INST_f_deqEn_dummy_1.dump_state(indent + 2u);
    INST_f_deqEn_dummy_2.dump_state(indent + 2u);
    INST_f_deqEn_dummy_3.dump_state(indent + 2u);
    INST_f_deqEn_dummy_4.dump_state(indent + 2u);
    INST_f_deqEn_dummy_5.dump_state(indent + 2u);
    INST_f_deqEn_dummy_6.dump_state(indent + 2u);
    INST_f_deqEn_dummy_7.dump_state(indent + 2u);
    INST_f_deqEn_dummy_8.dump_state(indent + 2u);
    INST_f_deqEn_lat.dump_state(indent + 2u);
    INST_f_deqEn_lat_1.dump_state(indent + 2u);
    INST_f_deqEn_lat_2.dump_state(indent + 2u);
    INST_f_deqEn_rl.dump_state(indent + 2u);
    INST_f_deqP_dummy.dump_state(indent + 2u);
    INST_f_deqP_dummy2.dump_state(indent + 2u);
    INST_f_deqP_dummy2_1.dump_state(indent + 2u);
    INST_f_deqP_dummy2_2.dump_state(indent + 2u);
    INST_f_deqP_dummy_1.dump_state(indent + 2u);
    INST_f_deqP_dummy_2.dump_state(indent + 2u);
    INST_f_deqP_dummy_3.dump_state(indent + 2u);
    INST_f_deqP_dummy_4.dump_state(indent + 2u);
    INST_f_deqP_dummy_5.dump_state(indent + 2u);
    INST_f_deqP_dummy_6.dump_state(indent + 2u);
    INST_f_deqP_dummy_7.dump_state(indent + 2u);
    INST_f_deqP_dummy_8.dump_state(indent + 2u);
    INST_f_deqP_lat.dump_state(indent + 2u);
    INST_f_deqP_lat_1.dump_state(indent + 2u);
    INST_f_deqP_lat_2.dump_state(indent + 2u);
    INST_f_deqP_rl.dump_state(indent + 2u);
    INST_f_enqEn_dummy.dump_state(indent + 2u);
    INST_f_enqEn_dummy2.dump_state(indent + 2u);
    INST_f_enqEn_dummy2_1.dump_state(indent + 2u);
    INST_f_enqEn_dummy2_2.dump_state(indent + 2u);
    INST_f_enqEn_dummy_1.dump_state(indent + 2u);
    INST_f_enqEn_dummy_2.dump_state(indent + 2u);
    INST_f_enqEn_dummy_3.dump_state(indent + 2u);
    INST_f_enqEn_dummy_4.dump_state(indent + 2u);
    INST_f_enqEn_dummy_5.dump_state(indent + 2u);
    INST_f_enqEn_dummy_6.dump_state(indent + 2u);
    INST_f_enqEn_dummy_7.dump_state(indent + 2u);
    INST_f_enqEn_dummy_8.dump_state(indent + 2u);
    INST_f_enqEn_lat.dump_state(indent + 2u);
    INST_f_enqEn_lat_1.dump_state(indent + 2u);
    INST_f_enqEn_lat_2.dump_state(indent + 2u);
    INST_f_enqEn_rl.dump_state(indent + 2u);
    INST_f_enqP_dummy.dump_state(indent + 2u);
    INST_f_enqP_dummy2.dump_state(indent + 2u);
    INST_f_enqP_dummy2_1.dump_state(indent + 2u);
    INST_f_enqP_dummy2_2.dump_state(indent + 2u);
    INST_f_enqP_dummy_1.dump_state(indent + 2u);
    INST_f_enqP_dummy_2.dump_state(indent + 2u);
    INST_f_enqP_dummy_3.dump_state(indent + 2u);
    INST_f_enqP_dummy_4.dump_state(indent + 2u);
    INST_f_enqP_dummy_5.dump_state(indent + 2u);
    INST_f_enqP_dummy_6.dump_state(indent + 2u);
    INST_f_enqP_dummy_7.dump_state(indent + 2u);
    INST_f_enqP_dummy_8.dump_state(indent + 2u);
    INST_f_enqP_lat.dump_state(indent + 2u);
    INST_f_enqP_lat_1.dump_state(indent + 2u);
    INST_f_enqP_lat_2.dump_state(indent + 2u);
    INST_f_enqP_rl.dump_state(indent + 2u);
    INST_f_tempData_dummy.dump_state(indent + 2u);
    INST_f_tempData_dummy2.dump_state(indent + 2u);
    INST_f_tempData_dummy2_1.dump_state(indent + 2u);
    INST_f_tempData_dummy_1.dump_state(indent + 2u);
    INST_f_tempData_dummy_2.dump_state(indent + 2u);
    INST_f_tempData_dummy_3.dump_state(indent + 2u);
    INST_f_tempData_lat.dump_state(indent + 2u);
    INST_f_tempData_lat_1.dump_state(indent + 2u);
    INST_f_tempData_rl.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy2.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy2_1.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy_1.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy_2.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy_3.dump_state(indent + 2u);
    INST_f_tempEnqP_lat.dump_state(indent + 2u);
    INST_f_tempEnqP_lat_1.dump_state(indent + 2u);
    INST_f_tempEnqP_rl.dump_state(indent + 2u);
    INST_mult_a.dump_state(indent + 2u);
    INST_mult_i.dump_state(indent + 2u);
    INST_mult_p.dump_state(indent + 2u);
    INST_mult_s.dump_state(indent + 2u);
    INST_randomVal1_init.dump_state(indent + 2u);
    INST_randomVal2_init.dump_state(indent + 2u);
  }
  
  
  /* VCD dumping routines */
  
  unsigned int MOD_mkBoothTb::dump_VCD_defs(unsigned int levels)
  {
    fprintf(vcd_file, "$scope module %s $end\n", inst_name);
    vcd_num = vcd_reserve_ids(137u);
    unsigned int num = vcd_num;
    for (unsigned int hdl = 0u; hdl < bk_num_clocks(); ++hdl)
      vcd_add_clock_def(this, bk_clock_name(hdl), bk_clock_vcd_num(hdl));
    vcd_write_def(bk_clock_vcd_num(__clk_handle_0), "CLK", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276", 4u);
    vcd_write_def(num++, "RST_N", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d174", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d179", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "_read__h193", 5u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "ab__h8769", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "ab__h8773", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_dummy2_2__h11741", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_1_wget____d281", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_1_whas____d288", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_wget____d280", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_whas____d287", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_rl__h7670", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqP_dummy2_2__h10822", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_dummy2_2__h10238", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_1_wget____d279", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_1_whas____d286", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_wget____d278", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_whas____d285", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_rl__h6069", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqP_dummy2_2__h10542", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_wget__2_BIT_4___d294", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_wget____d283", 5u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_whas____d289", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_rl_4_BIT_4___d295", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_rl___d296", 5u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "mult_p_BIT_32___h625", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "mult_p__h15599", 33u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "res__h15368", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h10581", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h10614", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h10861", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h10894", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h14458", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h15110", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "x__h14887", 16u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "x__h15872", 16u);
    num = INST_deqCount.dump_VCD_defs(num);
    num = INST_enqCount.dump_VCD_defs(num);
    num = INST_f_data.dump_VCD_defs(num);
    num = INST_f_data_1.dump_VCD_defs(num);
    num = INST_f_data_2.dump_VCD_defs(num);
    num = INST_f_data_3.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy2.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy2_1.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy2_2.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_1.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_2.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_3.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_4.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_5.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_6.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_7.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_8.dump_VCD_defs(num);
    num = INST_f_deqEn_lat.dump_VCD_defs(num);
    num = INST_f_deqEn_lat_1.dump_VCD_defs(num);
    num = INST_f_deqEn_lat_2.dump_VCD_defs(num);
    num = INST_f_deqEn_rl.dump_VCD_defs(num);
    num = INST_f_deqP_dummy.dump_VCD_defs(num);
    num = INST_f_deqP_dummy2.dump_VCD_defs(num);
    num = INST_f_deqP_dummy2_1.dump_VCD_defs(num);
    num = INST_f_deqP_dummy2_2.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_1.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_2.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_3.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_4.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_5.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_6.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_7.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_8.dump_VCD_defs(num);
    num = INST_f_deqP_lat.dump_VCD_defs(num);
    num = INST_f_deqP_lat_1.dump_VCD_defs(num);
    num = INST_f_deqP_lat_2.dump_VCD_defs(num);
    num = INST_f_deqP_rl.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy2.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy2_1.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy2_2.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_1.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_2.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_3.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_4.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_5.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_6.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_7.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_8.dump_VCD_defs(num);
    num = INST_f_enqEn_lat.dump_VCD_defs(num);
    num = INST_f_enqEn_lat_1.dump_VCD_defs(num);
    num = INST_f_enqEn_lat_2.dump_VCD_defs(num);
    num = INST_f_enqEn_rl.dump_VCD_defs(num);
    num = INST_f_enqP_dummy.dump_VCD_defs(num);
    num = INST_f_enqP_dummy2.dump_VCD_defs(num);
    num = INST_f_enqP_dummy2_1.dump_VCD_defs(num);
    num = INST_f_enqP_dummy2_2.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_1.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_2.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_3.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_4.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_5.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_6.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_7.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_8.dump_VCD_defs(num);
    num = INST_f_enqP_lat.dump_VCD_defs(num);
    num = INST_f_enqP_lat_1.dump_VCD_defs(num);
    num = INST_f_enqP_lat_2.dump_VCD_defs(num);
    num = INST_f_enqP_rl.dump_VCD_defs(num);
    num = INST_f_tempData_dummy.dump_VCD_defs(num);
    num = INST_f_tempData_dummy2.dump_VCD_defs(num);
    num = INST_f_tempData_dummy2_1.dump_VCD_defs(num);
    num = INST_f_tempData_dummy_1.dump_VCD_defs(num);
    num = INST_f_tempData_dummy_2.dump_VCD_defs(num);
    num = INST_f_tempData_dummy_3.dump_VCD_defs(num);
    num = INST_f_tempData_lat.dump_VCD_defs(num);
    num = INST_f_tempData_lat_1.dump_VCD_defs(num);
    num = INST_f_tempData_rl.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy2.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy2_1.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy_1.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy_2.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy_3.dump_VCD_defs(num);
    num = INST_f_tempEnqP_lat.dump_VCD_defs(num);
    num = INST_f_tempEnqP_lat_1.dump_VCD_defs(num);
    num = INST_f_tempEnqP_rl.dump_VCD_defs(num);
    num = INST_mult_a.dump_VCD_defs(num);
    num = INST_mult_i.dump_VCD_defs(num);
    num = INST_mult_p.dump_VCD_defs(num);
    num = INST_mult_s.dump_VCD_defs(num);
    num = INST_randomVal1_init.dump_VCD_defs(num);
    num = INST_randomVal2_init.dump_VCD_defs(num);
    fprintf(vcd_file, "$upscope $end\n");
    return num;
  }
  
  void MOD_mkBoothTb::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBoothTb &backing)
  {
    vcd_defs(dt, backing);
    vcd_prims(dt, backing);
  }
  
  void MOD_mkBoothTb::vcd_defs(tVCDDumpType dt, MOD_mkBoothTb &backing)
  {
    unsigned int num = vcd_num;
    if (dt == VCD_DUMP_XS)
    {
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 5u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 5u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 5u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 33u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 16u);
      vcd_write_x(num++, 16u);
    }
    else
      if (dt == VCD_DUMP_CHANGES)
      {
	if ((backing.DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274) != DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274)
	{
	  vcd_write_val(num, DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274, 4u);
	  backing.DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274 = DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274;
	}
	++num;
	if ((backing.DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272) != DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272)
	{
	  vcd_write_val(num, DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272, 4u);
	  backing.DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272 = DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272;
	}
	++num;
	if ((backing.DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266) != DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266)
	{
	  vcd_write_val(num, DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266, 32u);
	  backing.DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266 = DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266;
	}
	++num;
	if ((backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259) != DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259)
	{
	  vcd_write_val(num, DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259, 1u);
	  backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259 = DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259;
	}
	++num;
	if ((backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271) != DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271)
	{
	  vcd_write_val(num, DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271, 1u);
	  backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271 = DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271;
	}
	++num;
	if ((backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276) != DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276)
	{
	  vcd_write_val(num, DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276, 4u);
	  backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276 = DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276;
	}
	++num;
	if ((backing.PORT_RST_N) != PORT_RST_N)
	{
	  vcd_write_val(num, PORT_RST_N, 1u);
	  backing.PORT_RST_N = PORT_RST_N;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d174) != DEF_TASK_getRandom___d174)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d174, 32u);
	  backing.DEF_TASK_getRandom___d174 = DEF_TASK_getRandom___d174;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d179) != DEF_TASK_getRandom___d179)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d179, 32u);
	  backing.DEF_TASK_getRandom___d179 = DEF_TASK_getRandom___d179;
	}
	++num;
	if ((backing.DEF__read__h193) != DEF__read__h193)
	{
	  vcd_write_val(num, DEF__read__h193, 5u);
	  backing.DEF__read__h193 = DEF__read__h193;
	}
	++num;
	if ((backing.DEF_ab__h8769) != DEF_ab__h8769)
	{
	  vcd_write_val(num, DEF_ab__h8769, 32u);
	  backing.DEF_ab__h8769 = DEF_ab__h8769;
	}
	++num;
	if ((backing.DEF_ab__h8773) != DEF_ab__h8773)
	{
	  vcd_write_val(num, DEF_ab__h8773, 32u);
	  backing.DEF_ab__h8773 = DEF_ab__h8773;
	}
	++num;
	if ((backing.DEF_f_deqEn_dummy2_2__h11741) != DEF_f_deqEn_dummy2_2__h11741)
	{
	  vcd_write_val(num, DEF_f_deqEn_dummy2_2__h11741, 1u);
	  backing.DEF_f_deqEn_dummy2_2__h11741 = DEF_f_deqEn_dummy2_2__h11741;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_1_wget____d281) != DEF_f_deqEn_lat_1_wget____d281)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_1_wget____d281, 1u);
	  backing.DEF_f_deqEn_lat_1_wget____d281 = DEF_f_deqEn_lat_1_wget____d281;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_1_whas____d288) != DEF_f_deqEn_lat_1_whas____d288)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_1_whas____d288, 1u);
	  backing.DEF_f_deqEn_lat_1_whas____d288 = DEF_f_deqEn_lat_1_whas____d288;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_wget____d280) != DEF_f_deqEn_lat_wget____d280)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_wget____d280, 1u);
	  backing.DEF_f_deqEn_lat_wget____d280 = DEF_f_deqEn_lat_wget____d280;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_whas____d287) != DEF_f_deqEn_lat_whas____d287)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_whas____d287, 1u);
	  backing.DEF_f_deqEn_lat_whas____d287 = DEF_f_deqEn_lat_whas____d287;
	}
	++num;
	if ((backing.DEF_f_deqEn_rl__h7670) != DEF_f_deqEn_rl__h7670)
	{
	  vcd_write_val(num, DEF_f_deqEn_rl__h7670, 1u);
	  backing.DEF_f_deqEn_rl__h7670 = DEF_f_deqEn_rl__h7670;
	}
	++num;
	if ((backing.DEF_f_deqP_dummy2_2__h10822) != DEF_f_deqP_dummy2_2__h10822)
	{
	  vcd_write_val(num, DEF_f_deqP_dummy2_2__h10822, 1u);
	  backing.DEF_f_deqP_dummy2_2__h10822 = DEF_f_deqP_dummy2_2__h10822;
	}
	++num;
	if ((backing.DEF_f_enqEn_dummy2_2__h10238) != DEF_f_enqEn_dummy2_2__h10238)
	{
	  vcd_write_val(num, DEF_f_enqEn_dummy2_2__h10238, 1u);
	  backing.DEF_f_enqEn_dummy2_2__h10238 = DEF_f_enqEn_dummy2_2__h10238;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_1_wget____d279) != DEF_f_enqEn_lat_1_wget____d279)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_1_wget____d279, 1u);
	  backing.DEF_f_enqEn_lat_1_wget____d279 = DEF_f_enqEn_lat_1_wget____d279;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_1_whas____d286) != DEF_f_enqEn_lat_1_whas____d286)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_1_whas____d286, 1u);
	  backing.DEF_f_enqEn_lat_1_whas____d286 = DEF_f_enqEn_lat_1_whas____d286;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_wget____d278) != DEF_f_enqEn_lat_wget____d278)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_wget____d278, 1u);
	  backing.DEF_f_enqEn_lat_wget____d278 = DEF_f_enqEn_lat_wget____d278;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_whas____d285) != DEF_f_enqEn_lat_whas____d285)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_whas____d285, 1u);
	  backing.DEF_f_enqEn_lat_whas____d285 = DEF_f_enqEn_lat_whas____d285;
	}
	++num;
	if ((backing.DEF_f_enqEn_rl__h6069) != DEF_f_enqEn_rl__h6069)
	{
	  vcd_write_val(num, DEF_f_enqEn_rl__h6069, 1u);
	  backing.DEF_f_enqEn_rl__h6069 = DEF_f_enqEn_rl__h6069;
	}
	++num;
	if ((backing.DEF_f_enqP_dummy2_2__h10542) != DEF_f_enqP_dummy2_2__h10542)
	{
	  vcd_write_val(num, DEF_f_enqP_dummy2_2__h10542, 1u);
	  backing.DEF_f_enqP_dummy2_2__h10542 = DEF_f_enqP_dummy2_2__h10542;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277) != DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277, 4u);
	  backing.DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277 = DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_wget__2_BIT_4___d294) != DEF_f_tempEnqP_lat_wget__2_BIT_4___d294)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_wget__2_BIT_4___d294, 1u);
	  backing.DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 = DEF_f_tempEnqP_lat_wget__2_BIT_4___d294;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_wget____d283) != DEF_f_tempEnqP_lat_wget____d283)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_wget____d283, 5u);
	  backing.DEF_f_tempEnqP_lat_wget____d283 = DEF_f_tempEnqP_lat_wget____d283;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_whas____d289) != DEF_f_tempEnqP_lat_whas____d289)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_whas____d289, 1u);
	  backing.DEF_f_tempEnqP_lat_whas____d289 = DEF_f_tempEnqP_lat_whas____d289;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_rl_4_BIT_4___d295) != DEF_f_tempEnqP_rl_4_BIT_4___d295)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_rl_4_BIT_4___d295, 1u);
	  backing.DEF_f_tempEnqP_rl_4_BIT_4___d295 = DEF_f_tempEnqP_rl_4_BIT_4___d295;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_rl___d296) != DEF_f_tempEnqP_rl___d296)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_rl___d296, 5u);
	  backing.DEF_f_tempEnqP_rl___d296 = DEF_f_tempEnqP_rl___d296;
	}
	++num;
	if ((backing.DEF_mult_p_BIT_32___h625) != DEF_mult_p_BIT_32___h625)
	{
	  vcd_write_val(num, DEF_mult_p_BIT_32___h625, 1u);
	  backing.DEF_mult_p_BIT_32___h625 = DEF_mult_p_BIT_32___h625;
	}
	++num;
	if ((backing.DEF_mult_p__h15599) != DEF_mult_p__h15599)
	{
	  vcd_write_val(num, DEF_mult_p__h15599, 33u);
	  backing.DEF_mult_p__h15599 = DEF_mult_p__h15599;
	}
	++num;
	if ((backing.DEF_res__h15368) != DEF_res__h15368)
	{
	  vcd_write_val(num, DEF_res__h15368, 32u);
	  backing.DEF_res__h15368 = DEF_res__h15368;
	}
	++num;
	if ((backing.DEF_upd__h10581) != DEF_upd__h10581)
	{
	  vcd_write_val(num, DEF_upd__h10581, 4u);
	  backing.DEF_upd__h10581 = DEF_upd__h10581;
	}
	++num;
	if ((backing.DEF_upd__h10614) != DEF_upd__h10614)
	{
	  vcd_write_val(num, DEF_upd__h10614, 4u);
	  backing.DEF_upd__h10614 = DEF_upd__h10614;
	}
	++num;
	if ((backing.DEF_upd__h10861) != DEF_upd__h10861)
	{
	  vcd_write_val(num, DEF_upd__h10861, 4u);
	  backing.DEF_upd__h10861 = DEF_upd__h10861;
	}
	++num;
	if ((backing.DEF_upd__h10894) != DEF_upd__h10894)
	{
	  vcd_write_val(num, DEF_upd__h10894, 4u);
	  backing.DEF_upd__h10894 = DEF_upd__h10894;
	}
	++num;
	if ((backing.DEF_upd__h14458) != DEF_upd__h14458)
	{
	  vcd_write_val(num, DEF_upd__h14458, 4u);
	  backing.DEF_upd__h14458 = DEF_upd__h14458;
	}
	++num;
	if ((backing.DEF_upd__h15110) != DEF_upd__h15110)
	{
	  vcd_write_val(num, DEF_upd__h15110, 4u);
	  backing.DEF_upd__h15110 = DEF_upd__h15110;
	}
	++num;
	if ((backing.DEF_x__h14887) != DEF_x__h14887)
	{
	  vcd_write_val(num, DEF_x__h14887, 16u);
	  backing.DEF_x__h14887 = DEF_x__h14887;
	}
	++num;
	if ((backing.DEF_x__h15872) != DEF_x__h15872)
	{
	  vcd_write_val(num, DEF_x__h15872, 16u);
	  backing.DEF_x__h15872 = DEF_x__h15872;
	}
	++num;
      }
      else
      {
	vcd_write_val(num++, DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274, 4u);
	backing.DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274 = DEF_IF_f_deqP_lat_1_whas__3_THEN_f_deqP_lat_1_wget_ETC___d274;
	vcd_write_val(num++, DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272, 4u);
	backing.DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272 = DEF_IF_f_enqP_lat_1_whas__3_THEN_f_enqP_lat_1_wget_ETC___d272;
	vcd_write_val(num++, DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266, 32u);
	backing.DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266 = DEF_IF_f_tempData_lat_whas__3_THEN_f_tempData_lat__ETC___d266;
	vcd_write_val(num++, DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259, 1u);
	backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259 = DEF_IF_f_tempEnqP_lat_whas__1_THEN_NOT_f_tempEnqP__ETC___d259;
	vcd_write_val(num++, DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271, 1u);
	backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271 = DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d271;
	vcd_write_val(num++, DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276, 4u);
	backing.DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276 = DEF_IF_f_tempEnqP_lat_whas__1_THEN_f_tempEnqP_lat__ETC___d276;
	vcd_write_val(num++, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
	vcd_write_val(num++, DEF_TASK_getRandom___d174, 32u);
	backing.DEF_TASK_getRandom___d174 = DEF_TASK_getRandom___d174;
	vcd_write_val(num++, DEF_TASK_getRandom___d179, 32u);
	backing.DEF_TASK_getRandom___d179 = DEF_TASK_getRandom___d179;
	vcd_write_val(num++, DEF__read__h193, 5u);
	backing.DEF__read__h193 = DEF__read__h193;
	vcd_write_val(num++, DEF_ab__h8769, 32u);
	backing.DEF_ab__h8769 = DEF_ab__h8769;
	vcd_write_val(num++, DEF_ab__h8773, 32u);
	backing.DEF_ab__h8773 = DEF_ab__h8773;
	vcd_write_val(num++, DEF_f_deqEn_dummy2_2__h11741, 1u);
	backing.DEF_f_deqEn_dummy2_2__h11741 = DEF_f_deqEn_dummy2_2__h11741;
	vcd_write_val(num++, DEF_f_deqEn_lat_1_wget____d281, 1u);
	backing.DEF_f_deqEn_lat_1_wget____d281 = DEF_f_deqEn_lat_1_wget____d281;
	vcd_write_val(num++, DEF_f_deqEn_lat_1_whas____d288, 1u);
	backing.DEF_f_deqEn_lat_1_whas____d288 = DEF_f_deqEn_lat_1_whas____d288;
	vcd_write_val(num++, DEF_f_deqEn_lat_wget____d280, 1u);
	backing.DEF_f_deqEn_lat_wget____d280 = DEF_f_deqEn_lat_wget____d280;
	vcd_write_val(num++, DEF_f_deqEn_lat_whas____d287, 1u);
	backing.DEF_f_deqEn_lat_whas____d287 = DEF_f_deqEn_lat_whas____d287;
	vcd_write_val(num++, DEF_f_deqEn_rl__h7670, 1u);
	backing.DEF_f_deqEn_rl__h7670 = DEF_f_deqEn_rl__h7670;
	vcd_write_val(num++, DEF_f_deqP_dummy2_2__h10822, 1u);
	backing.DEF_f_deqP_dummy2_2__h10822 = DEF_f_deqP_dummy2_2__h10822;
	vcd_write_val(num++, DEF_f_enqEn_dummy2_2__h10238, 1u);
	backing.DEF_f_enqEn_dummy2_2__h10238 = DEF_f_enqEn_dummy2_2__h10238;
	vcd_write_val(num++, DEF_f_enqEn_lat_1_wget____d279, 1u);
	backing.DEF_f_enqEn_lat_1_wget____d279 = DEF_f_enqEn_lat_1_wget____d279;
	vcd_write_val(num++, DEF_f_enqEn_lat_1_whas____d286, 1u);
	backing.DEF_f_enqEn_lat_1_whas____d286 = DEF_f_enqEn_lat_1_whas____d286;
	vcd_write_val(num++, DEF_f_enqEn_lat_wget____d278, 1u);
	backing.DEF_f_enqEn_lat_wget____d278 = DEF_f_enqEn_lat_wget____d278;
	vcd_write_val(num++, DEF_f_enqEn_lat_whas____d285, 1u);
	backing.DEF_f_enqEn_lat_whas____d285 = DEF_f_enqEn_lat_whas____d285;
	vcd_write_val(num++, DEF_f_enqEn_rl__h6069, 1u);
	backing.DEF_f_enqEn_rl__h6069 = DEF_f_enqEn_rl__h6069;
	vcd_write_val(num++, DEF_f_enqP_dummy2_2__h10542, 1u);
	backing.DEF_f_enqP_dummy2_2__h10542 = DEF_f_enqP_dummy2_2__h10542;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277, 4u);
	backing.DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277 = DEF_f_tempEnqP_lat_wget__2_BITS_3_TO_0___d277;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_wget__2_BIT_4___d294, 1u);
	backing.DEF_f_tempEnqP_lat_wget__2_BIT_4___d294 = DEF_f_tempEnqP_lat_wget__2_BIT_4___d294;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_wget____d283, 5u);
	backing.DEF_f_tempEnqP_lat_wget____d283 = DEF_f_tempEnqP_lat_wget____d283;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_whas____d289, 1u);
	backing.DEF_f_tempEnqP_lat_whas____d289 = DEF_f_tempEnqP_lat_whas____d289;
	vcd_write_val(num++, DEF_f_tempEnqP_rl_4_BIT_4___d295, 1u);
	backing.DEF_f_tempEnqP_rl_4_BIT_4___d295 = DEF_f_tempEnqP_rl_4_BIT_4___d295;
	vcd_write_val(num++, DEF_f_tempEnqP_rl___d296, 5u);
	backing.DEF_f_tempEnqP_rl___d296 = DEF_f_tempEnqP_rl___d296;
	vcd_write_val(num++, DEF_mult_p_BIT_32___h625, 1u);
	backing.DEF_mult_p_BIT_32___h625 = DEF_mult_p_BIT_32___h625;
	vcd_write_val(num++, DEF_mult_p__h15599, 33u);
	backing.DEF_mult_p__h15599 = DEF_mult_p__h15599;
	vcd_write_val(num++, DEF_res__h15368, 32u);
	backing.DEF_res__h15368 = DEF_res__h15368;
	vcd_write_val(num++, DEF_upd__h10581, 4u);
	backing.DEF_upd__h10581 = DEF_upd__h10581;
	vcd_write_val(num++, DEF_upd__h10614, 4u);
	backing.DEF_upd__h10614 = DEF_upd__h10614;
	vcd_write_val(num++, DEF_upd__h10861, 4u);
	backing.DEF_upd__h10861 = DEF_upd__h10861;
	vcd_write_val(num++, DEF_upd__h10894, 4u);
	backing.DEF_upd__h10894 = DEF_upd__h10894;
	vcd_write_val(num++, DEF_upd__h14458, 4u);
	backing.DEF_upd__h14458 = DEF_upd__h14458;
	vcd_write_val(num++, DEF_upd__h15110, 4u);
	backing.DEF_upd__h15110 = DEF_upd__h15110;
	vcd_write_val(num++, DEF_x__h14887, 16u);
	backing.DEF_x__h14887 = DEF_x__h14887;
	vcd_write_val(num++, DEF_x__h15872, 16u);
	backing.DEF_x__h15872 = DEF_x__h15872;
      }
  }
  
  void MOD_mkBoothTb::vcd_prims(tVCDDumpType dt, MOD_mkBoothTb &backing)
  {
    INST_deqCount.dump_VCD(dt, backing.INST_deqCount);
    INST_enqCount.dump_VCD(dt, backing.INST_enqCount);
    INST_f_data.dump_VCD(dt, backing.INST_f_data);
    INST_f_data_1.dump_VCD(dt, backing.INST_f_data_1);
    INST_f_data_2.dump_VCD(dt, backing.INST_f_data_2);
    INST_f_data_3.dump_VCD(dt, backing.INST_f_data_3);
    INST_f_deqEn_dummy.dump_VCD(dt, backing.INST_f_deqEn_dummy);
    INST_f_deqEn_dummy2.dump_VCD(dt, backing.INST_f_deqEn_dummy2);
    INST_f_deqEn_dummy2_1.dump_VCD(dt, backing.INST_f_deqEn_dummy2_1);
    INST_f_deqEn_dummy2_2.dump_VCD(dt, backing.INST_f_deqEn_dummy2_2);
    INST_f_deqEn_dummy_1.dump_VCD(dt, backing.INST_f_deqEn_dummy_1);
    INST_f_deqEn_dummy_2.dump_VCD(dt, backing.INST_f_deqEn_dummy_2);
    INST_f_deqEn_dummy_3.dump_VCD(dt, backing.INST_f_deqEn_dummy_3);
    INST_f_deqEn_dummy_4.dump_VCD(dt, backing.INST_f_deqEn_dummy_4);
    INST_f_deqEn_dummy_5.dump_VCD(dt, backing.INST_f_deqEn_dummy_5);
    INST_f_deqEn_dummy_6.dump_VCD(dt, backing.INST_f_deqEn_dummy_6);
    INST_f_deqEn_dummy_7.dump_VCD(dt, backing.INST_f_deqEn_dummy_7);
    INST_f_deqEn_dummy_8.dump_VCD(dt, backing.INST_f_deqEn_dummy_8);
    INST_f_deqEn_lat.dump_VCD(dt, backing.INST_f_deqEn_lat);
    INST_f_deqEn_lat_1.dump_VCD(dt, backing.INST_f_deqEn_lat_1);
    INST_f_deqEn_lat_2.dump_VCD(dt, backing.INST_f_deqEn_lat_2);
    INST_f_deqEn_rl.dump_VCD(dt, backing.INST_f_deqEn_rl);
    INST_f_deqP_dummy.dump_VCD(dt, backing.INST_f_deqP_dummy);
    INST_f_deqP_dummy2.dump_VCD(dt, backing.INST_f_deqP_dummy2);
    INST_f_deqP_dummy2_1.dump_VCD(dt, backing.INST_f_deqP_dummy2_1);
    INST_f_deqP_dummy2_2.dump_VCD(dt, backing.INST_f_deqP_dummy2_2);
    INST_f_deqP_dummy_1.dump_VCD(dt, backing.INST_f_deqP_dummy_1);
    INST_f_deqP_dummy_2.dump_VCD(dt, backing.INST_f_deqP_dummy_2);
    INST_f_deqP_dummy_3.dump_VCD(dt, backing.INST_f_deqP_dummy_3);
    INST_f_deqP_dummy_4.dump_VCD(dt, backing.INST_f_deqP_dummy_4);
    INST_f_deqP_dummy_5.dump_VCD(dt, backing.INST_f_deqP_dummy_5);
    INST_f_deqP_dummy_6.dump_VCD(dt, backing.INST_f_deqP_dummy_6);
    INST_f_deqP_dummy_7.dump_VCD(dt, backing.INST_f_deqP_dummy_7);
    INST_f_deqP_dummy_8.dump_VCD(dt, backing.INST_f_deqP_dummy_8);
    INST_f_deqP_lat.dump_VCD(dt, backing.INST_f_deqP_lat);
    INST_f_deqP_lat_1.dump_VCD(dt, backing.INST_f_deqP_lat_1);
    INST_f_deqP_lat_2.dump_VCD(dt, backing.INST_f_deqP_lat_2);
    INST_f_deqP_rl.dump_VCD(dt, backing.INST_f_deqP_rl);
    INST_f_enqEn_dummy.dump_VCD(dt, backing.INST_f_enqEn_dummy);
    INST_f_enqEn_dummy2.dump_VCD(dt, backing.INST_f_enqEn_dummy2);
    INST_f_enqEn_dummy2_1.dump_VCD(dt, backing.INST_f_enqEn_dummy2_1);
    INST_f_enqEn_dummy2_2.dump_VCD(dt, backing.INST_f_enqEn_dummy2_2);
    INST_f_enqEn_dummy_1.dump_VCD(dt, backing.INST_f_enqEn_dummy_1);
    INST_f_enqEn_dummy_2.dump_VCD(dt, backing.INST_f_enqEn_dummy_2);
    INST_f_enqEn_dummy_3.dump_VCD(dt, backing.INST_f_enqEn_dummy_3);
    INST_f_enqEn_dummy_4.dump_VCD(dt, backing.INST_f_enqEn_dummy_4);
    INST_f_enqEn_dummy_5.dump_VCD(dt, backing.INST_f_enqEn_dummy_5);
    INST_f_enqEn_dummy_6.dump_VCD(dt, backing.INST_f_enqEn_dummy_6);
    INST_f_enqEn_dummy_7.dump_VCD(dt, backing.INST_f_enqEn_dummy_7);
    INST_f_enqEn_dummy_8.dump_VCD(dt, backing.INST_f_enqEn_dummy_8);
    INST_f_enqEn_lat.dump_VCD(dt, backing.INST_f_enqEn_lat);
    INST_f_enqEn_lat_1.dump_VCD(dt, backing.INST_f_enqEn_lat_1);
    INST_f_enqEn_lat_2.dump_VCD(dt, backing.INST_f_enqEn_lat_2);
    INST_f_enqEn_rl.dump_VCD(dt, backing.INST_f_enqEn_rl);
    INST_f_enqP_dummy.dump_VCD(dt, backing.INST_f_enqP_dummy);
    INST_f_enqP_dummy2.dump_VCD(dt, backing.INST_f_enqP_dummy2);
    INST_f_enqP_dummy2_1.dump_VCD(dt, backing.INST_f_enqP_dummy2_1);
    INST_f_enqP_dummy2_2.dump_VCD(dt, backing.INST_f_enqP_dummy2_2);
    INST_f_enqP_dummy_1.dump_VCD(dt, backing.INST_f_enqP_dummy_1);
    INST_f_enqP_dummy_2.dump_VCD(dt, backing.INST_f_enqP_dummy_2);
    INST_f_enqP_dummy_3.dump_VCD(dt, backing.INST_f_enqP_dummy_3);
    INST_f_enqP_dummy_4.dump_VCD(dt, backing.INST_f_enqP_dummy_4);
    INST_f_enqP_dummy_5.dump_VCD(dt, backing.INST_f_enqP_dummy_5);
    INST_f_enqP_dummy_6.dump_VCD(dt, backing.INST_f_enqP_dummy_6);
    INST_f_enqP_dummy_7.dump_VCD(dt, backing.INST_f_enqP_dummy_7);
    INST_f_enqP_dummy_8.dump_VCD(dt, backing.INST_f_enqP_dummy_8);
    INST_f_enqP_lat.dump_VCD(dt, backing.INST_f_enqP_lat);
    INST_f_enqP_lat_1.dump_VCD(dt, backing.INST_f_enqP_lat_1);
    INST_f_enqP_lat_2.dump_VCD(dt, backing.INST_f_enqP_lat_2);
    INST_f_enqP_rl.dump_VCD(dt, backing.INST_f_enqP_rl);
    INST_f_tempData_dummy.dump_VCD(dt, backing.INST_f_tempData_dummy);
    INST_f_tempData_dummy2.dump_VCD(dt, backing.INST_f_tempData_dummy2);
    INST_f_tempData_dummy2_1.dump_VCD(dt, backing.INST_f_tempData_dummy2_1);
    INST_f_tempData_dummy_1.dump_VCD(dt, backing.INST_f_tempData_dummy_1);
    INST_f_tempData_dummy_2.dump_VCD(dt, backing.INST_f_tempData_dummy_2);
    INST_f_tempData_dummy_3.dump_VCD(dt, backing.INST_f_tempData_dummy_3);
    INST_f_tempData_lat.dump_VCD(dt, backing.INST_f_tempData_lat);
    INST_f_tempData_lat_1.dump_VCD(dt, backing.INST_f_tempData_lat_1);
    INST_f_tempData_rl.dump_VCD(dt, backing.INST_f_tempData_rl);
    INST_f_tempEnqP_dummy.dump_VCD(dt, backing.INST_f_tempEnqP_dummy);
    INST_f_tempEnqP_dummy2.dump_VCD(dt, backing.INST_f_tempEnqP_dummy2);
    INST_f_tempEnqP_dummy2_1.dump_VCD(dt, backing.INST_f_tempEnqP_dummy2_1);
    INST_f_tempEnqP_dummy_1.dump_VCD(dt, backing.INST_f_tempEnqP_dummy_1);
    INST_f_tempEnqP_dummy_2.dump_VCD(dt, backing.INST_f_tempEnqP_dummy_2);
    INST_f_tempEnqP_dummy_3.dump_VCD(dt, backing.INST_f_tempEnqP_dummy_3);
    INST_f_tempEnqP_lat.dump_VCD(dt, backing.INST_f_tempEnqP_lat);
    INST_f_tempEnqP_lat_1.dump_VCD(dt, backing.INST_f_tempEnqP_lat_1);
    INST_f_tempEnqP_rl.dump_VCD(dt, backing.INST_f_tempEnqP_rl);
    INST_mult_a.dump_VCD(dt, backing.INST_mult_a);
    INST_mult_i.dump_VCD(dt, backing.INST_mult_i);
    INST_mult_p.dump_VCD(dt, backing.INST_mult_p);
    INST_mult_s.dump_VCD(dt, backing.INST_mult_s);
    INST_randomVal1_init.dump_VCD(dt, backing.INST_randomVal1_init);
    INST_randomVal2_init.dump_VCD(dt, backing.INST_randomVal2_init);
  }
}
