/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sun Feb  2 14:48:50 IST 2014
 * 
 */

/* Generation options: */
#ifndef __mkDefaultTb_h__
#define __mkDefaultTb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

namespace bluesim
{
  
  /* Class declaration for the mkDefaultTb module */
  class MOD_mkDefaultTb : public Module {
   
   /* Clock handles */
   private:
    tClock __clk_handle_0;
   
   /* Instantiation parameters */
   public:
   
   /* Module state */
   public:
    MOD_Reg<tUInt32> INST_deqCount;
    MOD_Reg<tUInt32> INST_enqCount;
    MOD_Reg<tUInt32> INST_f_data;
    MOD_Reg<tUInt32> INST_f_data_1;
    MOD_Reg<tUInt32> INST_f_data_2;
    MOD_Reg<tUInt32> INST_f_data_3;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy;
    MOD_Reg<tUInt8> INST_f_deqEn_dummy2;
    MOD_Reg<tUInt8> INST_f_deqEn_dummy2_1;
    MOD_Reg<tUInt8> INST_f_deqEn_dummy2_2;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_1;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_2;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_3;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_4;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_5;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_6;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_7;
    MOD_Wire<tUInt8> INST_f_deqEn_dummy_8;
    MOD_Wire<tUInt8> INST_f_deqEn_lat;
    MOD_Wire<tUInt8> INST_f_deqEn_lat_1;
    MOD_Wire<tUInt8> INST_f_deqEn_lat_2;
    MOD_Reg<tUInt8> INST_f_deqEn_rl;
    MOD_Wire<tUInt8> INST_f_deqP_dummy;
    MOD_Reg<tUInt8> INST_f_deqP_dummy2;
    MOD_Reg<tUInt8> INST_f_deqP_dummy2_1;
    MOD_Reg<tUInt8> INST_f_deqP_dummy2_2;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_1;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_2;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_3;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_4;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_5;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_6;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_7;
    MOD_Wire<tUInt8> INST_f_deqP_dummy_8;
    MOD_Wire<tUInt8> INST_f_deqP_lat;
    MOD_Wire<tUInt8> INST_f_deqP_lat_1;
    MOD_Wire<tUInt8> INST_f_deqP_lat_2;
    MOD_Reg<tUInt8> INST_f_deqP_rl;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy;
    MOD_Reg<tUInt8> INST_f_enqEn_dummy2;
    MOD_Reg<tUInt8> INST_f_enqEn_dummy2_1;
    MOD_Reg<tUInt8> INST_f_enqEn_dummy2_2;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_1;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_2;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_3;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_4;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_5;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_6;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_7;
    MOD_Wire<tUInt8> INST_f_enqEn_dummy_8;
    MOD_Wire<tUInt8> INST_f_enqEn_lat;
    MOD_Wire<tUInt8> INST_f_enqEn_lat_1;
    MOD_Wire<tUInt8> INST_f_enqEn_lat_2;
    MOD_Reg<tUInt8> INST_f_enqEn_rl;
    MOD_Wire<tUInt8> INST_f_enqP_dummy;
    MOD_Reg<tUInt8> INST_f_enqP_dummy2;
    MOD_Reg<tUInt8> INST_f_enqP_dummy2_1;
    MOD_Reg<tUInt8> INST_f_enqP_dummy2_2;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_1;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_2;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_3;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_4;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_5;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_6;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_7;
    MOD_Wire<tUInt8> INST_f_enqP_dummy_8;
    MOD_Wire<tUInt8> INST_f_enqP_lat;
    MOD_Wire<tUInt8> INST_f_enqP_lat_1;
    MOD_Wire<tUInt8> INST_f_enqP_lat_2;
    MOD_Reg<tUInt8> INST_f_enqP_rl;
    MOD_Wire<tUInt64> INST_f_tempData_dummy;
    MOD_Reg<tUInt8> INST_f_tempData_dummy2;
    MOD_Reg<tUInt8> INST_f_tempData_dummy2_1;
    MOD_Wire<tUInt64> INST_f_tempData_dummy_1;
    MOD_Wire<tUInt64> INST_f_tempData_dummy_2;
    MOD_Wire<tUInt64> INST_f_tempData_dummy_3;
    MOD_Wire<tUInt32> INST_f_tempData_lat;
    MOD_Wire<tUInt32> INST_f_tempData_lat_1;
    MOD_Reg<tUInt32> INST_f_tempData_rl;
    MOD_Wire<tUInt8> INST_f_tempEnqP_dummy;
    MOD_Reg<tUInt8> INST_f_tempEnqP_dummy2;
    MOD_Reg<tUInt8> INST_f_tempEnqP_dummy2_1;
    MOD_Wire<tUInt8> INST_f_tempEnqP_dummy_1;
    MOD_Wire<tUInt8> INST_f_tempEnqP_dummy_2;
    MOD_Wire<tUInt8> INST_f_tempEnqP_dummy_3;
    MOD_Wire<tUInt8> INST_f_tempEnqP_lat;
    MOD_Wire<tUInt8> INST_f_tempEnqP_lat_1;
    MOD_Reg<tUInt8> INST_f_tempEnqP_rl;
    MOD_Reg<tUInt32> INST_mult_a;
    MOD_Reg<tUInt32> INST_mult_b;
    MOD_Reg<tUInt8> INST_mult_i;
    MOD_Reg<tUInt32> INST_mult_prod;
    MOD_Reg<tUInt32> INST_mult_tp;
    MOD_Reg<tUInt8> INST_randomVal1_init;
    MOD_Reg<tUInt8> INST_randomVal2_init;
   
   /* Constructor */
   public:
    MOD_mkDefaultTb(char const *name, Module *parent);
   
   /* Symbol init methods */
   private:
    void init_symbols_0();
   
   /* Reset signal definitions */
   private:
    tUInt8 PORT_RST_N;
   
   /* Port definitions */
   public:
   
   /* Publicly accessible definitions */
   public:
    tUInt8 DEF_f_deqEn_dummy2_2__h15467;
    tUInt8 DEF_f_enqEn_dummy2_2__h13964;
    tUInt32 DEF_x__h19458;
    tUInt32 DEF_x__h18635;
    tUInt8 DEF__read__h234;
    tUInt8 DEF_f_deqEn_rl__h11396;
    tUInt8 DEF_f_enqEn_rl__h9795;
   
   /* Local definitions */
   private:
    tUInt8 DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d387;
    tUInt8 DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d385;
    tUInt8 DEF_f_deqEn_lat_1_whas____d369;
    tUInt8 DEF_f_enqEn_lat_1_whas____d367;
    tUInt32 DEF_TASK_getRandom___d283;
    tUInt32 DEF_TASK_getRandom___d281;
    tUInt32 DEF_ab__h12499;
    tUInt32 DEF_ab__h12495;
    tUInt32 DEF_mult_tp__h3526;
    tUInt32 DEF__read__h147;
    tUInt8 DEF_f_tempEnqP_rl___d375;
    tUInt8 DEF_f_tempEnqP_lat_wget____d364;
    tUInt8 DEF_upd__h18858;
    tUInt8 DEF_upd__h14587;
    tUInt8 DEF_upd__h14620;
    tUInt8 DEF_upd__h18206;
    tUInt8 DEF_upd__h14307;
    tUInt8 DEF_upd__h14340;
    tUInt8 DEF_f_tempEnqP_lat_whas____d370;
    tUInt8 DEF_f_deqEn_lat_1_wget____d362;
    tUInt8 DEF_f_deqEn_lat_whas____d368;
    tUInt8 DEF_f_deqEn_lat_wget____d361;
    tUInt8 DEF_f_enqEn_lat_1_wget____d360;
    tUInt8 DEF_f_enqEn_lat_whas____d366;
    tUInt8 DEF_f_enqEn_lat_wget____d359;
    tUInt8 DEF_f_deqP_dummy2_2__h14548;
    tUInt8 DEF_f_enqP_dummy2_2__h14268;
    tUInt8 DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d358;
    tUInt8 DEF_f_tempEnqP_rl_91_BIT_4___d374;
    tUInt8 DEF_f_tempEnqP_lat_wget__89_BIT_4___d373;
    tUInt32 DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d386;
    tUInt8 DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d356;
    tUInt8 DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d354;
    tUInt8 DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d352;
   
   /* Rules */
   public:
    void RL_mult_mulStep();
    void RL_randomVal1_initialize();
    void RL_randomVal2_initialize();
    void RL_f_enqP_canon();
    void RL_f_deqP_canon();
    void RL_f_enqEn_canon();
    void RL_f_deqEn_canon();
    void RL_f_tempData_canon();
    void RL_f_tempEnqP_canon();
    void RL_f_canonicalize();
    void RL_enq();
    void RL_deq();
    void RL_fin();
   
   /* Methods */
   public:
   
   /* Reset routines */
   public:
    void reset_RST_N(tUInt8 ARG_rst_in);
   
   /* Static handles to reset routines */
   public:
   
   /* Pointers to reset fns in parent module for asserting output resets */
   private:
   
   /* Functions for the parent module to register its reset fns */
   public:
   
   /* Functions to set the elaborated clock id */
   public:
    void set_clk_0(char const *s);
   
   /* State dumping routine */
   public:
    void dump_state(unsigned int indent);
   
   /* VCD dumping routines */
   public:
    unsigned int dump_VCD_defs(unsigned int levels);
    void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDefaultTb &backing);
    void vcd_defs(tVCDDumpType dt, MOD_mkDefaultTb &backing);
    void vcd_prims(tVCDDumpType dt, MOD_mkDefaultTb &backing);
  };
}

#endif /* ifndef __mkDefaultTb_h__ */
