/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sun Feb  2 17:07:46 IST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "mkSignedTb.h"
#include "imported_BDPI_functions.h"

namespace bluesim
{
  
  /* String declarations */
  static std::string const __str_literal_2(" ", 1u);
  static std::string const __str_literal_4("%0d * %0d = %0d", 15u);
  static std::string const __str_literal_3("%s%0d * %s%0d = %s%0d, but you returned %s%0d", 45u);
  static std::string const __str_literal_1("-", 1u);
  static std::string const __str_literal_5("PASSED", 6u);
  
  
  /* Constructor */
  MOD_mkSignedTb::MOD_mkSignedTb(char const *name, Module *parent)
    : Module(name, parent),
      __clk_handle_0(BAD_CLOCK_HANDLE),
      INST_deqCount("deqCount", this, 16u, 0u, (tUInt8)0u),
      INST_enqCount("enqCount", this, 16u, 0u, (tUInt8)0u),
      INST_f_data("f_data", this, 32u),
      INST_f_data_1("f_data_1", this, 32u),
      INST_f_data_2("f_data_2", this, 32u),
      INST_f_data_3("f_data_3", this, 32u),
      INST_f_deqEn_dummy("f_deqEn_dummy", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy2("f_deqEn_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqEn_dummy2_1("f_deqEn_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqEn_dummy2_2("f_deqEn_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqEn_dummy_1("f_deqEn_dummy_1", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_2("f_deqEn_dummy_2", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_3("f_deqEn_dummy_3", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_4("f_deqEn_dummy_4", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_5("f_deqEn_dummy_5", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_6("f_deqEn_dummy_6", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_7("f_deqEn_dummy_7", this, 2u, (tUInt8)0u),
      INST_f_deqEn_dummy_8("f_deqEn_dummy_8", this, 2u, (tUInt8)0u),
      INST_f_deqEn_lat("f_deqEn_lat", this, 1u, (tUInt8)0u),
      INST_f_deqEn_lat_1("f_deqEn_lat_1", this, 1u, (tUInt8)0u),
      INST_f_deqEn_lat_2("f_deqEn_lat_2", this, 1u, (tUInt8)0u),
      INST_f_deqEn_rl("f_deqEn_rl", this, 1u, (tUInt8)0u, (tUInt8)0u),
      INST_f_deqP_dummy("f_deqP_dummy", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy2("f_deqP_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqP_dummy2_1("f_deqP_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqP_dummy2_2("f_deqP_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_deqP_dummy_1("f_deqP_dummy_1", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_2("f_deqP_dummy_2", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_3("f_deqP_dummy_3", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_4("f_deqP_dummy_4", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_5("f_deqP_dummy_5", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_6("f_deqP_dummy_6", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_7("f_deqP_dummy_7", this, 5u, (tUInt8)0u),
      INST_f_deqP_dummy_8("f_deqP_dummy_8", this, 5u, (tUInt8)0u),
      INST_f_deqP_lat("f_deqP_lat", this, 4u, (tUInt8)0u),
      INST_f_deqP_lat_1("f_deqP_lat_1", this, 4u, (tUInt8)0u),
      INST_f_deqP_lat_2("f_deqP_lat_2", this, 4u, (tUInt8)0u),
      INST_f_deqP_rl("f_deqP_rl", this, 4u, (tUInt8)0u, (tUInt8)0u),
      INST_f_enqEn_dummy("f_enqEn_dummy", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy2("f_enqEn_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqEn_dummy2_1("f_enqEn_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqEn_dummy2_2("f_enqEn_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqEn_dummy_1("f_enqEn_dummy_1", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_2("f_enqEn_dummy_2", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_3("f_enqEn_dummy_3", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_4("f_enqEn_dummy_4", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_5("f_enqEn_dummy_5", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_6("f_enqEn_dummy_6", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_7("f_enqEn_dummy_7", this, 2u, (tUInt8)0u),
      INST_f_enqEn_dummy_8("f_enqEn_dummy_8", this, 2u, (tUInt8)0u),
      INST_f_enqEn_lat("f_enqEn_lat", this, 1u, (tUInt8)0u),
      INST_f_enqEn_lat_1("f_enqEn_lat_1", this, 1u, (tUInt8)0u),
      INST_f_enqEn_lat_2("f_enqEn_lat_2", this, 1u, (tUInt8)0u),
      INST_f_enqEn_rl("f_enqEn_rl", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy("f_enqP_dummy", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy2("f_enqP_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy2_1("f_enqP_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy2_2("f_enqP_dummy2_2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_enqP_dummy_1("f_enqP_dummy_1", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_2("f_enqP_dummy_2", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_3("f_enqP_dummy_3", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_4("f_enqP_dummy_4", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_5("f_enqP_dummy_5", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_6("f_enqP_dummy_6", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_7("f_enqP_dummy_7", this, 5u, (tUInt8)0u),
      INST_f_enqP_dummy_8("f_enqP_dummy_8", this, 5u, (tUInt8)0u),
      INST_f_enqP_lat("f_enqP_lat", this, 4u, (tUInt8)0u),
      INST_f_enqP_lat_1("f_enqP_lat_1", this, 4u, (tUInt8)0u),
      INST_f_enqP_lat_2("f_enqP_lat_2", this, 4u, (tUInt8)0u),
      INST_f_enqP_rl("f_enqP_rl", this, 4u, (tUInt8)0u, (tUInt8)0u),
      INST_f_tempData_dummy("f_tempData_dummy", this, 33u, (tUInt8)0u),
      INST_f_tempData_dummy2("f_tempData_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempData_dummy2_1("f_tempData_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempData_dummy_1("f_tempData_dummy_1", this, 33u, (tUInt8)0u),
      INST_f_tempData_dummy_2("f_tempData_dummy_2", this, 33u, (tUInt8)0u),
      INST_f_tempData_dummy_3("f_tempData_dummy_3", this, 33u, (tUInt8)0u),
      INST_f_tempData_lat("f_tempData_lat", this, 32u, (tUInt8)0u),
      INST_f_tempData_lat_1("f_tempData_lat_1", this, 32u, (tUInt8)0u),
      INST_f_tempData_rl("f_tempData_rl", this, 32u, 2863311530u, (tUInt8)0u),
      INST_f_tempEnqP_dummy("f_tempEnqP_dummy", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_dummy2("f_tempEnqP_dummy2", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempEnqP_dummy2_1("f_tempEnqP_dummy2_1", this, 1u, (tUInt8)1u, (tUInt8)0u),
      INST_f_tempEnqP_dummy_1("f_tempEnqP_dummy_1", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_dummy_2("f_tempEnqP_dummy_2", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_dummy_3("f_tempEnqP_dummy_3", this, 6u, (tUInt8)0u),
      INST_f_tempEnqP_lat("f_tempEnqP_lat", this, 5u, (tUInt8)0u),
      INST_f_tempEnqP_lat_1("f_tempEnqP_lat_1", this, 5u, (tUInt8)0u),
      INST_f_tempEnqP_rl("f_tempEnqP_rl", this, 5u, (tUInt8)31u & (tUInt8)10u, (tUInt8)0u),
      INST_mult_a("mult_a", this, 16u),
      INST_mult_asign("mult_asign", this, 1u),
      INST_mult_b("mult_b", this, 16u),
      INST_mult_bsign("mult_bsign", this, 1u),
      INST_mult_i("mult_i", this, 16u, 1u, (tUInt8)0u),
      INST_mult_mul_a("mult_mul_a", this, 16u),
      INST_mult_mul_b("mult_mul_b", this, 16u),
      INST_mult_mul_i("mult_mul_i", this, 5u, (tUInt8)16u, (tUInt8)0u),
      INST_mult_mul_prod("mult_mul_prod", this, 16u),
      INST_mult_mul_tp("mult_mul_tp", this, 16u),
      INST_mult_res("mult_res", this, 32u),
      INST_randomVal1_init("randomVal1_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      INST_randomVal2_init("randomVal2_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      PORT_RST_N((tUInt8)1u),
      DEF_TASK_getRandom___d409(2863311530u),
      DEF_TASK_getRandom___d408(2863311530u)
  {
    symbol_count = 121u;
    symbols = new tSym[symbol_count];
    init_symbols_0();
  }
  
  
  /* Symbol init fns */
  
  void MOD_mkSignedTb::init_symbols_0()
  {
    init_symbol(&symbols[0u], "_read__h241", SYM_DEF, &DEF__read__h241, 5u);
    init_symbol(&symbols[1u], "deqCount", SYM_MODULE, &INST_deqCount);
    init_symbol(&symbols[2u], "enqCount", SYM_MODULE, &INST_enqCount);
    init_symbol(&symbols[3u], "f_data", SYM_MODULE, &INST_f_data);
    init_symbol(&symbols[4u], "f_data_1", SYM_MODULE, &INST_f_data_1);
    init_symbol(&symbols[5u], "f_data_2", SYM_MODULE, &INST_f_data_2);
    init_symbol(&symbols[6u], "f_data_3", SYM_MODULE, &INST_f_data_3);
    init_symbol(&symbols[7u], "f_deqEn_dummy", SYM_MODULE, &INST_f_deqEn_dummy);
    init_symbol(&symbols[8u], "f_deqEn_dummy2", SYM_MODULE, &INST_f_deqEn_dummy2);
    init_symbol(&symbols[9u], "f_deqEn_dummy2_1", SYM_MODULE, &INST_f_deqEn_dummy2_1);
    init_symbol(&symbols[10u], "f_deqEn_dummy2_2", SYM_MODULE, &INST_f_deqEn_dummy2_2);
    init_symbol(&symbols[11u], "f_deqEn_dummy2_2__h15721", SYM_DEF, &DEF_f_deqEn_dummy2_2__h15721, 1u);
    init_symbol(&symbols[12u], "f_deqEn_dummy_1", SYM_MODULE, &INST_f_deqEn_dummy_1);
    init_symbol(&symbols[13u], "f_deqEn_dummy_2", SYM_MODULE, &INST_f_deqEn_dummy_2);
    init_symbol(&symbols[14u], "f_deqEn_dummy_3", SYM_MODULE, &INST_f_deqEn_dummy_3);
    init_symbol(&symbols[15u], "f_deqEn_dummy_4", SYM_MODULE, &INST_f_deqEn_dummy_4);
    init_symbol(&symbols[16u], "f_deqEn_dummy_5", SYM_MODULE, &INST_f_deqEn_dummy_5);
    init_symbol(&symbols[17u], "f_deqEn_dummy_6", SYM_MODULE, &INST_f_deqEn_dummy_6);
    init_symbol(&symbols[18u], "f_deqEn_dummy_7", SYM_MODULE, &INST_f_deqEn_dummy_7);
    init_symbol(&symbols[19u], "f_deqEn_dummy_8", SYM_MODULE, &INST_f_deqEn_dummy_8);
    init_symbol(&symbols[20u], "f_deqEn_lat", SYM_MODULE, &INST_f_deqEn_lat);
    init_symbol(&symbols[21u], "f_deqEn_lat_1", SYM_MODULE, &INST_f_deqEn_lat_1);
    init_symbol(&symbols[22u], "f_deqEn_lat_2", SYM_MODULE, &INST_f_deqEn_lat_2);
    init_symbol(&symbols[23u], "f_deqEn_rl", SYM_MODULE, &INST_f_deqEn_rl);
    init_symbol(&symbols[24u], "f_deqEn_rl__h11650", SYM_DEF, &DEF_f_deqEn_rl__h11650, 1u);
    init_symbol(&symbols[25u], "f_deqP_dummy", SYM_MODULE, &INST_f_deqP_dummy);
    init_symbol(&symbols[26u], "f_deqP_dummy2", SYM_MODULE, &INST_f_deqP_dummy2);
    init_symbol(&symbols[27u], "f_deqP_dummy2_1", SYM_MODULE, &INST_f_deqP_dummy2_1);
    init_symbol(&symbols[28u], "f_deqP_dummy2_2", SYM_MODULE, &INST_f_deqP_dummy2_2);
    init_symbol(&symbols[29u], "f_deqP_dummy_1", SYM_MODULE, &INST_f_deqP_dummy_1);
    init_symbol(&symbols[30u], "f_deqP_dummy_2", SYM_MODULE, &INST_f_deqP_dummy_2);
    init_symbol(&symbols[31u], "f_deqP_dummy_3", SYM_MODULE, &INST_f_deqP_dummy_3);
    init_symbol(&symbols[32u], "f_deqP_dummy_4", SYM_MODULE, &INST_f_deqP_dummy_4);
    init_symbol(&symbols[33u], "f_deqP_dummy_5", SYM_MODULE, &INST_f_deqP_dummy_5);
    init_symbol(&symbols[34u], "f_deqP_dummy_6", SYM_MODULE, &INST_f_deqP_dummy_6);
    init_symbol(&symbols[35u], "f_deqP_dummy_7", SYM_MODULE, &INST_f_deqP_dummy_7);
    init_symbol(&symbols[36u], "f_deqP_dummy_8", SYM_MODULE, &INST_f_deqP_dummy_8);
    init_symbol(&symbols[37u], "f_deqP_lat", SYM_MODULE, &INST_f_deqP_lat);
    init_symbol(&symbols[38u], "f_deqP_lat_1", SYM_MODULE, &INST_f_deqP_lat_1);
    init_symbol(&symbols[39u], "f_deqP_lat_2", SYM_MODULE, &INST_f_deqP_lat_2);
    init_symbol(&symbols[40u], "f_deqP_rl", SYM_MODULE, &INST_f_deqP_rl);
    init_symbol(&symbols[41u], "f_enqEn_dummy", SYM_MODULE, &INST_f_enqEn_dummy);
    init_symbol(&symbols[42u], "f_enqEn_dummy2", SYM_MODULE, &INST_f_enqEn_dummy2);
    init_symbol(&symbols[43u], "f_enqEn_dummy2_1", SYM_MODULE, &INST_f_enqEn_dummy2_1);
    init_symbol(&symbols[44u], "f_enqEn_dummy2_2", SYM_MODULE, &INST_f_enqEn_dummy2_2);
    init_symbol(&symbols[45u], "f_enqEn_dummy2_2__h14218", SYM_DEF, &DEF_f_enqEn_dummy2_2__h14218, 1u);
    init_symbol(&symbols[46u], "f_enqEn_dummy_1", SYM_MODULE, &INST_f_enqEn_dummy_1);
    init_symbol(&symbols[47u], "f_enqEn_dummy_2", SYM_MODULE, &INST_f_enqEn_dummy_2);
    init_symbol(&symbols[48u], "f_enqEn_dummy_3", SYM_MODULE, &INST_f_enqEn_dummy_3);
    init_symbol(&symbols[49u], "f_enqEn_dummy_4", SYM_MODULE, &INST_f_enqEn_dummy_4);
    init_symbol(&symbols[50u], "f_enqEn_dummy_5", SYM_MODULE, &INST_f_enqEn_dummy_5);
    init_symbol(&symbols[51u], "f_enqEn_dummy_6", SYM_MODULE, &INST_f_enqEn_dummy_6);
    init_symbol(&symbols[52u], "f_enqEn_dummy_7", SYM_MODULE, &INST_f_enqEn_dummy_7);
    init_symbol(&symbols[53u], "f_enqEn_dummy_8", SYM_MODULE, &INST_f_enqEn_dummy_8);
    init_symbol(&symbols[54u], "f_enqEn_lat", SYM_MODULE, &INST_f_enqEn_lat);
    init_symbol(&symbols[55u], "f_enqEn_lat_1", SYM_MODULE, &INST_f_enqEn_lat_1);
    init_symbol(&symbols[56u], "f_enqEn_lat_2", SYM_MODULE, &INST_f_enqEn_lat_2);
    init_symbol(&symbols[57u], "f_enqEn_rl", SYM_MODULE, &INST_f_enqEn_rl);
    init_symbol(&symbols[58u], "f_enqEn_rl__h10049", SYM_DEF, &DEF_f_enqEn_rl__h10049, 1u);
    init_symbol(&symbols[59u], "f_enqP_dummy", SYM_MODULE, &INST_f_enqP_dummy);
    init_symbol(&symbols[60u], "f_enqP_dummy2", SYM_MODULE, &INST_f_enqP_dummy2);
    init_symbol(&symbols[61u], "f_enqP_dummy2_1", SYM_MODULE, &INST_f_enqP_dummy2_1);
    init_symbol(&symbols[62u], "f_enqP_dummy2_2", SYM_MODULE, &INST_f_enqP_dummy2_2);
    init_symbol(&symbols[63u], "f_enqP_dummy_1", SYM_MODULE, &INST_f_enqP_dummy_1);
    init_symbol(&symbols[64u], "f_enqP_dummy_2", SYM_MODULE, &INST_f_enqP_dummy_2);
    init_symbol(&symbols[65u], "f_enqP_dummy_3", SYM_MODULE, &INST_f_enqP_dummy_3);
    init_symbol(&symbols[66u], "f_enqP_dummy_4", SYM_MODULE, &INST_f_enqP_dummy_4);
    init_symbol(&symbols[67u], "f_enqP_dummy_5", SYM_MODULE, &INST_f_enqP_dummy_5);
    init_symbol(&symbols[68u], "f_enqP_dummy_6", SYM_MODULE, &INST_f_enqP_dummy_6);
    init_symbol(&symbols[69u], "f_enqP_dummy_7", SYM_MODULE, &INST_f_enqP_dummy_7);
    init_symbol(&symbols[70u], "f_enqP_dummy_8", SYM_MODULE, &INST_f_enqP_dummy_8);
    init_symbol(&symbols[71u], "f_enqP_lat", SYM_MODULE, &INST_f_enqP_lat);
    init_symbol(&symbols[72u], "f_enqP_lat_1", SYM_MODULE, &INST_f_enqP_lat_1);
    init_symbol(&symbols[73u], "f_enqP_lat_2", SYM_MODULE, &INST_f_enqP_lat_2);
    init_symbol(&symbols[74u], "f_enqP_rl", SYM_MODULE, &INST_f_enqP_rl);
    init_symbol(&symbols[75u], "f_tempData_dummy", SYM_MODULE, &INST_f_tempData_dummy);
    init_symbol(&symbols[76u], "f_tempData_dummy2", SYM_MODULE, &INST_f_tempData_dummy2);
    init_symbol(&symbols[77u], "f_tempData_dummy2_1", SYM_MODULE, &INST_f_tempData_dummy2_1);
    init_symbol(&symbols[78u], "f_tempData_dummy_1", SYM_MODULE, &INST_f_tempData_dummy_1);
    init_symbol(&symbols[79u], "f_tempData_dummy_2", SYM_MODULE, &INST_f_tempData_dummy_2);
    init_symbol(&symbols[80u], "f_tempData_dummy_3", SYM_MODULE, &INST_f_tempData_dummy_3);
    init_symbol(&symbols[81u], "f_tempData_lat", SYM_MODULE, &INST_f_tempData_lat);
    init_symbol(&symbols[82u], "f_tempData_lat_1", SYM_MODULE, &INST_f_tempData_lat_1);
    init_symbol(&symbols[83u], "f_tempData_rl", SYM_MODULE, &INST_f_tempData_rl);
    init_symbol(&symbols[84u], "f_tempEnqP_dummy", SYM_MODULE, &INST_f_tempEnqP_dummy);
    init_symbol(&symbols[85u], "f_tempEnqP_dummy2", SYM_MODULE, &INST_f_tempEnqP_dummy2);
    init_symbol(&symbols[86u], "f_tempEnqP_dummy2_1", SYM_MODULE, &INST_f_tempEnqP_dummy2_1);
    init_symbol(&symbols[87u], "f_tempEnqP_dummy_1", SYM_MODULE, &INST_f_tempEnqP_dummy_1);
    init_symbol(&symbols[88u], "f_tempEnqP_dummy_2", SYM_MODULE, &INST_f_tempEnqP_dummy_2);
    init_symbol(&symbols[89u], "f_tempEnqP_dummy_3", SYM_MODULE, &INST_f_tempEnqP_dummy_3);
    init_symbol(&symbols[90u], "f_tempEnqP_lat", SYM_MODULE, &INST_f_tempEnqP_lat);
    init_symbol(&symbols[91u], "f_tempEnqP_lat_1", SYM_MODULE, &INST_f_tempEnqP_lat_1);
    init_symbol(&symbols[92u], "f_tempEnqP_rl", SYM_MODULE, &INST_f_tempEnqP_rl);
    init_symbol(&symbols[93u], "mult_a", SYM_MODULE, &INST_mult_a);
    init_symbol(&symbols[94u], "mult_asign", SYM_MODULE, &INST_mult_asign);
    init_symbol(&symbols[95u], "mult_b", SYM_MODULE, &INST_mult_b);
    init_symbol(&symbols[96u], "mult_bsign", SYM_MODULE, &INST_mult_bsign);
    init_symbol(&symbols[97u], "mult_i", SYM_MODULE, &INST_mult_i);
    init_symbol(&symbols[98u], "mult_mul_a", SYM_MODULE, &INST_mult_mul_a);
    init_symbol(&symbols[99u], "mult_mul_b", SYM_MODULE, &INST_mult_mul_b);
    init_symbol(&symbols[100u], "mult_mul_i", SYM_MODULE, &INST_mult_mul_i);
    init_symbol(&symbols[101u], "mult_mul_prod", SYM_MODULE, &INST_mult_mul_prod);
    init_symbol(&symbols[102u], "mult_mul_tp", SYM_MODULE, &INST_mult_mul_tp);
    init_symbol(&symbols[103u], "mult_res", SYM_MODULE, &INST_mult_res);
    init_symbol(&symbols[104u], "RL_deq", SYM_RULE);
    init_symbol(&symbols[105u], "RL_enq", SYM_RULE);
    init_symbol(&symbols[106u], "RL_f_canonicalize", SYM_RULE);
    init_symbol(&symbols[107u], "RL_f_deqEn_canon", SYM_RULE);
    init_symbol(&symbols[108u], "RL_f_deqP_canon", SYM_RULE);
    init_symbol(&symbols[109u], "RL_f_enqEn_canon", SYM_RULE);
    init_symbol(&symbols[110u], "RL_f_enqP_canon", SYM_RULE);
    init_symbol(&symbols[111u], "RL_f_tempData_canon", SYM_RULE);
    init_symbol(&symbols[112u], "RL_f_tempEnqP_canon", SYM_RULE);
    init_symbol(&symbols[113u], "RL_fin", SYM_RULE);
    init_symbol(&symbols[114u], "RL_mult_mul_mulStep", SYM_RULE);
    init_symbol(&symbols[115u], "RL_randomVal1_initialize", SYM_RULE);
    init_symbol(&symbols[116u], "RL_randomVal2_initialize", SYM_RULE);
    init_symbol(&symbols[117u], "randomVal1_init", SYM_MODULE, &INST_randomVal1_init);
    init_symbol(&symbols[118u], "randomVal2_init", SYM_MODULE, &INST_randomVal2_init);
    init_symbol(&symbols[119u], "x__h19728", SYM_DEF, &DEF_x__h19728, 16u);
    init_symbol(&symbols[120u], "x__h20679", SYM_DEF, &DEF_x__h20679, 16u);
  }
  
  
  /* Rule actions */
  
  void MOD_mkSignedTb::RL_mult_mul_mulStep()
  {
    tUInt32 DEF_x__h4344;
    tUInt32 DEF_x__h278;
    tUInt32 DEF_x__h4373;
    tUInt8 DEF_x__h4399;
    tUInt8 DEF_y__h1054;
    tUInt8 DEF_x__h1053;
    tUInt8 DEF_y__h1228;
    tUInt8 DEF_x__h1227;
    tUInt8 DEF_y__h1401;
    tUInt8 DEF_x__h1400;
    tUInt8 DEF_y__h1574;
    tUInt8 DEF_x__h1573;
    tUInt8 DEF_y__h1747;
    tUInt8 DEF_x__h1746;
    tUInt8 DEF_y__h1920;
    tUInt8 DEF_x__h1919;
    tUInt8 DEF_y__h2093;
    tUInt8 DEF_x__h2092;
    tUInt8 DEF_y__h2266;
    tUInt8 DEF_x__h2265;
    tUInt8 DEF_y__h2439;
    tUInt8 DEF_x__h2438;
    tUInt8 DEF_y__h2612;
    tUInt8 DEF_x__h2611;
    tUInt8 DEF_y__h2785;
    tUInt8 DEF_x__h2784;
    tUInt8 DEF_y__h2958;
    tUInt8 DEF_x__h2957;
    tUInt8 DEF_y__h3131;
    tUInt8 DEF_x__h3130;
    tUInt8 DEF_y__h3304;
    tUInt8 DEF_x__h3303;
    tUInt8 DEF_y__h3477;
    tUInt8 DEF_x__h3476;
    tUInt8 DEF_y__h1111;
    tUInt8 DEF_c_in__h1213;
    tUInt8 DEF_y__h1285;
    tUInt8 DEF_c_in__h1386;
    tUInt8 DEF_y__h1458;
    tUInt8 DEF_c_in__h1559;
    tUInt8 DEF_y__h1631;
    tUInt8 DEF_c_in__h1732;
    tUInt8 DEF_y__h1804;
    tUInt8 DEF_c_in__h1905;
    tUInt8 DEF_y__h1977;
    tUInt8 DEF_c_in__h2078;
    tUInt8 DEF_y__h2150;
    tUInt8 DEF_c_in__h2251;
    tUInt8 DEF_y__h2323;
    tUInt8 DEF_c_in__h2424;
    tUInt8 DEF_y__h2496;
    tUInt8 DEF_c_in__h2597;
    tUInt8 DEF_y__h2669;
    tUInt8 DEF_c_in__h2770;
    tUInt8 DEF_y__h2842;
    tUInt8 DEF_c_in__h2943;
    tUInt8 DEF_y__h3015;
    tUInt8 DEF_c_in__h3116;
    tUInt8 DEF_y__h3188;
    tUInt8 DEF_c_in__h3289;
    tUInt8 DEF_y__h3361;
    tUInt8 DEF_c_in__h3462;
    tUInt8 DEF_y__h3534;
    tUInt8 DEF_ba__h836;
    tUInt8 DEF_ba__h1037;
    tUInt8 DEF_ba__h1211;
    tUInt8 DEF_ba__h1384;
    tUInt8 DEF_ba__h1557;
    tUInt8 DEF_ba__h1730;
    tUInt8 DEF_ba__h1903;
    tUInt8 DEF_ba__h2076;
    tUInt8 DEF_ba__h2249;
    tUInt8 DEF_ba__h2422;
    tUInt8 DEF_ba__h2595;
    tUInt8 DEF_ba__h2768;
    tUInt8 DEF_ba__h2941;
    tUInt8 DEF_ba__h3114;
    tUInt8 DEF_ba__h3287;
    tUInt32 DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399;
    tUInt8 DEF_ba__h3460;
    tUInt8 DEF_bb__h837;
    tUInt8 DEF_bb__h1038;
    tUInt8 DEF_bb__h1212;
    tUInt8 DEF_bb__h1385;
    tUInt8 DEF_bb__h1558;
    tUInt8 DEF_bb__h1731;
    tUInt8 DEF_bb__h1904;
    tUInt8 DEF_bb__h2077;
    tUInt8 DEF_bb__h2250;
    tUInt8 DEF_bb__h2423;
    tUInt8 DEF_bb__h2596;
    tUInt8 DEF_bb__h2769;
    tUInt8 DEF_bb__h2942;
    tUInt8 DEF_bb__h3115;
    tUInt8 DEF_bb__h3288;
    tUInt8 DEF_bb__h3461;
    tUInt8 DEF_c_in__h1039;
    tUInt32 DEF_mult_mul_a_BITS_15_TO_1___h4394;
    tUInt32 DEF_mult_mul_prod_BITS_15_TO_1___h4329;
    tUInt32 DEF_mult_mul_a___d382;
    tUInt32 DEF__read__h114;
    DEF_mult_mul_tp__h3533 = INST_mult_mul_tp.METH_read();
    DEF__read__h154 = INST_mult_mul_prod.METH_read();
    DEF__read__h114 = INST_mult_mul_b.METH_read();
    DEF_mult_mul_a___d382 = INST_mult_mul_a.METH_read();
    DEF__read__h241 = INST_mult_mul_i.METH_read();
    DEF_mult_mul_prod_BITS_15_TO_1___h4329 = (tUInt32)(DEF__read__h154 >> 1u);
    DEF_mult_mul_a_BITS_15_TO_1___h4394 = (tUInt32)(DEF_mult_mul_a___d382 >> 1u);
    DEF_bb__h3461 = (tUInt8)(DEF_mult_mul_tp__h3533 >> 15u);
    DEF_bb__h3288 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 14u));
    DEF_bb__h3115 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 13u));
    DEF_bb__h2942 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 12u));
    DEF_bb__h2596 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 10u));
    DEF_bb__h2769 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 11u));
    DEF_bb__h2423 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 9u));
    DEF_bb__h2077 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 7u));
    DEF_bb__h2250 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 8u));
    DEF_bb__h1904 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 6u));
    DEF_bb__h1731 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 5u));
    DEF_bb__h1385 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 3u));
    DEF_bb__h1558 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 4u));
    DEF_bb__h1212 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 2u));
    DEF_bb__h1038 = (tUInt8)((tUInt8)1u & (DEF_mult_mul_tp__h3533 >> 1u));
    DEF_bb__h837 = (tUInt8)((tUInt8)1u & DEF_mult_mul_tp__h3533);
    DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 = (tUInt8)((tUInt8)1u & DEF_mult_mul_a___d382) ? DEF__read__h114 : 0u;
    DEF_ba__h3460 = (tUInt8)(DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 15u);
    DEF_ba__h3287 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 14u));
    DEF_ba__h3114 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 13u));
    DEF_ba__h2941 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 12u));
    DEF_ba__h2768 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 11u));
    DEF_ba__h2595 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 10u));
    DEF_ba__h2422 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 9u));
    DEF_ba__h2076 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 7u));
    DEF_ba__h2249 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 8u));
    DEF_ba__h1903 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 6u));
    DEF_ba__h1730 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 5u));
    DEF_ba__h1557 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 4u));
    DEF_ba__h1384 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 3u));
    DEF_ba__h1211 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 2u));
    DEF_ba__h836 = (tUInt8)((tUInt8)1u & DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399);
    DEF_c_in__h1039 = (tUInt8)((tUInt8)1u & ((DEF_ba__h836 & DEF_bb__h837 ? 2u : 0u) >> 1u));
    DEF_ba__h1037 = (tUInt8)((tUInt8)1u & (DEF_IF_mult_mul_a_BIT_0_THEN_mult_mul_b_ELSE_0___d399 >> 1u));
    DEF_y__h3534 = DEF_ba__h3460 ^ DEF_bb__h3461;
    DEF_y__h3361 = DEF_ba__h3287 ^ DEF_bb__h3288;
    DEF_y__h3188 = DEF_ba__h3114 ^ DEF_bb__h3115;
    DEF_y__h3015 = DEF_ba__h2941 ^ DEF_bb__h2942;
    DEF_y__h2842 = DEF_ba__h2768 ^ DEF_bb__h2769;
    DEF_y__h2669 = DEF_ba__h2595 ^ DEF_bb__h2596;
    DEF_y__h2496 = DEF_ba__h2422 ^ DEF_bb__h2423;
    DEF_y__h2323 = DEF_ba__h2249 ^ DEF_bb__h2250;
    DEF_y__h2150 = DEF_ba__h2076 ^ DEF_bb__h2077;
    DEF_y__h1804 = DEF_ba__h1730 ^ DEF_bb__h1731;
    DEF_y__h1977 = DEF_ba__h1903 ^ DEF_bb__h1904;
    DEF_y__h1631 = DEF_ba__h1557 ^ DEF_bb__h1558;
    DEF_y__h1458 = DEF_ba__h1384 ^ DEF_bb__h1385;
    DEF_y__h1285 = DEF_ba__h1211 ^ DEF_bb__h1212;
    DEF_y__h1111 = DEF_ba__h1037 ^ DEF_bb__h1038;
    DEF_x__h3476 = DEF_ba__h3460 & DEF_bb__h3461;
    DEF_x__h3303 = DEF_ba__h3287 & DEF_bb__h3288;
    DEF_x__h3130 = DEF_ba__h3114 & DEF_bb__h3115;
    DEF_x__h2957 = DEF_ba__h2941 & DEF_bb__h2942;
    DEF_x__h2784 = DEF_ba__h2768 & DEF_bb__h2769;
    DEF_x__h2611 = DEF_ba__h2595 & DEF_bb__h2596;
    DEF_x__h2438 = DEF_ba__h2422 & DEF_bb__h2423;
    DEF_x__h2265 = DEF_ba__h2249 & DEF_bb__h2250;
    DEF_x__h2092 = DEF_ba__h2076 & DEF_bb__h2077;
    DEF_x__h1919 = DEF_ba__h1903 & DEF_bb__h1904;
    DEF_x__h1746 = DEF_ba__h1730 & DEF_bb__h1731;
    DEF_x__h1573 = DEF_ba__h1557 & DEF_bb__h1558;
    DEF_x__h1400 = DEF_ba__h1384 & DEF_bb__h1385;
    DEF_x__h1227 = DEF_ba__h1211 & DEF_bb__h1212;
    DEF_x__h1053 = DEF_ba__h1037 & DEF_bb__h1038;
    DEF_y__h1054 = DEF_c_in__h1039 & DEF_y__h1111;
    DEF_c_in__h1213 = DEF_x__h1053 | DEF_y__h1054;
    DEF_y__h1228 = DEF_c_in__h1213 & DEF_y__h1285;
    DEF_c_in__h1386 = DEF_x__h1227 | DEF_y__h1228;
    DEF_y__h1401 = DEF_c_in__h1386 & DEF_y__h1458;
    DEF_c_in__h1559 = DEF_x__h1400 | DEF_y__h1401;
    DEF_y__h1574 = DEF_c_in__h1559 & DEF_y__h1631;
    DEF_c_in__h1732 = DEF_x__h1573 | DEF_y__h1574;
    DEF_y__h1747 = DEF_c_in__h1732 & DEF_y__h1804;
    DEF_c_in__h1905 = DEF_x__h1746 | DEF_y__h1747;
    DEF_y__h1920 = DEF_c_in__h1905 & DEF_y__h1977;
    DEF_c_in__h2078 = DEF_x__h1919 | DEF_y__h1920;
    DEF_y__h2093 = DEF_c_in__h2078 & DEF_y__h2150;
    DEF_c_in__h2251 = DEF_x__h2092 | DEF_y__h2093;
    DEF_y__h2266 = DEF_c_in__h2251 & DEF_y__h2323;
    DEF_c_in__h2424 = DEF_x__h2265 | DEF_y__h2266;
    DEF_y__h2439 = DEF_c_in__h2424 & DEF_y__h2496;
    DEF_c_in__h2597 = DEF_x__h2438 | DEF_y__h2439;
    DEF_y__h2612 = DEF_c_in__h2597 & DEF_y__h2669;
    DEF_c_in__h2770 = DEF_x__h2611 | DEF_y__h2612;
    DEF_y__h2785 = DEF_c_in__h2770 & DEF_y__h2842;
    DEF_c_in__h2943 = DEF_x__h2784 | DEF_y__h2785;
    DEF_y__h2958 = DEF_c_in__h2943 & DEF_y__h3015;
    DEF_c_in__h3116 = DEF_x__h2957 | DEF_y__h2958;
    DEF_y__h3131 = DEF_c_in__h3116 & DEF_y__h3188;
    DEF_c_in__h3289 = DEF_x__h3130 | DEF_y__h3131;
    DEF_y__h3304 = DEF_c_in__h3289 & DEF_y__h3361;
    DEF_c_in__h3462 = DEF_x__h3303 | DEF_y__h3304;
    DEF_y__h3477 = DEF_c_in__h3462 & DEF_y__h3534;
    DEF_x__h4399 = (tUInt8)31u & (DEF__read__h241 + (tUInt8)1u);
    DEF_x__h4373 = 65535u & ((((tUInt32)((tUInt8)0u)) << 15u) | DEF_mult_mul_a_BITS_15_TO_1___h4394);
    DEF_x__h278 = 65535u & ((((tUInt32)(DEF_ba__h836 ^ DEF_bb__h837)) << 15u) | DEF_mult_mul_prod_BITS_15_TO_1___h4329);
    DEF_x__h4344 = 65535u & ((((tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_x__h3476 | DEF_y__h3477) << 1u) | (DEF_y__h3534 ^ DEF_c_in__h3462))) << 2u) | ((tUInt8)3u & (((DEF_y__h3361 ^ DEF_c_in__h3289) << 1u) | (DEF_y__h3188 ^ DEF_c_in__h3116))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_y__h3015 ^ DEF_c_in__h2943) << 1u) | (DEF_y__h2842 ^ DEF_c_in__h2770))) << 2u) | ((tUInt8)3u & (((DEF_y__h2669 ^ DEF_c_in__h2597) << 1u) | (DEF_y__h2496 ^ DEF_c_in__h2424)))))))) << 8u) | (tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_y__h2323 ^ DEF_c_in__h2251) << 1u) | (DEF_y__h2150 ^ DEF_c_in__h2078))) << 2u) | ((tUInt8)3u & (((DEF_y__h1977 ^ DEF_c_in__h1905) << 1u) | (DEF_y__h1804 ^ DEF_c_in__h1732))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_y__h1631 ^ DEF_c_in__h1559) << 1u) | (DEF_y__h1458 ^ DEF_c_in__h1386))) << 2u) | ((tUInt8)3u & (((DEF_y__h1285 ^ DEF_c_in__h1213) << 1u) | (DEF_y__h1111 ^ DEF_c_in__h1039))))))));
    INST_mult_mul_prod.METH_write(DEF_x__h278);
    INST_mult_mul_tp.METH_write(DEF_x__h4344);
    INST_mult_mul_a.METH_write(DEF_x__h4373);
    INST_mult_mul_i.METH_write(DEF_x__h4399);
  }
  
  void MOD_mkSignedTb::RL_randomVal1_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3735928559u);
    INST_randomVal1_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkSignedTb::RL_randomVal2_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3405691582u);
    INST_randomVal2_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkSignedTb::RL_f_enqP_canon()
  {
    tUInt8 DEF_x__h6628;
    tUInt8 DEF_upd__h6780;
    DEF_upd__h19299 = INST_f_enqP_rl.METH_read();
    DEF_upd__h6780 = INST_f_enqP_lat_2.METH_wget();
    DEF_upd__h14561 = INST_f_enqP_lat_1.METH_wget();
    DEF_upd__h14594 = INST_f_enqP_lat.METH_wget();
    DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394 = INST_f_enqP_lat_1.METH_whas() ? DEF_upd__h14561 : (INST_f_enqP_lat.METH_whas() ? DEF_upd__h14594 : DEF_upd__h19299);
    DEF_x__h6628 = INST_f_enqP_lat_2.METH_whas() ? DEF_upd__h6780 : DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394;
    INST_f_enqP_rl.METH_write(DEF_x__h6628);
  }
  
  void MOD_mkSignedTb::RL_f_deqP_canon()
  {
    tUInt8 DEF_x__h8204;
    tUInt8 DEF_upd__h8356;
    DEF_upd__h19951 = INST_f_deqP_rl.METH_read();
    DEF_upd__h8356 = INST_f_deqP_lat_2.METH_wget();
    DEF_upd__h14841 = INST_f_deqP_lat_1.METH_wget();
    DEF_upd__h14874 = INST_f_deqP_lat.METH_wget();
    DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396 = INST_f_deqP_lat_1.METH_whas() ? DEF_upd__h14841 : (INST_f_deqP_lat.METH_whas() ? DEF_upd__h14874 : DEF_upd__h19951);
    DEF_x__h8204 = INST_f_deqP_lat_2.METH_whas() ? DEF_upd__h8356 : DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396;
    INST_f_deqP_rl.METH_write(DEF_x__h8204);
  }
  
  void MOD_mkSignedTb::RL_f_enqEn_canon()
  {
    tUInt8 DEF_IF_f_enqEn_lat_2_whas__58_THEN_f_enqEn_lat_2_w_ETC___d167;
    DEF_f_enqEn_lat_1_whas____d411 = INST_f_enqEn_lat_1.METH_whas();
    DEF_f_enqEn_rl__h10049 = INST_f_enqEn_rl.METH_read();
    DEF_f_enqEn_lat_1_wget____d402 = INST_f_enqEn_lat_1.METH_wget();
    DEF_f_enqEn_lat_whas____d410 = INST_f_enqEn_lat.METH_whas();
    DEF_f_enqEn_lat_wget____d401 = INST_f_enqEn_lat.METH_wget();
    DEF_IF_f_enqEn_lat_2_whas__58_THEN_f_enqEn_lat_2_w_ETC___d167 = INST_f_enqEn_lat_2.METH_whas() ? INST_f_enqEn_lat_2.METH_wget() : (DEF_f_enqEn_lat_1_whas____d411 ? DEF_f_enqEn_lat_1_wget____d402 : (DEF_f_enqEn_lat_whas____d410 ? DEF_f_enqEn_lat_wget____d401 : DEF_f_enqEn_rl__h10049));
    INST_f_enqEn_rl.METH_write(DEF_IF_f_enqEn_lat_2_whas__58_THEN_f_enqEn_lat_2_w_ETC___d167);
  }
  
  void MOD_mkSignedTb::RL_f_deqEn_canon()
  {
    tUInt8 DEF_IF_f_deqEn_lat_2_whas__68_THEN_f_deqEn_lat_2_w_ETC___d177;
    DEF_f_deqEn_lat_1_whas____d413 = INST_f_deqEn_lat_1.METH_whas();
    DEF_f_deqEn_rl__h11650 = INST_f_deqEn_rl.METH_read();
    DEF_f_deqEn_lat_1_wget____d404 = INST_f_deqEn_lat_1.METH_wget();
    DEF_f_deqEn_lat_whas____d412 = INST_f_deqEn_lat.METH_whas();
    DEF_f_deqEn_lat_wget____d403 = INST_f_deqEn_lat.METH_wget();
    DEF_IF_f_deqEn_lat_2_whas__68_THEN_f_deqEn_lat_2_w_ETC___d177 = INST_f_deqEn_lat_2.METH_whas() ? INST_f_deqEn_lat_2.METH_wget() : (DEF_f_deqEn_lat_1_whas____d413 ? DEF_f_deqEn_lat_1_wget____d404 : (DEF_f_deqEn_lat_whas____d412 ? DEF_f_deqEn_lat_wget____d403 : DEF_f_deqEn_rl__h11650));
    INST_f_deqEn_rl.METH_write(DEF_IF_f_deqEn_lat_2_whas__68_THEN_f_deqEn_lat_2_w_ETC___d177);
  }
  
  void MOD_mkSignedTb::RL_f_tempData_canon()
  {
    tUInt32 DEF_ab__h12707;
    tUInt32 DEF_IF_f_tempData_lat_1_whas__78_THEN_f_tempData_l_ETC___d184;
    DEF_ab__h12753 = INST_f_tempData_rl.METH_read();
    DEF_ab__h12707 = INST_f_tempData_lat_1.METH_wget();
    DEF_ab__h12749 = INST_f_tempData_lat.METH_wget();
    DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388 = INST_f_tempData_lat.METH_whas() ? DEF_ab__h12749 : DEF_ab__h12753;
    DEF_IF_f_tempData_lat_1_whas__78_THEN_f_tempData_l_ETC___d184 = INST_f_tempData_lat_1.METH_whas() ? DEF_ab__h12707 : DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388;
    INST_f_tempData_rl.METH_write(DEF_IF_f_tempData_lat_1_whas__78_THEN_f_tempData_l_ETC___d184);
  }
  
  void MOD_mkSignedTb::RL_f_tempEnqP_canon()
  {
    tUInt8 DEF_IF_f_tempEnqP_lat_1_whas__85_THEN_f_tempEnqP_l_ETC___d390;
    tUInt8 DEF_f_tempEnqP_lat_1_wget__86_BIT_4___d418;
    tUInt8 DEF_f_tempEnqP_lat_1_whas____d415;
    tUInt8 DEF_f_tempEnqP_lat_1_wget____d407;
    tUInt8 DEF_IF_f_tempEnqP_lat_1_whas__85_THEN_f_tempEnqP_l_ETC___d206;
    DEF_f_tempEnqP_rl___d423 = INST_f_tempEnqP_rl.METH_read();
    DEF_f_tempEnqP_lat_1_wget____d407 = INST_f_tempEnqP_lat_1.METH_wget();
    DEF_f_tempEnqP_lat_wget____d406 = INST_f_tempEnqP_lat.METH_wget();
    DEF_f_tempEnqP_lat_1_whas____d415 = INST_f_tempEnqP_lat_1.METH_whas();
    DEF_f_tempEnqP_lat_whas____d414 = INST_f_tempEnqP_lat.METH_whas();
    DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400 = (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_lat_wget____d406);
    DEF_f_tempEnqP_rl_91_BIT_4___d420 = (tUInt8)(DEF_f_tempEnqP_rl___d423 >> 4u);
    DEF_f_tempEnqP_lat_1_wget__86_BIT_4___d418 = (tUInt8)(DEF_f_tempEnqP_lat_1_wget____d407 >> 4u);
    DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 = (tUInt8)(DEF_f_tempEnqP_lat_wget____d406 >> 4u);
    DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389 = DEF_f_tempEnqP_lat_whas____d414 ? DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 : DEF_f_tempEnqP_rl_91_BIT_4___d420;
    DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384 = DEF_f_tempEnqP_lat_whas____d414 ? !DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 : !DEF_f_tempEnqP_rl_91_BIT_4___d420;
    DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398 = DEF_f_tempEnqP_lat_whas____d414 ? DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400 : (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_rl___d423);
    DEF_IF_f_tempEnqP_lat_1_whas__85_THEN_f_tempEnqP_l_ETC___d390 = DEF_f_tempEnqP_lat_1_whas____d415 ? (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_lat_1_wget____d407) : DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398;
    DEF_IF_f_tempEnqP_lat_1_whas__85_THEN_f_tempEnqP_l_ETC___d206 = (tUInt8)31u & (((DEF_f_tempEnqP_lat_1_whas____d415 ? DEF_f_tempEnqP_lat_1_wget__86_BIT_4___d418 : DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389) << 4u) | ((DEF_f_tempEnqP_lat_1_whas____d415 ? !DEF_f_tempEnqP_lat_1_wget__86_BIT_4___d418 : DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384) ? DEF_IF_f_tempEnqP_lat_1_whas__85_THEN_f_tempEnqP_l_ETC___d390 : DEF_IF_f_tempEnqP_lat_1_whas__85_THEN_f_tempEnqP_l_ETC___d390));
    INST_f_tempEnqP_rl.METH_write(DEF_IF_f_tempEnqP_lat_1_whas__85_THEN_f_tempEnqP_l_ETC___d206);
  }
  
  void MOD_mkSignedTb::RL_f_canonicalize()
  {
    tUInt8 DEF__0_CONCAT_DONTCARE___d405;
    tUInt8 DEF_x__h14945;
    tUInt8 DEF_y__h14944;
    tUInt8 DEF_x__h14943;
    tUInt8 DEF_IF_f_enqEn_lat_1_whas__60_THEN_NOT_f_enqEn_lat_ETC___d391;
    tUInt8 DEF_IF_f_deqEn_lat_1_whas__70_THEN_NOT_f_deqEn_lat_ETC___d393;
    tUInt8 DEF_IF_f_tempEnqP_lat_wget__89_BIT_4_90_THEN_f_tem_ETC___d431;
    tUInt8 DEF_cnt__h14016;
    tUInt8 DEF_IF_f_tempEnqP_dummy2_1_48_THEN_IF_f_tempEnqP_l_ETC___d387;
    tUInt32 DEF_IF_f_tempData_dummy2_1_56_THEN_IF_f_tempData_l_ETC___d430;
    tUInt8 DEF_n__read__h14675;
    tUInt8 DEF_n__read__h14395;
    tUInt8 DEF_f_tempData_dummy2_1__h17068;
    tUInt8 DEF_x__h16617;
    tUInt8 DEF_f_tempEnqP_dummy2_1__h16526;
    tUInt8 DEF_f_enqEn_lat_1_whas__60_CONCAT_IF_f_enqEn_lat_1_ETC___d233;
    tUInt8 DEF_f_enqEn_lat_whas__62_CONCAT_IF_f_enqEn_lat_wha_ETC___d231;
    tUInt8 DEF_f_deqEn_lat_whas__72_CONCAT_IF_f_deqEn_lat_wha_ETC___d245;
    tUInt8 DEF_f_deqEn_lat_1_whas__70_CONCAT_IF_f_deqEn_lat_1_ETC___d247;
    tUInt8 DEF_f_tempEnqP_lat_whas__88_CONCAT_IF_f_tempEnqP_l_ETC___d269;
    tUInt8 DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d229;
    tUInt8 DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d243;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d259;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d255;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d261;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d263;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250;
    tUInt8 DEF_f_tempEnqP_dummy2_1_48_AND_IF_f_tempEnqP_lat_w_ETC___d251;
    tUInt8 DEF_NOT_f_tempEnqP_dummy2_1_48___d249;
    tUInt8 DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d213;
    tUInt8 DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d240;
    DEF_f_tempEnqP_dummy2_1__h16526 = INST_f_tempEnqP_dummy2_1.METH_read();
    DEF_NOT_f_tempEnqP_dummy2_1_48___d249 = !DEF_f_tempEnqP_dummy2_1__h16526;
    DEF_f_deqEn_dummy2_2__h15721 = INST_f_deqEn_dummy2_2.METH_read();
    DEF_f_enqEn_dummy2_2__h14218 = INST_f_enqEn_dummy2_2.METH_read();
    DEF_f_deqEn_lat_1_whas____d413 = INST_f_deqEn_lat_1.METH_whas();
    DEF_f_enqEn_lat_1_whas____d411 = INST_f_enqEn_lat_1.METH_whas();
    DEF_ab__h12753 = INST_f_tempData_rl.METH_read();
    DEF_ab__h12749 = INST_f_tempData_lat.METH_wget();
    DEF_f_tempEnqP_rl___d423 = INST_f_tempEnqP_rl.METH_read();
    DEF_upd__h19951 = INST_f_deqP_rl.METH_read();
    DEF_f_tempEnqP_lat_wget____d406 = INST_f_tempEnqP_lat.METH_wget();
    DEF_upd__h14841 = INST_f_deqP_lat_1.METH_wget();
    DEF_upd__h14874 = INST_f_deqP_lat.METH_wget();
    DEF_upd__h19299 = INST_f_enqP_rl.METH_read();
    DEF_upd__h14561 = INST_f_enqP_lat_1.METH_wget();
    DEF_upd__h14594 = INST_f_enqP_lat.METH_wget();
    DEF_f_tempEnqP_lat_whas____d414 = INST_f_tempEnqP_lat.METH_whas();
    DEF_f_tempData_dummy2_1__h17068 = INST_f_tempData_dummy2_1.METH_read();
    DEF_f_deqEn_rl__h11650 = INST_f_deqEn_rl.METH_read();
    DEF_f_deqEn_lat_whas____d412 = INST_f_deqEn_lat.METH_whas();
    DEF_f_deqEn_lat_1_wget____d404 = INST_f_deqEn_lat_1.METH_wget();
    DEF_f_deqEn_lat_1_whas__70_CONCAT_IF_f_deqEn_lat_1_ETC___d247 = (tUInt8)3u & ((DEF_f_deqEn_lat_1_whas____d413 << 1u) | (DEF_f_deqEn_lat_1_whas____d413 ? DEF_f_deqEn_lat_1_wget____d404 : DEF_f_deqEn_lat_1_wget____d404));
    DEF_f_deqEn_lat_wget____d403 = INST_f_deqEn_lat.METH_wget();
    DEF_f_deqEn_lat_whas__72_CONCAT_IF_f_deqEn_lat_wha_ETC___d245 = (tUInt8)3u & ((DEF_f_deqEn_lat_whas____d412 << 1u) | (DEF_f_deqEn_lat_whas____d412 ? DEF_f_deqEn_lat_wget____d403 : DEF_f_deqEn_lat_wget____d403));
    DEF_f_enqEn_rl__h10049 = INST_f_enqEn_rl.METH_read();
    DEF_f_enqEn_lat_1_wget____d402 = INST_f_enqEn_lat_1.METH_wget();
    DEF_f_enqEn_lat_1_whas__60_CONCAT_IF_f_enqEn_lat_1_ETC___d233 = (tUInt8)3u & ((DEF_f_enqEn_lat_1_whas____d411 << 1u) | (DEF_f_enqEn_lat_1_whas____d411 ? DEF_f_enqEn_lat_1_wget____d402 : DEF_f_enqEn_lat_1_wget____d402));
    DEF_f_enqEn_lat_whas____d410 = INST_f_enqEn_lat.METH_whas();
    DEF_f_enqEn_lat_wget____d401 = INST_f_enqEn_lat.METH_wget();
    DEF_f_enqEn_lat_whas__62_CONCAT_IF_f_enqEn_lat_wha_ETC___d231 = (tUInt8)3u & ((DEF_f_enqEn_lat_whas____d410 << 1u) | (DEF_f_enqEn_lat_whas____d410 ? DEF_f_enqEn_lat_wget____d401 : DEF_f_enqEn_lat_wget____d401));
    DEF_f_deqP_dummy2_2__h14802 = INST_f_deqP_dummy2_2.METH_read();
    DEF_f_enqP_dummy2_2__h14522 = INST_f_enqP_dummy2_2.METH_read();
    DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400 = (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_lat_wget____d406);
    DEF_f_tempEnqP_rl_91_BIT_4___d420 = (tUInt8)(DEF_f_tempEnqP_rl___d423 >> 4u);
    DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 = (tUInt8)(DEF_f_tempEnqP_lat_wget____d406 >> 4u);
    DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389 = DEF_f_tempEnqP_lat_whas____d414 ? DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 : DEF_f_tempEnqP_rl_91_BIT_4___d420;
    DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250 = DEF_NOT_f_tempEnqP_dummy2_1_48___d249 || DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389;
    DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384 = DEF_f_tempEnqP_lat_whas____d414 ? !DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 : !DEF_f_tempEnqP_rl_91_BIT_4___d420;
    DEF_f_tempEnqP_dummy2_1_48_AND_IF_f_tempEnqP_lat_w_ETC___d251 = DEF_f_tempEnqP_dummy2_1__h16526 && DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384;
    DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388 = INST_f_tempData_lat.METH_whas() ? DEF_ab__h12749 : DEF_ab__h12753;
    DEF_IF_f_tempData_dummy2_1_56_THEN_IF_f_tempData_l_ETC___d430 = DEF_f_tempData_dummy2_1__h17068 ? DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388 : DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388;
    DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398 = DEF_f_tempEnqP_lat_whas____d414 ? DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400 : (tUInt8)((tUInt8)15u & DEF_f_tempEnqP_rl___d423);
    DEF_IF_f_tempEnqP_dummy2_1_48_THEN_IF_f_tempEnqP_l_ETC___d387 = DEF_f_tempEnqP_dummy2_1__h16526 ? DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398 : DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398;
    DEF_x__h16617 = DEF_f_tempEnqP_dummy2_1_48_AND_IF_f_tempEnqP_lat_w_ETC___d251 ? DEF_IF_f_tempEnqP_dummy2_1_48_THEN_IF_f_tempEnqP_l_ETC___d387 : DEF_IF_f_tempEnqP_dummy2_1_48_THEN_IF_f_tempEnqP_l_ETC___d387;
    DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d263 = DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250 && DEF_x__h16617 == (tUInt8)3u;
    DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d261 = DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250 && DEF_x__h16617 == (tUInt8)2u;
    DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d255 = DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250 && DEF_x__h16617 == (tUInt8)0u;
    DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d259 = DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250 && DEF_x__h16617 == (tUInt8)1u;
    DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396 = INST_f_deqP_lat_1.METH_whas() ? DEF_upd__h14841 : (INST_f_deqP_lat.METH_whas() ? DEF_upd__h14874 : DEF_upd__h19951);
    DEF_n__read__h14675 = DEF_f_deqP_dummy2_2__h14802 ? DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396 : DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396;
    DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394 = INST_f_enqP_lat_1.METH_whas() ? DEF_upd__h14561 : (INST_f_enqP_lat.METH_whas() ? DEF_upd__h14594 : DEF_upd__h19299);
    DEF_n__read__h14395 = DEF_f_enqP_dummy2_2__h14522 ? DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394 : DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394;
    DEF_IF_f_tempEnqP_lat_wget__89_BIT_4_90_THEN_f_tem_ETC___d431 = DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 ? DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400 : DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400;
    DEF_f_tempEnqP_lat_whas__88_CONCAT_IF_f_tempEnqP_l_ETC___d269 = (tUInt8)63u & ((DEF_f_tempEnqP_lat_whas____d414 << 5u) | (DEF_f_tempEnqP_lat_whas____d414 ? (tUInt8)31u & ((DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 << 4u) | DEF_IF_f_tempEnqP_lat_wget__89_BIT_4_90_THEN_f_tem_ETC___d431) : (tUInt8)31u & ((DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 << 4u) | DEF_IF_f_tempEnqP_lat_wget__89_BIT_4_90_THEN_f_tem_ETC___d431)));
    DEF_IF_f_deqEn_lat_1_whas__70_THEN_NOT_f_deqEn_lat_ETC___d393 = DEF_f_deqEn_lat_1_whas____d413 ? !DEF_f_deqEn_lat_1_wget____d404 : (DEF_f_deqEn_lat_whas____d412 ? !DEF_f_deqEn_lat_wget____d403 : !DEF_f_deqEn_rl__h11650);
    DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d240 = DEF_f_deqEn_dummy2_2__h15721 ? DEF_IF_f_deqEn_lat_1_whas__70_THEN_NOT_f_deqEn_lat_ETC___d393 : DEF_IF_f_deqEn_lat_1_whas__70_THEN_NOT_f_deqEn_lat_ETC___d393;
    DEF_IF_f_enqEn_lat_1_whas__60_THEN_NOT_f_enqEn_lat_ETC___d391 = DEF_f_enqEn_lat_1_whas____d411 ? !DEF_f_enqEn_lat_1_wget____d402 : (DEF_f_enqEn_lat_whas____d410 ? !DEF_f_enqEn_lat_wget____d401 : !DEF_f_enqEn_rl__h10049);
    DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d213 = DEF_f_enqEn_dummy2_2__h14218 ? DEF_IF_f_enqEn_lat_1_whas__60_THEN_NOT_f_enqEn_lat_ETC___d391 : DEF_IF_f_enqEn_lat_1_whas__60_THEN_NOT_f_enqEn_lat_ETC___d391;
    DEF_y__h14944 = (tUInt8)15u & ((tUInt8)((tUInt8)3u & DEF_n__read__h14675));
    DEF_x__h14945 = (tUInt8)15u & ((tUInt8)((tUInt8)3u & DEF_n__read__h14395));
    DEF_x__h14943 = (tUInt8)15u & (DEF_x__h14945 + (tUInt8)4u);
    DEF_cnt__h14016 = DEF_n__read__h14395 < DEF_n__read__h14675 ? (tUInt8)15u & (DEF_x__h14943 - DEF_y__h14944) : (tUInt8)15u & (DEF_n__read__h14395 - DEF_n__read__h14675);
    DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d243 = DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d240 && !(DEF_cnt__h14016 == (tUInt8)0u);
    DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d229 = DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d213 && !(DEF_cnt__h14016 == (tUInt8)4u);
    DEF__0_CONCAT_DONTCARE___d405 = (tUInt8)31u & (tUInt8)10u;
    if (DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d229)
      INST_f_enqEn_lat_2.METH_wset((tUInt8)1u);
    if (DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d229)
      INST_f_enqEn_dummy2_2.METH_write((tUInt8)1u);
    if (DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d229)
      INST_f_enqEn_dummy_6.METH_wset(DEF_f_enqEn_lat_whas__62_CONCAT_IF_f_enqEn_lat_wha_ETC___d231);
    if (DEF_IF_f_enqEn_dummy2_2_07_THEN_IF_f_enqEn_lat_1_w_ETC___d229)
      INST_f_enqEn_dummy_7.METH_wset(DEF_f_enqEn_lat_1_whas__60_CONCAT_IF_f_enqEn_lat_1_ETC___d233);
    if (DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d243)
      INST_f_deqEn_lat_2.METH_wset((tUInt8)1u);
    if (DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d243)
      INST_f_deqEn_dummy2_2.METH_write((tUInt8)1u);
    if (DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d243)
      INST_f_deqEn_dummy_7.METH_wset(DEF_f_deqEn_lat_1_whas__70_CONCAT_IF_f_deqEn_lat_1_ETC___d247);
    if (DEF_IF_f_deqEn_dummy2_2_34_THEN_IF_f_deqEn_lat_1_w_ETC___d243)
      INST_f_deqEn_dummy_6.METH_wset(DEF_f_deqEn_lat_whas__72_CONCAT_IF_f_deqEn_lat_wha_ETC___d245);
    if (DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d255)
      INST_f_data.METH_write(DEF_IF_f_tempData_dummy2_1_56_THEN_IF_f_tempData_l_ETC___d430);
    if (DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d259)
      INST_f_data_1.METH_write(DEF_IF_f_tempData_dummy2_1_56_THEN_IF_f_tempData_l_ETC___d430);
    if (DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d261)
      INST_f_data_2.METH_write(DEF_IF_f_tempData_dummy2_1_56_THEN_IF_f_tempData_l_ETC___d430);
    if (DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d263)
      INST_f_data_3.METH_write(DEF_IF_f_tempData_dummy2_1_56_THEN_IF_f_tempData_l_ETC___d430);
    if (DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250)
      INST_f_tempEnqP_lat_1.METH_wset(DEF__0_CONCAT_DONTCARE___d405);
    if (DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250)
      INST_f_tempEnqP_dummy2_1.METH_write((tUInt8)1u);
    if (DEF_NOT_f_tempEnqP_dummy2_1_48_49_OR_IF_f_tempEnqP_ETC___d250)
      INST_f_tempEnqP_dummy_2.METH_wset(DEF_f_tempEnqP_lat_whas__88_CONCAT_IF_f_tempEnqP_l_ETC___d269);
  }
  
  void MOD_mkSignedTb::RL_enq()
  {
    tUInt8 DEF_x__h19477;
    tUInt8 DEF__4_CONCAT_IF_f_enqP_dummy2_99_AND_f_enqP_dummy2_ETC___d305;
    tUInt32 DEF_TASK_getRandom_81_BITS_15_TO_0_85_CONCAT_TASK__ETC___d298;
    tUInt32 DEF_x__h19709;
    tUInt8 DEF_NOT_TASK_getRandom_83_BIT_15_84___d422;
    tUInt8 DEF_NOT_TASK_getRandom_81_BIT_15_82___d421;
    tUInt32 DEF_aIn__h18644;
    tUInt32 DEF_IF_TASK_getRandom_81_BIT_15_82_THEN_NEG_TASK_g_ETC___d287;
    tUInt32 DEF_bIn__h18424;
    tUInt32 DEF_IF_NOT_TASK_getRandom_81_BIT_15_82_88_AND_NOT__ETC___d297;
    tUInt8 DEF_x__h18070;
    tUInt8 DEF_x__h18015;
    tUInt8 DEF_x__h19514;
    tUInt32 DEF_x__h19131;
    tUInt32 DEF_x__h19130;
    tUInt8 DEF_f_enqP_dummy2__h19342;
    tUInt8 DEF_f_enqP_dummy2_1__h19354;
    DEF_x__h19728 = INST_enqCount.METH_read();
    DEF_upd__h19299 = INST_f_enqP_rl.METH_read();
    DEF_f_enqP_dummy2_2__h14522 = INST_f_enqP_dummy2_2.METH_read();
    DEF_f_enqP_dummy2_1__h19354 = INST_f_enqP_dummy2_1.METH_read();
    DEF_f_enqP_dummy2__h19342 = INST_f_enqP_dummy2.METH_read();
    DEF_x__h19514 = (DEF_f_enqP_dummy2__h19342 && DEF_f_enqP_dummy2_1__h19354) && DEF_f_enqP_dummy2_2__h14522 ? DEF_upd__h19299 : DEF_upd__h19299;
    DEF_x__h19709 = 65535u & (DEF_x__h19728 + 1u);
    DEF__4_CONCAT_IF_f_enqP_dummy2_99_AND_f_enqP_dummy2_ETC___d305 = (tUInt8)31u & (((tUInt8)4u << 2u) | (tUInt8)((tUInt8)3u & DEF_x__h19514));
    DEF_x__h19477 = (tUInt8)15u & ((tUInt8)((tUInt8)7u & ((tUInt8)15u & (DEF_x__h19514 + (tUInt8)1u))));
    if (!(PORT_RST_N == (tUInt8)0u))
      DEF_TASK_getRandom___d408 = getRandom();
    DEF_x__h19130 = (tUInt32)(65535u & DEF_TASK_getRandom___d408);
    DEF_x__h18015 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d408 >> 15u));
    DEF_aIn__h18644 = 65535u & -DEF_x__h19130;
    DEF_IF_TASK_getRandom_81_BIT_15_82_THEN_NEG_TASK_g_ETC___d287 = DEF_x__h18015 ? DEF_aIn__h18644 : DEF_x__h19130;
    DEF_NOT_TASK_getRandom_81_BIT_15_82___d421 = !DEF_x__h18015;
    if (!(PORT_RST_N == (tUInt8)0u))
      DEF_TASK_getRandom___d409 = getRandom();
    DEF_x__h19131 = (tUInt32)(65535u & DEF_TASK_getRandom___d409);
    DEF_x__h18070 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d409 >> 15u));
    DEF_bIn__h18424 = 65535u & -DEF_x__h19131;
    DEF_NOT_TASK_getRandom_83_BIT_15_84___d422 = !DEF_x__h18070;
    DEF_IF_NOT_TASK_getRandom_81_BIT_15_82_88_AND_NOT__ETC___d297 = DEF_NOT_TASK_getRandom_81_BIT_15_82___d421 && DEF_NOT_TASK_getRandom_83_BIT_15_84___d422 ? DEF_x__h19131 : (DEF_NOT_TASK_getRandom_81_BIT_15_82___d421 && DEF_x__h18070 ? DEF_bIn__h18424 : (DEF_x__h18015 && DEF_NOT_TASK_getRandom_83_BIT_15_84___d422 ? DEF_x__h19131 : DEF_bIn__h18424));
    DEF_TASK_getRandom_81_BITS_15_TO_0_85_CONCAT_TASK__ETC___d298 = (DEF_x__h19130 << 16u) | DEF_x__h19131;
    INST_mult_asign.METH_write(DEF_x__h18015);
    INST_mult_bsign.METH_write(DEF_x__h18070);
    INST_mult_mul_a.METH_write(DEF_IF_TASK_getRandom_81_BIT_15_82_THEN_NEG_TASK_g_ETC___d287);
    INST_mult_mul_b.METH_write(DEF_IF_NOT_TASK_getRandom_81_BIT_15_82_88_AND_NOT__ETC___d297);
    INST_mult_mul_i.METH_write((tUInt8)0u);
    INST_mult_mul_tp.METH_write(0u);
    INST_mult_mul_prod.METH_write(0u);
    INST_mult_i.METH_write(0u);
    INST_f_tempData_dummy2.METH_write((tUInt8)1u);
    INST_f_tempData_lat.METH_wset(DEF_TASK_getRandom_81_BITS_15_TO_0_85_CONCAT_TASK__ETC___d298);
    INST_f_tempEnqP_lat.METH_wset(DEF__4_CONCAT_IF_f_enqP_dummy2_99_AND_f_enqP_dummy2_ETC___d305);
    INST_f_tempEnqP_dummy2.METH_write((tUInt8)1u);
    INST_f_enqP_lat.METH_wset(DEF_x__h19477);
    INST_f_enqP_dummy2.METH_write((tUInt8)1u);
    INST_f_enqEn_lat.METH_wset((tUInt8)0u);
    INST_f_enqEn_dummy2.METH_write((tUInt8)1u);
    INST_enqCount.METH_write(DEF_x__h19709);
  }
  
  void MOD_mkSignedTb::RL_deq()
  {
    tUInt8 DEF_x__h19883;
    tUInt32 DEF_x__h20675;
    tUInt32 DEF_v2__h20211;
    tUInt32 DEF_v1__h20210;
    tUInt8 DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dum_ETC___d363;
    tUInt8 DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d427;
    tUInt8 DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d426;
    tUInt8 DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d425;
    tUInt8 DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d417;
    tUInt32 DEF_k1__h20435;
    tUInt32 DEF_k2__h20436;
    tUInt32 DEF_x_result__h4412;
    tUInt32 DEF_k4__h20438;
    tUInt32 DEF_k3__h20437;
    tUInt32 DEF_val2__h19741;
    tUInt8 DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d392;
    tUInt32 DEF_val1__h19740;
    tUInt8 DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d385;
    tUInt32 DEF_res__h20209;
    tUInt8 DEF_IF_mult_asign_56_EQ_mult_bsign_57_58_THEN_mult_ETC___d383;
    tUInt8 DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d386;
    tUInt8 DEF_x__h19935;
    tUInt8 DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d424;
    tUInt32 DEF__read_snd__h20344;
    tUInt32 DEF__read_fst__h20343;
    tUInt32 DEF__read_snd__h20348;
    tUInt32 DEF__read_fst__h20347;
    tUInt32 DEF__read_snd__h20352;
    tUInt32 DEF__read_fst__h20351;
    tUInt32 DEF__read_snd__h20356;
    tUInt32 DEF__read_fst__h20355;
    tUInt64 DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d416;
    tUInt32 DEF_actual__h20212;
    tUInt8 DEF_f_deqP_dummy2__h19994;
    tUInt8 DEF_f_deqP_dummy2_1__h20006;
    tUInt8 DEF__read__h4615;
    tUInt8 DEF__read__h4655;
    tUInt32 DEF_ab__h20341;
    tUInt32 DEF_ab__h20345;
    tUInt32 DEF_ab__h20349;
    tUInt32 DEF_ab__h20353;
    DEF_ab__h20353 = INST_f_data_3.METH_read();
    DEF_ab__h20349 = INST_f_data_2.METH_read();
    DEF_ab__h20345 = INST_f_data_1.METH_read();
    DEF_ab__h20341 = INST_f_data.METH_read();
    DEF_mult_mul_tp__h3533 = INST_mult_mul_tp.METH_read();
    DEF__read__h154 = INST_mult_mul_prod.METH_read();
    DEF_x__h20679 = INST_deqCount.METH_read();
    DEF_upd__h19951 = INST_f_deqP_rl.METH_read();
    DEF__read__h4655 = INST_mult_bsign.METH_read();
    DEF__read__h4615 = INST_mult_asign.METH_read();
    DEF_f_deqP_dummy2_2__h14802 = INST_f_deqP_dummy2_2.METH_read();
    DEF_f_deqP_dummy2_1__h20006 = INST_f_deqP_dummy2_1.METH_read();
    DEF_f_deqP_dummy2__h19994 = INST_f_deqP_dummy2.METH_read();
    DEF__read_fst__h20355 = (tUInt32)(DEF_ab__h20353 >> 16u);
    DEF__read_fst__h20351 = (tUInt32)(DEF_ab__h20349 >> 16u);
    DEF__read_snd__h20356 = (tUInt32)(65535u & DEF_ab__h20353);
    DEF__read_snd__h20352 = (tUInt32)(65535u & DEF_ab__h20349);
    DEF__read_fst__h20347 = (tUInt32)(DEF_ab__h20345 >> 16u);
    DEF__read_snd__h20348 = (tUInt32)(65535u & DEF_ab__h20345);
    DEF__read_fst__h20343 = (tUInt32)(DEF_ab__h20341 >> 16u);
    DEF__read_snd__h20344 = (tUInt32)(65535u & DEF_ab__h20341);
    DEF_x__h19935 = (DEF_f_deqP_dummy2__h19994 && DEF_f_deqP_dummy2_1__h20006) && DEF_f_deqP_dummy2_2__h14802 ? DEF_upd__h19951 : DEF_upd__h19951;
    DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d424 = (tUInt8)((tUInt8)3u & DEF_x__h19935);
    DEF_x_result__h4412 = (DEF_mult_mul_tp__h3533 << 16u) | DEF__read__h154;
    DEF_res__h20209 = DEF__read__h4615 == DEF__read__h4655 ? DEF_x_result__h4412 : -DEF_x_result__h4412;
    DEF_IF_mult_asign_56_EQ_mult_bsign_57_58_THEN_mult_ETC___d383 = (tUInt8)(DEF_res__h20209 >> 31u);
    DEF_str3__h20433 = DEF_IF_mult_asign_56_EQ_mult_bsign_57_58_THEN_mult_ETC___d383 ? __str_literal_1 : __str_literal_2;
    DEF_k3__h20437 = DEF_IF_mult_asign_56_EQ_mult_bsign_57_58_THEN_mult_ETC___d383 ? -DEF_res__h20209 : DEF_res__h20209;
    DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d417 = DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d424 == (tUInt8)0u;
    DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d425 = DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d424 == (tUInt8)1u;
    DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d426 = DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d424 == (tUInt8)2u;
    DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d427 = DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d424 == (tUInt8)3u;
    DEF_val1__h19740 = DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d417 ? DEF__read_fst__h20343 : (DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d425 ? DEF__read_fst__h20347 : (DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d426 ? DEF__read_fst__h20351 : (DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d427 ? DEF__read_fst__h20355 : DEF__read_fst__h20355)));
    DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d385 = (tUInt8)(DEF_val1__h19740 >> 15u);
    DEF_val2__h19741 = DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d417 ? DEF__read_snd__h20344 : (DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d425 ? DEF__read_snd__h20348 : (DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d426 ? DEF__read_snd__h20352 : (DEF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20_21__ETC___d427 ? DEF__read_snd__h20356 : DEF__read_snd__h20356)));
    DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d392 = (tUInt8)(DEF_val2__h19741 >> 15u);
    DEF_str2__h20432 = DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d392 ? __str_literal_1 : __str_literal_2;
    DEF_str1__h20431 = DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d385 ? __str_literal_1 : __str_literal_2;
    DEF_k2__h20436 = DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d392 ? 65535u & -DEF_val2__h19741 : DEF_val2__h19741;
    DEF_k1__h20435 = DEF_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2_1_20__ETC___d385 ? 65535u & -DEF_val1__h19740 : DEF_val1__h19740;
    DEF_v1__h20210 = primSignExt32(32u, 16u, (tUInt32)(DEF_val1__h19740));
    DEF_v2__h20211 = primSignExt32(32u, 16u, (tUInt32)(DEF_val2__h19741));
    DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d416 = ((tUInt64)(DEF_v1__h20210)) * ((tUInt64)(DEF_v2__h20211));
    DEF_actual__h20212 = (tUInt32)(DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d416);
    DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d386 = (tUInt8)((tUInt8)1u & (DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d416 >> 31u));
    DEF_str4__h20434 = DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d386 ? __str_literal_1 : __str_literal_2;
    DEF_k4__h20438 = DEF_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dummy2__ETC___d386 ? -DEF_actual__h20212 : DEF_actual__h20212;
    DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dum_ETC___d363 = !(DEF_actual__h20212 == DEF_res__h20209);
    DEF_x__h20675 = 65535u & (DEF_x__h20679 + 1u);
    DEF_x__h19883 = (tUInt8)15u & ((tUInt8)((tUInt8)7u & ((tUInt8)15u & (DEF_x__h19935 + (tUInt8)1u))));
    INST_f_deqP_lat.METH_wset(DEF_x__h19883);
    INST_f_deqP_dummy2.METH_write((tUInt8)1u);
    INST_f_deqEn_lat.METH_wset((tUInt8)0u);
    INST_f_deqEn_dummy2.METH_write((tUInt8)1u);
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      if (DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dum_ETC___d363)
	dollar_display(this,
		       "s,s,16,s,16,s,32,s,32",
		       &__str_literal_3,
		       &DEF_str1__h20431,
		       DEF_k1__h20435,
		       &DEF_str2__h20432,
		       DEF_k2__h20436,
		       &DEF_str4__h20434,
		       DEF_k4__h20438,
		       &DEF_str3__h20433,
		       DEF_k3__h20437);
      if (DEF_NOT_SEXT_IF_IF_f_deqP_dummy2_19_AND_f_deqP_dum_ETC___d363)
	dollar_finish("32", 1u);
      dollar_display(this,
		     "s,16,16,32",
		     &__str_literal_4,
		     DEF_val1__h19740,
		     DEF_val2__h19741,
		     DEF_res__h20209);
    }
    INST_deqCount.METH_write(DEF_x__h20675);
  }
  
  void MOD_mkSignedTb::RL_fin()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      dollar_display(this, "s", &__str_literal_5);
      dollar_finish("32", 1u);
    }
  }
  
  
  /* Methods */
  
  
  /* Reset routines */
  
  void MOD_mkSignedTb::reset_RST_N(tUInt8 ARG_rst_in)
  {
    PORT_RST_N = ARG_rst_in;
    INST_randomVal2_init.reset_RST_N(ARG_rst_in);
    INST_randomVal1_init.reset_RST_N(ARG_rst_in);
    INST_mult_mul_i.reset_RST_N(ARG_rst_in);
    INST_mult_i.reset_RST_N(ARG_rst_in);
    INST_f_tempEnqP_rl.reset_RST_N(ARG_rst_in);
    INST_f_tempEnqP_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_tempEnqP_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_tempData_rl.reset_RST_N(ARG_rst_in);
    INST_f_tempData_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_tempData_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_enqP_rl.reset_RST_N(ARG_rst_in);
    INST_f_enqP_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_enqP_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_enqP_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_rl.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_enqEn_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_deqP_rl.reset_RST_N(ARG_rst_in);
    INST_f_deqP_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_deqP_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_deqP_dummy2.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_rl.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_dummy2_2.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_dummy2_1.reset_RST_N(ARG_rst_in);
    INST_f_deqEn_dummy2.reset_RST_N(ARG_rst_in);
    INST_enqCount.reset_RST_N(ARG_rst_in);
    INST_deqCount.reset_RST_N(ARG_rst_in);
  }
  
  
  /* Static handles to reset routines */
  
  
  /* Functions for the parent module to register its reset fns */
  
  
  /* Functions to set the elaborated clock id */
  
  void MOD_mkSignedTb::set_clk_0(char const *s)
  {
    __clk_handle_0 = bk_get_or_define_clock(s);
  }
  
  
  /* State dumping routine */
  void MOD_mkSignedTb::dump_state(unsigned int indent)
  {
    printf("%*s%s:\n", indent, "", inst_name);
    INST_deqCount.dump_state(indent + 2u);
    INST_enqCount.dump_state(indent + 2u);
    INST_f_data.dump_state(indent + 2u);
    INST_f_data_1.dump_state(indent + 2u);
    INST_f_data_2.dump_state(indent + 2u);
    INST_f_data_3.dump_state(indent + 2u);
    INST_f_deqEn_dummy.dump_state(indent + 2u);
    INST_f_deqEn_dummy2.dump_state(indent + 2u);
    INST_f_deqEn_dummy2_1.dump_state(indent + 2u);
    INST_f_deqEn_dummy2_2.dump_state(indent + 2u);
    INST_f_deqEn_dummy_1.dump_state(indent + 2u);
    INST_f_deqEn_dummy_2.dump_state(indent + 2u);
    INST_f_deqEn_dummy_3.dump_state(indent + 2u);
    INST_f_deqEn_dummy_4.dump_state(indent + 2u);
    INST_f_deqEn_dummy_5.dump_state(indent + 2u);
    INST_f_deqEn_dummy_6.dump_state(indent + 2u);
    INST_f_deqEn_dummy_7.dump_state(indent + 2u);
    INST_f_deqEn_dummy_8.dump_state(indent + 2u);
    INST_f_deqEn_lat.dump_state(indent + 2u);
    INST_f_deqEn_lat_1.dump_state(indent + 2u);
    INST_f_deqEn_lat_2.dump_state(indent + 2u);
    INST_f_deqEn_rl.dump_state(indent + 2u);
    INST_f_deqP_dummy.dump_state(indent + 2u);
    INST_f_deqP_dummy2.dump_state(indent + 2u);
    INST_f_deqP_dummy2_1.dump_state(indent + 2u);
    INST_f_deqP_dummy2_2.dump_state(indent + 2u);
    INST_f_deqP_dummy_1.dump_state(indent + 2u);
    INST_f_deqP_dummy_2.dump_state(indent + 2u);
    INST_f_deqP_dummy_3.dump_state(indent + 2u);
    INST_f_deqP_dummy_4.dump_state(indent + 2u);
    INST_f_deqP_dummy_5.dump_state(indent + 2u);
    INST_f_deqP_dummy_6.dump_state(indent + 2u);
    INST_f_deqP_dummy_7.dump_state(indent + 2u);
    INST_f_deqP_dummy_8.dump_state(indent + 2u);
    INST_f_deqP_lat.dump_state(indent + 2u);
    INST_f_deqP_lat_1.dump_state(indent + 2u);
    INST_f_deqP_lat_2.dump_state(indent + 2u);
    INST_f_deqP_rl.dump_state(indent + 2u);
    INST_f_enqEn_dummy.dump_state(indent + 2u);
    INST_f_enqEn_dummy2.dump_state(indent + 2u);
    INST_f_enqEn_dummy2_1.dump_state(indent + 2u);
    INST_f_enqEn_dummy2_2.dump_state(indent + 2u);
    INST_f_enqEn_dummy_1.dump_state(indent + 2u);
    INST_f_enqEn_dummy_2.dump_state(indent + 2u);
    INST_f_enqEn_dummy_3.dump_state(indent + 2u);
    INST_f_enqEn_dummy_4.dump_state(indent + 2u);
    INST_f_enqEn_dummy_5.dump_state(indent + 2u);
    INST_f_enqEn_dummy_6.dump_state(indent + 2u);
    INST_f_enqEn_dummy_7.dump_state(indent + 2u);
    INST_f_enqEn_dummy_8.dump_state(indent + 2u);
    INST_f_enqEn_lat.dump_state(indent + 2u);
    INST_f_enqEn_lat_1.dump_state(indent + 2u);
    INST_f_enqEn_lat_2.dump_state(indent + 2u);
    INST_f_enqEn_rl.dump_state(indent + 2u);
    INST_f_enqP_dummy.dump_state(indent + 2u);
    INST_f_enqP_dummy2.dump_state(indent + 2u);
    INST_f_enqP_dummy2_1.dump_state(indent + 2u);
    INST_f_enqP_dummy2_2.dump_state(indent + 2u);
    INST_f_enqP_dummy_1.dump_state(indent + 2u);
    INST_f_enqP_dummy_2.dump_state(indent + 2u);
    INST_f_enqP_dummy_3.dump_state(indent + 2u);
    INST_f_enqP_dummy_4.dump_state(indent + 2u);
    INST_f_enqP_dummy_5.dump_state(indent + 2u);
    INST_f_enqP_dummy_6.dump_state(indent + 2u);
    INST_f_enqP_dummy_7.dump_state(indent + 2u);
    INST_f_enqP_dummy_8.dump_state(indent + 2u);
    INST_f_enqP_lat.dump_state(indent + 2u);
    INST_f_enqP_lat_1.dump_state(indent + 2u);
    INST_f_enqP_lat_2.dump_state(indent + 2u);
    INST_f_enqP_rl.dump_state(indent + 2u);
    INST_f_tempData_dummy.dump_state(indent + 2u);
    INST_f_tempData_dummy2.dump_state(indent + 2u);
    INST_f_tempData_dummy2_1.dump_state(indent + 2u);
    INST_f_tempData_dummy_1.dump_state(indent + 2u);
    INST_f_tempData_dummy_2.dump_state(indent + 2u);
    INST_f_tempData_dummy_3.dump_state(indent + 2u);
    INST_f_tempData_lat.dump_state(indent + 2u);
    INST_f_tempData_lat_1.dump_state(indent + 2u);
    INST_f_tempData_rl.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy2.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy2_1.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy_1.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy_2.dump_state(indent + 2u);
    INST_f_tempEnqP_dummy_3.dump_state(indent + 2u);
    INST_f_tempEnqP_lat.dump_state(indent + 2u);
    INST_f_tempEnqP_lat_1.dump_state(indent + 2u);
    INST_f_tempEnqP_rl.dump_state(indent + 2u);
    INST_mult_a.dump_state(indent + 2u);
    INST_mult_asign.dump_state(indent + 2u);
    INST_mult_b.dump_state(indent + 2u);
    INST_mult_bsign.dump_state(indent + 2u);
    INST_mult_i.dump_state(indent + 2u);
    INST_mult_mul_a.dump_state(indent + 2u);
    INST_mult_mul_b.dump_state(indent + 2u);
    INST_mult_mul_i.dump_state(indent + 2u);
    INST_mult_mul_prod.dump_state(indent + 2u);
    INST_mult_mul_tp.dump_state(indent + 2u);
    INST_mult_res.dump_state(indent + 2u);
    INST_randomVal1_init.dump_state(indent + 2u);
    INST_randomVal2_init.dump_state(indent + 2u);
  }
  
  
  /* VCD dumping routines */
  
  unsigned int MOD_mkSignedTb::dump_VCD_defs(unsigned int levels)
  {
    fprintf(vcd_file, "$scope module %s $end\n", inst_name);
    vcd_num = vcd_reserve_ids(143u);
    unsigned int num = vcd_num;
    for (unsigned int hdl = 0u; hdl < bk_num_clocks(); ++hdl)
      vcd_add_clock_def(this, bk_clock_name(hdl), bk_clock_vcd_num(hdl));
    vcd_write_def(bk_clock_vcd_num(__clk_handle_0), "CLK", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398", 4u);
    vcd_write_def(num++, "RST_N", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d408", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d409", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "_read__h154", 16u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "_read__h241", 5u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "ab__h12749", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "ab__h12753", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_dummy2_2__h15721", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_1_wget____d404", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_1_whas____d413", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_wget____d403", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_lat_whas____d412", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqEn_rl__h11650", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_deqP_dummy2_2__h14802", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_dummy2_2__h14218", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_1_wget____d402", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_1_whas____d411", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_wget____d401", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_lat_whas____d410", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqEn_rl__h10049", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_enqP_dummy2_2__h14522", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_wget__89_BIT_4___d419", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_wget____d406", 5u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_lat_whas____d414", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_rl_91_BIT_4___d420", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "f_tempEnqP_rl___d423", 5u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "mult_mul_tp__h3533", 16u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h14561", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h14594", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h14841", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h14874", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h19299", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "upd__h19951", 4u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "x__h19728", 16u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "x__h20679", 16u);
    num = INST_deqCount.dump_VCD_defs(num);
    num = INST_enqCount.dump_VCD_defs(num);
    num = INST_f_data.dump_VCD_defs(num);
    num = INST_f_data_1.dump_VCD_defs(num);
    num = INST_f_data_2.dump_VCD_defs(num);
    num = INST_f_data_3.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy2.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy2_1.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy2_2.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_1.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_2.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_3.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_4.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_5.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_6.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_7.dump_VCD_defs(num);
    num = INST_f_deqEn_dummy_8.dump_VCD_defs(num);
    num = INST_f_deqEn_lat.dump_VCD_defs(num);
    num = INST_f_deqEn_lat_1.dump_VCD_defs(num);
    num = INST_f_deqEn_lat_2.dump_VCD_defs(num);
    num = INST_f_deqEn_rl.dump_VCD_defs(num);
    num = INST_f_deqP_dummy.dump_VCD_defs(num);
    num = INST_f_deqP_dummy2.dump_VCD_defs(num);
    num = INST_f_deqP_dummy2_1.dump_VCD_defs(num);
    num = INST_f_deqP_dummy2_2.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_1.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_2.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_3.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_4.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_5.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_6.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_7.dump_VCD_defs(num);
    num = INST_f_deqP_dummy_8.dump_VCD_defs(num);
    num = INST_f_deqP_lat.dump_VCD_defs(num);
    num = INST_f_deqP_lat_1.dump_VCD_defs(num);
    num = INST_f_deqP_lat_2.dump_VCD_defs(num);
    num = INST_f_deqP_rl.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy2.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy2_1.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy2_2.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_1.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_2.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_3.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_4.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_5.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_6.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_7.dump_VCD_defs(num);
    num = INST_f_enqEn_dummy_8.dump_VCD_defs(num);
    num = INST_f_enqEn_lat.dump_VCD_defs(num);
    num = INST_f_enqEn_lat_1.dump_VCD_defs(num);
    num = INST_f_enqEn_lat_2.dump_VCD_defs(num);
    num = INST_f_enqEn_rl.dump_VCD_defs(num);
    num = INST_f_enqP_dummy.dump_VCD_defs(num);
    num = INST_f_enqP_dummy2.dump_VCD_defs(num);
    num = INST_f_enqP_dummy2_1.dump_VCD_defs(num);
    num = INST_f_enqP_dummy2_2.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_1.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_2.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_3.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_4.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_5.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_6.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_7.dump_VCD_defs(num);
    num = INST_f_enqP_dummy_8.dump_VCD_defs(num);
    num = INST_f_enqP_lat.dump_VCD_defs(num);
    num = INST_f_enqP_lat_1.dump_VCD_defs(num);
    num = INST_f_enqP_lat_2.dump_VCD_defs(num);
    num = INST_f_enqP_rl.dump_VCD_defs(num);
    num = INST_f_tempData_dummy.dump_VCD_defs(num);
    num = INST_f_tempData_dummy2.dump_VCD_defs(num);
    num = INST_f_tempData_dummy2_1.dump_VCD_defs(num);
    num = INST_f_tempData_dummy_1.dump_VCD_defs(num);
    num = INST_f_tempData_dummy_2.dump_VCD_defs(num);
    num = INST_f_tempData_dummy_3.dump_VCD_defs(num);
    num = INST_f_tempData_lat.dump_VCD_defs(num);
    num = INST_f_tempData_lat_1.dump_VCD_defs(num);
    num = INST_f_tempData_rl.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy2.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy2_1.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy_1.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy_2.dump_VCD_defs(num);
    num = INST_f_tempEnqP_dummy_3.dump_VCD_defs(num);
    num = INST_f_tempEnqP_lat.dump_VCD_defs(num);
    num = INST_f_tempEnqP_lat_1.dump_VCD_defs(num);
    num = INST_f_tempEnqP_rl.dump_VCD_defs(num);
    num = INST_mult_a.dump_VCD_defs(num);
    num = INST_mult_asign.dump_VCD_defs(num);
    num = INST_mult_b.dump_VCD_defs(num);
    num = INST_mult_bsign.dump_VCD_defs(num);
    num = INST_mult_i.dump_VCD_defs(num);
    num = INST_mult_mul_a.dump_VCD_defs(num);
    num = INST_mult_mul_b.dump_VCD_defs(num);
    num = INST_mult_mul_i.dump_VCD_defs(num);
    num = INST_mult_mul_prod.dump_VCD_defs(num);
    num = INST_mult_mul_tp.dump_VCD_defs(num);
    num = INST_mult_res.dump_VCD_defs(num);
    num = INST_randomVal1_init.dump_VCD_defs(num);
    num = INST_randomVal2_init.dump_VCD_defs(num);
    fprintf(vcd_file, "$upscope $end\n");
    return num;
  }
  
  void MOD_mkSignedTb::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSignedTb &backing)
  {
    vcd_defs(dt, backing);
    vcd_prims(dt, backing);
  }
  
  void MOD_mkSignedTb::vcd_defs(tVCDDumpType dt, MOD_mkSignedTb &backing)
  {
    unsigned int num = vcd_num;
    if (dt == VCD_DUMP_XS)
    {
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 16u);
      vcd_write_x(num++, 5u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 5u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 5u);
      vcd_write_x(num++, 16u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 4u);
      vcd_write_x(num++, 16u);
      vcd_write_x(num++, 16u);
    }
    else
      if (dt == VCD_DUMP_CHANGES)
      {
	if ((backing.DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396) != DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396)
	{
	  vcd_write_val(num, DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396, 4u);
	  backing.DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396 = DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396;
	}
	++num;
	if ((backing.DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394) != DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394)
	{
	  vcd_write_val(num, DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394, 4u);
	  backing.DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394 = DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394;
	}
	++num;
	if ((backing.DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388) != DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388)
	{
	  vcd_write_val(num, DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388, 32u);
	  backing.DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388 = DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388;
	}
	++num;
	if ((backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384) != DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384)
	{
	  vcd_write_val(num, DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384, 1u);
	  backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384 = DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384;
	}
	++num;
	if ((backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389) != DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389)
	{
	  vcd_write_val(num, DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389, 1u);
	  backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389 = DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389;
	}
	++num;
	if ((backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398) != DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398)
	{
	  vcd_write_val(num, DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398, 4u);
	  backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398 = DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398;
	}
	++num;
	if ((backing.PORT_RST_N) != PORT_RST_N)
	{
	  vcd_write_val(num, PORT_RST_N, 1u);
	  backing.PORT_RST_N = PORT_RST_N;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d408) != DEF_TASK_getRandom___d408)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d408, 32u);
	  backing.DEF_TASK_getRandom___d408 = DEF_TASK_getRandom___d408;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d409) != DEF_TASK_getRandom___d409)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d409, 32u);
	  backing.DEF_TASK_getRandom___d409 = DEF_TASK_getRandom___d409;
	}
	++num;
	if ((backing.DEF__read__h154) != DEF__read__h154)
	{
	  vcd_write_val(num, DEF__read__h154, 16u);
	  backing.DEF__read__h154 = DEF__read__h154;
	}
	++num;
	if ((backing.DEF__read__h241) != DEF__read__h241)
	{
	  vcd_write_val(num, DEF__read__h241, 5u);
	  backing.DEF__read__h241 = DEF__read__h241;
	}
	++num;
	if ((backing.DEF_ab__h12749) != DEF_ab__h12749)
	{
	  vcd_write_val(num, DEF_ab__h12749, 32u);
	  backing.DEF_ab__h12749 = DEF_ab__h12749;
	}
	++num;
	if ((backing.DEF_ab__h12753) != DEF_ab__h12753)
	{
	  vcd_write_val(num, DEF_ab__h12753, 32u);
	  backing.DEF_ab__h12753 = DEF_ab__h12753;
	}
	++num;
	if ((backing.DEF_f_deqEn_dummy2_2__h15721) != DEF_f_deqEn_dummy2_2__h15721)
	{
	  vcd_write_val(num, DEF_f_deqEn_dummy2_2__h15721, 1u);
	  backing.DEF_f_deqEn_dummy2_2__h15721 = DEF_f_deqEn_dummy2_2__h15721;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_1_wget____d404) != DEF_f_deqEn_lat_1_wget____d404)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_1_wget____d404, 1u);
	  backing.DEF_f_deqEn_lat_1_wget____d404 = DEF_f_deqEn_lat_1_wget____d404;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_1_whas____d413) != DEF_f_deqEn_lat_1_whas____d413)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_1_whas____d413, 1u);
	  backing.DEF_f_deqEn_lat_1_whas____d413 = DEF_f_deqEn_lat_1_whas____d413;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_wget____d403) != DEF_f_deqEn_lat_wget____d403)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_wget____d403, 1u);
	  backing.DEF_f_deqEn_lat_wget____d403 = DEF_f_deqEn_lat_wget____d403;
	}
	++num;
	if ((backing.DEF_f_deqEn_lat_whas____d412) != DEF_f_deqEn_lat_whas____d412)
	{
	  vcd_write_val(num, DEF_f_deqEn_lat_whas____d412, 1u);
	  backing.DEF_f_deqEn_lat_whas____d412 = DEF_f_deqEn_lat_whas____d412;
	}
	++num;
	if ((backing.DEF_f_deqEn_rl__h11650) != DEF_f_deqEn_rl__h11650)
	{
	  vcd_write_val(num, DEF_f_deqEn_rl__h11650, 1u);
	  backing.DEF_f_deqEn_rl__h11650 = DEF_f_deqEn_rl__h11650;
	}
	++num;
	if ((backing.DEF_f_deqP_dummy2_2__h14802) != DEF_f_deqP_dummy2_2__h14802)
	{
	  vcd_write_val(num, DEF_f_deqP_dummy2_2__h14802, 1u);
	  backing.DEF_f_deqP_dummy2_2__h14802 = DEF_f_deqP_dummy2_2__h14802;
	}
	++num;
	if ((backing.DEF_f_enqEn_dummy2_2__h14218) != DEF_f_enqEn_dummy2_2__h14218)
	{
	  vcd_write_val(num, DEF_f_enqEn_dummy2_2__h14218, 1u);
	  backing.DEF_f_enqEn_dummy2_2__h14218 = DEF_f_enqEn_dummy2_2__h14218;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_1_wget____d402) != DEF_f_enqEn_lat_1_wget____d402)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_1_wget____d402, 1u);
	  backing.DEF_f_enqEn_lat_1_wget____d402 = DEF_f_enqEn_lat_1_wget____d402;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_1_whas____d411) != DEF_f_enqEn_lat_1_whas____d411)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_1_whas____d411, 1u);
	  backing.DEF_f_enqEn_lat_1_whas____d411 = DEF_f_enqEn_lat_1_whas____d411;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_wget____d401) != DEF_f_enqEn_lat_wget____d401)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_wget____d401, 1u);
	  backing.DEF_f_enqEn_lat_wget____d401 = DEF_f_enqEn_lat_wget____d401;
	}
	++num;
	if ((backing.DEF_f_enqEn_lat_whas____d410) != DEF_f_enqEn_lat_whas____d410)
	{
	  vcd_write_val(num, DEF_f_enqEn_lat_whas____d410, 1u);
	  backing.DEF_f_enqEn_lat_whas____d410 = DEF_f_enqEn_lat_whas____d410;
	}
	++num;
	if ((backing.DEF_f_enqEn_rl__h10049) != DEF_f_enqEn_rl__h10049)
	{
	  vcd_write_val(num, DEF_f_enqEn_rl__h10049, 1u);
	  backing.DEF_f_enqEn_rl__h10049 = DEF_f_enqEn_rl__h10049;
	}
	++num;
	if ((backing.DEF_f_enqP_dummy2_2__h14522) != DEF_f_enqP_dummy2_2__h14522)
	{
	  vcd_write_val(num, DEF_f_enqP_dummy2_2__h14522, 1u);
	  backing.DEF_f_enqP_dummy2_2__h14522 = DEF_f_enqP_dummy2_2__h14522;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400) != DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400, 4u);
	  backing.DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400 = DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_wget__89_BIT_4___d419) != DEF_f_tempEnqP_lat_wget__89_BIT_4___d419)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_wget__89_BIT_4___d419, 1u);
	  backing.DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 = DEF_f_tempEnqP_lat_wget__89_BIT_4___d419;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_wget____d406) != DEF_f_tempEnqP_lat_wget____d406)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_wget____d406, 5u);
	  backing.DEF_f_tempEnqP_lat_wget____d406 = DEF_f_tempEnqP_lat_wget____d406;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_lat_whas____d414) != DEF_f_tempEnqP_lat_whas____d414)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_lat_whas____d414, 1u);
	  backing.DEF_f_tempEnqP_lat_whas____d414 = DEF_f_tempEnqP_lat_whas____d414;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_rl_91_BIT_4___d420) != DEF_f_tempEnqP_rl_91_BIT_4___d420)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_rl_91_BIT_4___d420, 1u);
	  backing.DEF_f_tempEnqP_rl_91_BIT_4___d420 = DEF_f_tempEnqP_rl_91_BIT_4___d420;
	}
	++num;
	if ((backing.DEF_f_tempEnqP_rl___d423) != DEF_f_tempEnqP_rl___d423)
	{
	  vcd_write_val(num, DEF_f_tempEnqP_rl___d423, 5u);
	  backing.DEF_f_tempEnqP_rl___d423 = DEF_f_tempEnqP_rl___d423;
	}
	++num;
	if ((backing.DEF_mult_mul_tp__h3533) != DEF_mult_mul_tp__h3533)
	{
	  vcd_write_val(num, DEF_mult_mul_tp__h3533, 16u);
	  backing.DEF_mult_mul_tp__h3533 = DEF_mult_mul_tp__h3533;
	}
	++num;
	if ((backing.DEF_upd__h14561) != DEF_upd__h14561)
	{
	  vcd_write_val(num, DEF_upd__h14561, 4u);
	  backing.DEF_upd__h14561 = DEF_upd__h14561;
	}
	++num;
	if ((backing.DEF_upd__h14594) != DEF_upd__h14594)
	{
	  vcd_write_val(num, DEF_upd__h14594, 4u);
	  backing.DEF_upd__h14594 = DEF_upd__h14594;
	}
	++num;
	if ((backing.DEF_upd__h14841) != DEF_upd__h14841)
	{
	  vcd_write_val(num, DEF_upd__h14841, 4u);
	  backing.DEF_upd__h14841 = DEF_upd__h14841;
	}
	++num;
	if ((backing.DEF_upd__h14874) != DEF_upd__h14874)
	{
	  vcd_write_val(num, DEF_upd__h14874, 4u);
	  backing.DEF_upd__h14874 = DEF_upd__h14874;
	}
	++num;
	if ((backing.DEF_upd__h19299) != DEF_upd__h19299)
	{
	  vcd_write_val(num, DEF_upd__h19299, 4u);
	  backing.DEF_upd__h19299 = DEF_upd__h19299;
	}
	++num;
	if ((backing.DEF_upd__h19951) != DEF_upd__h19951)
	{
	  vcd_write_val(num, DEF_upd__h19951, 4u);
	  backing.DEF_upd__h19951 = DEF_upd__h19951;
	}
	++num;
	if ((backing.DEF_x__h19728) != DEF_x__h19728)
	{
	  vcd_write_val(num, DEF_x__h19728, 16u);
	  backing.DEF_x__h19728 = DEF_x__h19728;
	}
	++num;
	if ((backing.DEF_x__h20679) != DEF_x__h20679)
	{
	  vcd_write_val(num, DEF_x__h20679, 16u);
	  backing.DEF_x__h20679 = DEF_x__h20679;
	}
	++num;
      }
      else
      {
	vcd_write_val(num++, DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396, 4u);
	backing.DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396 = DEF_IF_f_deqP_lat_1_whas__50_THEN_f_deqP_lat_1_wge_ETC___d396;
	vcd_write_val(num++, DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394, 4u);
	backing.DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394 = DEF_IF_f_enqP_lat_1_whas__40_THEN_f_enqP_lat_1_wge_ETC___d394;
	vcd_write_val(num++, DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388, 32u);
	backing.DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388 = DEF_IF_f_tempData_lat_whas__80_THEN_f_tempData_lat_ETC___d388;
	vcd_write_val(num++, DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384, 1u);
	backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384 = DEF_IF_f_tempEnqP_lat_whas__88_THEN_NOT_f_tempEnqP_ETC___d384;
	vcd_write_val(num++, DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389, 1u);
	backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389 = DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d389;
	vcd_write_val(num++, DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398, 4u);
	backing.DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398 = DEF_IF_f_tempEnqP_lat_whas__88_THEN_f_tempEnqP_lat_ETC___d398;
	vcd_write_val(num++, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
	vcd_write_val(num++, DEF_TASK_getRandom___d408, 32u);
	backing.DEF_TASK_getRandom___d408 = DEF_TASK_getRandom___d408;
	vcd_write_val(num++, DEF_TASK_getRandom___d409, 32u);
	backing.DEF_TASK_getRandom___d409 = DEF_TASK_getRandom___d409;
	vcd_write_val(num++, DEF__read__h154, 16u);
	backing.DEF__read__h154 = DEF__read__h154;
	vcd_write_val(num++, DEF__read__h241, 5u);
	backing.DEF__read__h241 = DEF__read__h241;
	vcd_write_val(num++, DEF_ab__h12749, 32u);
	backing.DEF_ab__h12749 = DEF_ab__h12749;
	vcd_write_val(num++, DEF_ab__h12753, 32u);
	backing.DEF_ab__h12753 = DEF_ab__h12753;
	vcd_write_val(num++, DEF_f_deqEn_dummy2_2__h15721, 1u);
	backing.DEF_f_deqEn_dummy2_2__h15721 = DEF_f_deqEn_dummy2_2__h15721;
	vcd_write_val(num++, DEF_f_deqEn_lat_1_wget____d404, 1u);
	backing.DEF_f_deqEn_lat_1_wget____d404 = DEF_f_deqEn_lat_1_wget____d404;
	vcd_write_val(num++, DEF_f_deqEn_lat_1_whas____d413, 1u);
	backing.DEF_f_deqEn_lat_1_whas____d413 = DEF_f_deqEn_lat_1_whas____d413;
	vcd_write_val(num++, DEF_f_deqEn_lat_wget____d403, 1u);
	backing.DEF_f_deqEn_lat_wget____d403 = DEF_f_deqEn_lat_wget____d403;
	vcd_write_val(num++, DEF_f_deqEn_lat_whas____d412, 1u);
	backing.DEF_f_deqEn_lat_whas____d412 = DEF_f_deqEn_lat_whas____d412;
	vcd_write_val(num++, DEF_f_deqEn_rl__h11650, 1u);
	backing.DEF_f_deqEn_rl__h11650 = DEF_f_deqEn_rl__h11650;
	vcd_write_val(num++, DEF_f_deqP_dummy2_2__h14802, 1u);
	backing.DEF_f_deqP_dummy2_2__h14802 = DEF_f_deqP_dummy2_2__h14802;
	vcd_write_val(num++, DEF_f_enqEn_dummy2_2__h14218, 1u);
	backing.DEF_f_enqEn_dummy2_2__h14218 = DEF_f_enqEn_dummy2_2__h14218;
	vcd_write_val(num++, DEF_f_enqEn_lat_1_wget____d402, 1u);
	backing.DEF_f_enqEn_lat_1_wget____d402 = DEF_f_enqEn_lat_1_wget____d402;
	vcd_write_val(num++, DEF_f_enqEn_lat_1_whas____d411, 1u);
	backing.DEF_f_enqEn_lat_1_whas____d411 = DEF_f_enqEn_lat_1_whas____d411;
	vcd_write_val(num++, DEF_f_enqEn_lat_wget____d401, 1u);
	backing.DEF_f_enqEn_lat_wget____d401 = DEF_f_enqEn_lat_wget____d401;
	vcd_write_val(num++, DEF_f_enqEn_lat_whas____d410, 1u);
	backing.DEF_f_enqEn_lat_whas____d410 = DEF_f_enqEn_lat_whas____d410;
	vcd_write_val(num++, DEF_f_enqEn_rl__h10049, 1u);
	backing.DEF_f_enqEn_rl__h10049 = DEF_f_enqEn_rl__h10049;
	vcd_write_val(num++, DEF_f_enqP_dummy2_2__h14522, 1u);
	backing.DEF_f_enqP_dummy2_2__h14522 = DEF_f_enqP_dummy2_2__h14522;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400, 4u);
	backing.DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400 = DEF_f_tempEnqP_lat_wget__89_BITS_3_TO_0___d400;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_wget__89_BIT_4___d419, 1u);
	backing.DEF_f_tempEnqP_lat_wget__89_BIT_4___d419 = DEF_f_tempEnqP_lat_wget__89_BIT_4___d419;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_wget____d406, 5u);
	backing.DEF_f_tempEnqP_lat_wget____d406 = DEF_f_tempEnqP_lat_wget____d406;
	vcd_write_val(num++, DEF_f_tempEnqP_lat_whas____d414, 1u);
	backing.DEF_f_tempEnqP_lat_whas____d414 = DEF_f_tempEnqP_lat_whas____d414;
	vcd_write_val(num++, DEF_f_tempEnqP_rl_91_BIT_4___d420, 1u);
	backing.DEF_f_tempEnqP_rl_91_BIT_4___d420 = DEF_f_tempEnqP_rl_91_BIT_4___d420;
	vcd_write_val(num++, DEF_f_tempEnqP_rl___d423, 5u);
	backing.DEF_f_tempEnqP_rl___d423 = DEF_f_tempEnqP_rl___d423;
	vcd_write_val(num++, DEF_mult_mul_tp__h3533, 16u);
	backing.DEF_mult_mul_tp__h3533 = DEF_mult_mul_tp__h3533;
	vcd_write_val(num++, DEF_upd__h14561, 4u);
	backing.DEF_upd__h14561 = DEF_upd__h14561;
	vcd_write_val(num++, DEF_upd__h14594, 4u);
	backing.DEF_upd__h14594 = DEF_upd__h14594;
	vcd_write_val(num++, DEF_upd__h14841, 4u);
	backing.DEF_upd__h14841 = DEF_upd__h14841;
	vcd_write_val(num++, DEF_upd__h14874, 4u);
	backing.DEF_upd__h14874 = DEF_upd__h14874;
	vcd_write_val(num++, DEF_upd__h19299, 4u);
	backing.DEF_upd__h19299 = DEF_upd__h19299;
	vcd_write_val(num++, DEF_upd__h19951, 4u);
	backing.DEF_upd__h19951 = DEF_upd__h19951;
	vcd_write_val(num++, DEF_x__h19728, 16u);
	backing.DEF_x__h19728 = DEF_x__h19728;
	vcd_write_val(num++, DEF_x__h20679, 16u);
	backing.DEF_x__h20679 = DEF_x__h20679;
      }
  }
  
  void MOD_mkSignedTb::vcd_prims(tVCDDumpType dt, MOD_mkSignedTb &backing)
  {
    INST_deqCount.dump_VCD(dt, backing.INST_deqCount);
    INST_enqCount.dump_VCD(dt, backing.INST_enqCount);
    INST_f_data.dump_VCD(dt, backing.INST_f_data);
    INST_f_data_1.dump_VCD(dt, backing.INST_f_data_1);
    INST_f_data_2.dump_VCD(dt, backing.INST_f_data_2);
    INST_f_data_3.dump_VCD(dt, backing.INST_f_data_3);
    INST_f_deqEn_dummy.dump_VCD(dt, backing.INST_f_deqEn_dummy);
    INST_f_deqEn_dummy2.dump_VCD(dt, backing.INST_f_deqEn_dummy2);
    INST_f_deqEn_dummy2_1.dump_VCD(dt, backing.INST_f_deqEn_dummy2_1);
    INST_f_deqEn_dummy2_2.dump_VCD(dt, backing.INST_f_deqEn_dummy2_2);
    INST_f_deqEn_dummy_1.dump_VCD(dt, backing.INST_f_deqEn_dummy_1);
    INST_f_deqEn_dummy_2.dump_VCD(dt, backing.INST_f_deqEn_dummy_2);
    INST_f_deqEn_dummy_3.dump_VCD(dt, backing.INST_f_deqEn_dummy_3);
    INST_f_deqEn_dummy_4.dump_VCD(dt, backing.INST_f_deqEn_dummy_4);
    INST_f_deqEn_dummy_5.dump_VCD(dt, backing.INST_f_deqEn_dummy_5);
    INST_f_deqEn_dummy_6.dump_VCD(dt, backing.INST_f_deqEn_dummy_6);
    INST_f_deqEn_dummy_7.dump_VCD(dt, backing.INST_f_deqEn_dummy_7);
    INST_f_deqEn_dummy_8.dump_VCD(dt, backing.INST_f_deqEn_dummy_8);
    INST_f_deqEn_lat.dump_VCD(dt, backing.INST_f_deqEn_lat);
    INST_f_deqEn_lat_1.dump_VCD(dt, backing.INST_f_deqEn_lat_1);
    INST_f_deqEn_lat_2.dump_VCD(dt, backing.INST_f_deqEn_lat_2);
    INST_f_deqEn_rl.dump_VCD(dt, backing.INST_f_deqEn_rl);
    INST_f_deqP_dummy.dump_VCD(dt, backing.INST_f_deqP_dummy);
    INST_f_deqP_dummy2.dump_VCD(dt, backing.INST_f_deqP_dummy2);
    INST_f_deqP_dummy2_1.dump_VCD(dt, backing.INST_f_deqP_dummy2_1);
    INST_f_deqP_dummy2_2.dump_VCD(dt, backing.INST_f_deqP_dummy2_2);
    INST_f_deqP_dummy_1.dump_VCD(dt, backing.INST_f_deqP_dummy_1);
    INST_f_deqP_dummy_2.dump_VCD(dt, backing.INST_f_deqP_dummy_2);
    INST_f_deqP_dummy_3.dump_VCD(dt, backing.INST_f_deqP_dummy_3);
    INST_f_deqP_dummy_4.dump_VCD(dt, backing.INST_f_deqP_dummy_4);
    INST_f_deqP_dummy_5.dump_VCD(dt, backing.INST_f_deqP_dummy_5);
    INST_f_deqP_dummy_6.dump_VCD(dt, backing.INST_f_deqP_dummy_6);
    INST_f_deqP_dummy_7.dump_VCD(dt, backing.INST_f_deqP_dummy_7);
    INST_f_deqP_dummy_8.dump_VCD(dt, backing.INST_f_deqP_dummy_8);
    INST_f_deqP_lat.dump_VCD(dt, backing.INST_f_deqP_lat);
    INST_f_deqP_lat_1.dump_VCD(dt, backing.INST_f_deqP_lat_1);
    INST_f_deqP_lat_2.dump_VCD(dt, backing.INST_f_deqP_lat_2);
    INST_f_deqP_rl.dump_VCD(dt, backing.INST_f_deqP_rl);
    INST_f_enqEn_dummy.dump_VCD(dt, backing.INST_f_enqEn_dummy);
    INST_f_enqEn_dummy2.dump_VCD(dt, backing.INST_f_enqEn_dummy2);
    INST_f_enqEn_dummy2_1.dump_VCD(dt, backing.INST_f_enqEn_dummy2_1);
    INST_f_enqEn_dummy2_2.dump_VCD(dt, backing.INST_f_enqEn_dummy2_2);
    INST_f_enqEn_dummy_1.dump_VCD(dt, backing.INST_f_enqEn_dummy_1);
    INST_f_enqEn_dummy_2.dump_VCD(dt, backing.INST_f_enqEn_dummy_2);
    INST_f_enqEn_dummy_3.dump_VCD(dt, backing.INST_f_enqEn_dummy_3);
    INST_f_enqEn_dummy_4.dump_VCD(dt, backing.INST_f_enqEn_dummy_4);
    INST_f_enqEn_dummy_5.dump_VCD(dt, backing.INST_f_enqEn_dummy_5);
    INST_f_enqEn_dummy_6.dump_VCD(dt, backing.INST_f_enqEn_dummy_6);
    INST_f_enqEn_dummy_7.dump_VCD(dt, backing.INST_f_enqEn_dummy_7);
    INST_f_enqEn_dummy_8.dump_VCD(dt, backing.INST_f_enqEn_dummy_8);
    INST_f_enqEn_lat.dump_VCD(dt, backing.INST_f_enqEn_lat);
    INST_f_enqEn_lat_1.dump_VCD(dt, backing.INST_f_enqEn_lat_1);
    INST_f_enqEn_lat_2.dump_VCD(dt, backing.INST_f_enqEn_lat_2);
    INST_f_enqEn_rl.dump_VCD(dt, backing.INST_f_enqEn_rl);
    INST_f_enqP_dummy.dump_VCD(dt, backing.INST_f_enqP_dummy);
    INST_f_enqP_dummy2.dump_VCD(dt, backing.INST_f_enqP_dummy2);
    INST_f_enqP_dummy2_1.dump_VCD(dt, backing.INST_f_enqP_dummy2_1);
    INST_f_enqP_dummy2_2.dump_VCD(dt, backing.INST_f_enqP_dummy2_2);
    INST_f_enqP_dummy_1.dump_VCD(dt, backing.INST_f_enqP_dummy_1);
    INST_f_enqP_dummy_2.dump_VCD(dt, backing.INST_f_enqP_dummy_2);
    INST_f_enqP_dummy_3.dump_VCD(dt, backing.INST_f_enqP_dummy_3);
    INST_f_enqP_dummy_4.dump_VCD(dt, backing.INST_f_enqP_dummy_4);
    INST_f_enqP_dummy_5.dump_VCD(dt, backing.INST_f_enqP_dummy_5);
    INST_f_enqP_dummy_6.dump_VCD(dt, backing.INST_f_enqP_dummy_6);
    INST_f_enqP_dummy_7.dump_VCD(dt, backing.INST_f_enqP_dummy_7);
    INST_f_enqP_dummy_8.dump_VCD(dt, backing.INST_f_enqP_dummy_8);
    INST_f_enqP_lat.dump_VCD(dt, backing.INST_f_enqP_lat);
    INST_f_enqP_lat_1.dump_VCD(dt, backing.INST_f_enqP_lat_1);
    INST_f_enqP_lat_2.dump_VCD(dt, backing.INST_f_enqP_lat_2);
    INST_f_enqP_rl.dump_VCD(dt, backing.INST_f_enqP_rl);
    INST_f_tempData_dummy.dump_VCD(dt, backing.INST_f_tempData_dummy);
    INST_f_tempData_dummy2.dump_VCD(dt, backing.INST_f_tempData_dummy2);
    INST_f_tempData_dummy2_1.dump_VCD(dt, backing.INST_f_tempData_dummy2_1);
    INST_f_tempData_dummy_1.dump_VCD(dt, backing.INST_f_tempData_dummy_1);
    INST_f_tempData_dummy_2.dump_VCD(dt, backing.INST_f_tempData_dummy_2);
    INST_f_tempData_dummy_3.dump_VCD(dt, backing.INST_f_tempData_dummy_3);
    INST_f_tempData_lat.dump_VCD(dt, backing.INST_f_tempData_lat);
    INST_f_tempData_lat_1.dump_VCD(dt, backing.INST_f_tempData_lat_1);
    INST_f_tempData_rl.dump_VCD(dt, backing.INST_f_tempData_rl);
    INST_f_tempEnqP_dummy.dump_VCD(dt, backing.INST_f_tempEnqP_dummy);
    INST_f_tempEnqP_dummy2.dump_VCD(dt, backing.INST_f_tempEnqP_dummy2);
    INST_f_tempEnqP_dummy2_1.dump_VCD(dt, backing.INST_f_tempEnqP_dummy2_1);
    INST_f_tempEnqP_dummy_1.dump_VCD(dt, backing.INST_f_tempEnqP_dummy_1);
    INST_f_tempEnqP_dummy_2.dump_VCD(dt, backing.INST_f_tempEnqP_dummy_2);
    INST_f_tempEnqP_dummy_3.dump_VCD(dt, backing.INST_f_tempEnqP_dummy_3);
    INST_f_tempEnqP_lat.dump_VCD(dt, backing.INST_f_tempEnqP_lat);
    INST_f_tempEnqP_lat_1.dump_VCD(dt, backing.INST_f_tempEnqP_lat_1);
    INST_f_tempEnqP_rl.dump_VCD(dt, backing.INST_f_tempEnqP_rl);
    INST_mult_a.dump_VCD(dt, backing.INST_mult_a);
    INST_mult_asign.dump_VCD(dt, backing.INST_mult_asign);
    INST_mult_b.dump_VCD(dt, backing.INST_mult_b);
    INST_mult_bsign.dump_VCD(dt, backing.INST_mult_bsign);
    INST_mult_i.dump_VCD(dt, backing.INST_mult_i);
    INST_mult_mul_a.dump_VCD(dt, backing.INST_mult_mul_a);
    INST_mult_mul_b.dump_VCD(dt, backing.INST_mult_mul_b);
    INST_mult_mul_i.dump_VCD(dt, backing.INST_mult_mul_i);
    INST_mult_mul_prod.dump_VCD(dt, backing.INST_mult_mul_prod);
    INST_mult_mul_tp.dump_VCD(dt, backing.INST_mult_mul_tp);
    INST_mult_res.dump_VCD(dt, backing.INST_mult_res);
    INST_randomVal1_init.dump_VCD(dt, backing.INST_randomVal1_init);
    INST_randomVal2_init.dump_VCD(dt, backing.INST_randomVal2_init);
  }
}
