/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sun Jan 26 12:10:16 IST 2014
 * 
 */
extern "C" {
  unsigned int getRandom();
  void setSeed(unsigned int );
}
