/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sat Jan 25 18:07:59 IST 2014
 * 
 */
extern "C" {
  unsigned int getRandom();
  void setSeed(unsigned int );
}
