/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sat Jan 25 18:07:59 IST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbRightLogical.h"
#include "imported_BDPI_functions.h"

namespace bluesim
{
  
  /* String declarations */
  static std::string const __str_literal_2("FAILED Logical Shift %b >> %d gave %b instead of %b",
					   51u);
  static std::string const __str_literal_1("PASSED", 6u);
  
  
  /* Constructor */
  MOD_mkTbRightLogical::MOD_mkTbRightLogical(char const *name, Module *parent)
    : Module(name, parent),
      __clk_handle_0(BAD_CLOCK_HANDLE),
      INST_cycle("cycle", this, 32u, 0u, (tUInt8)0u),
      INST_randomShift_init("randomShift_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      INST_randomVal_init("randomVal_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      PORT_RST_N((tUInt8)1u),
      DEF_TASK_getRandom___d496(2863311530u),
      DEF_TASK_getRandom___d495(2863311530u)
  {
    symbol_count = 7u;
    symbols = new tSym[symbol_count];
    init_symbols_0();
  }
  
  
  /* Symbol init fns */
  
  void MOD_mkTbRightLogical::init_symbols_0()
  {
    init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
    init_symbol(&symbols[1u], "RL_randomShift_initialize", SYM_RULE);
    init_symbol(&symbols[2u], "RL_randomVal_initialize", SYM_RULE);
    init_symbol(&symbols[3u], "RL_test", SYM_RULE);
    init_symbol(&symbols[4u], "randomShift_init", SYM_MODULE, &INST_randomShift_init);
    init_symbol(&symbols[5u], "randomVal_init", SYM_MODULE, &INST_randomVal_init);
    init_symbol(&symbols[6u], "x__h370", SYM_DEF, &DEF_x__h370, 32u);
  }
  
  
  /* Rule actions */
  
  void MOD_mkTbRightLogical::RL_randomVal_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3735928559u);
    INST_randomVal_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkTbRightLogical::RL_randomShift_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3405691582u);
    INST_randomShift_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkTbRightLogical::RL_test()
  {
    tUInt32 DEF_x__h15089;
    tUInt8 DEF_b__h7156;
    tUInt8 DEF_a__h9039;
    tUInt8 DEF_b__h9214;
    tUInt8 DEF_a__h11033;
    tUInt8 DEF_b__h11440;
    tUInt8 DEF_a__h11091;
    tUInt8 DEF_a__h11149;
    tUInt8 DEF_b__h14002;
    tUInt8 DEF_a__h1712;
    tUInt8 DEF_b__h5184;
    tUInt8 DEF_a__h5183;
    tUInt8 DEF_a__h7097;
    tUInt8 DEF_b__h5242;
    tUInt8 DEF_a__h5241;
    tUInt8 DEF_a__h7155;
    tUInt8 DEF_b__h7158;
    tUInt8 DEF_a__h7157;
    tUInt8 DEF_a__h9097;
    tUInt8 DEF_b__h5300;
    tUInt8 DEF_a__h5299;
    tUInt8 DEF_a__h7213;
    tUInt8 DEF_b__h7216;
    tUInt8 DEF_a__h7215;
    tUInt8 DEF_a__h9155;
    tUInt8 DEF_b__h5358;
    tUInt8 DEF_a__h5357;
    tUInt8 DEF_a__h7271;
    tUInt8 DEF_b__h7274;
    tUInt8 DEF_a__h7273;
    tUInt8 DEF_a__h9213;
    tUInt8 DEF_b__h9216;
    tUInt8 DEF_a__h9215;
    tUInt8 DEF_a__h11207;
    tUInt8 DEF_b__h5416;
    tUInt8 DEF_a__h5415;
    tUInt8 DEF_a__h7329;
    tUInt8 DEF_b__h7332;
    tUInt8 DEF_a__h7331;
    tUInt8 DEF_a__h9271;
    tUInt8 DEF_b__h9274;
    tUInt8 DEF_a__h9273;
    tUInt8 DEF_a__h11265;
    tUInt8 DEF_b__h5474;
    tUInt8 DEF_a__h5473;
    tUInt8 DEF_a__h7387;
    tUInt8 DEF_b__h7390;
    tUInt8 DEF_a__h7389;
    tUInt8 DEF_a__h9329;
    tUInt8 DEF_b__h9332;
    tUInt8 DEF_a__h9331;
    tUInt8 DEF_a__h11323;
    tUInt8 DEF_b__h5532;
    tUInt8 DEF_a__h5531;
    tUInt8 DEF_a__h7445;
    tUInt8 DEF_b__h7448;
    tUInt8 DEF_a__h7447;
    tUInt8 DEF_a__h9387;
    tUInt8 DEF_b__h9390;
    tUInt8 DEF_a__h9389;
    tUInt8 DEF_a__h11381;
    tUInt8 DEF_b__h5590;
    tUInt8 DEF_a__h5589;
    tUInt8 DEF_a__h7503;
    tUInt8 DEF_b__h7506;
    tUInt8 DEF_a__h7505;
    tUInt8 DEF_a__h9445;
    tUInt8 DEF_b__h9448;
    tUInt8 DEF_a__h9447;
    tUInt8 DEF_a__h11439;
    tUInt8 DEF_b__h11442;
    tUInt8 DEF_a__h11441;
    tUInt8 DEF_b__h5648;
    tUInt8 DEF_a__h5647;
    tUInt8 DEF_a__h7561;
    tUInt8 DEF_b__h7564;
    tUInt8 DEF_a__h7563;
    tUInt8 DEF_a__h9503;
    tUInt8 DEF_b__h9506;
    tUInt8 DEF_a__h9505;
    tUInt8 DEF_a__h11497;
    tUInt8 DEF_b__h11500;
    tUInt8 DEF_a__h11499;
    tUInt8 DEF_b__h5706;
    tUInt8 DEF_a__h5705;
    tUInt8 DEF_a__h7619;
    tUInt8 DEF_b__h7622;
    tUInt8 DEF_a__h7621;
    tUInt8 DEF_a__h9561;
    tUInt8 DEF_b__h9564;
    tUInt8 DEF_a__h9563;
    tUInt8 DEF_a__h11555;
    tUInt8 DEF_b__h11558;
    tUInt8 DEF_a__h11557;
    tUInt8 DEF_b__h5764;
    tUInt8 DEF_a__h5763;
    tUInt8 DEF_a__h7677;
    tUInt8 DEF_b__h7680;
    tUInt8 DEF_a__h7679;
    tUInt8 DEF_a__h9619;
    tUInt8 DEF_b__h9622;
    tUInt8 DEF_a__h9621;
    tUInt8 DEF_a__h11613;
    tUInt8 DEF_b__h11616;
    tUInt8 DEF_a__h11615;
    tUInt8 DEF_b__h5822;
    tUInt8 DEF_a__h5821;
    tUInt8 DEF_a__h7735;
    tUInt8 DEF_b__h7738;
    tUInt8 DEF_a__h7737;
    tUInt8 DEF_a__h9677;
    tUInt8 DEF_b__h9680;
    tUInt8 DEF_a__h9679;
    tUInt8 DEF_a__h11671;
    tUInt8 DEF_b__h11674;
    tUInt8 DEF_a__h11673;
    tUInt8 DEF_b__h5880;
    tUInt8 DEF_a__h5879;
    tUInt8 DEF_a__h7793;
    tUInt8 DEF_b__h7796;
    tUInt8 DEF_a__h7795;
    tUInt8 DEF_a__h9735;
    tUInt8 DEF_b__h9738;
    tUInt8 DEF_a__h9737;
    tUInt8 DEF_a__h11729;
    tUInt8 DEF_b__h11732;
    tUInt8 DEF_a__h11731;
    tUInt8 DEF_b__h5938;
    tUInt8 DEF_a__h5937;
    tUInt8 DEF_a__h7851;
    tUInt8 DEF_b__h7854;
    tUInt8 DEF_a__h7853;
    tUInt8 DEF_a__h9793;
    tUInt8 DEF_b__h9796;
    tUInt8 DEF_a__h9795;
    tUInt8 DEF_a__h11787;
    tUInt8 DEF_b__h11790;
    tUInt8 DEF_a__h11789;
    tUInt8 DEF_b__h5996;
    tUInt8 DEF_a__h5995;
    tUInt8 DEF_a__h7909;
    tUInt8 DEF_b__h7912;
    tUInt8 DEF_a__h7911;
    tUInt8 DEF_a__h9851;
    tUInt8 DEF_b__h9854;
    tUInt8 DEF_a__h9853;
    tUInt8 DEF_a__h11845;
    tUInt8 DEF_b__h11848;
    tUInt8 DEF_a__h11847;
    tUInt8 DEF_b__h6054;
    tUInt8 DEF_a__h6053;
    tUInt8 DEF_a__h7967;
    tUInt8 DEF_b__h7970;
    tUInt8 DEF_a__h7969;
    tUInt8 DEF_a__h9909;
    tUInt8 DEF_b__h9912;
    tUInt8 DEF_a__h9911;
    tUInt8 DEF_a__h11903;
    tUInt8 DEF_b__h11906;
    tUInt8 DEF_a__h11905;
    tUInt8 DEF_b__h6112;
    tUInt8 DEF_a__h6111;
    tUInt8 DEF_a__h8025;
    tUInt8 DEF_b__h8028;
    tUInt8 DEF_a__h8027;
    tUInt8 DEF_a__h9967;
    tUInt8 DEF_b__h9970;
    tUInt8 DEF_a__h9969;
    tUInt8 DEF_a__h11961;
    tUInt8 DEF_b__h11964;
    tUInt8 DEF_a__h11963;
    tUInt8 DEF_b__h6170;
    tUInt8 DEF_a__h6169;
    tUInt8 DEF_a__h8083;
    tUInt8 DEF_b__h8086;
    tUInt8 DEF_a__h8085;
    tUInt8 DEF_a__h10025;
    tUInt8 DEF_b__h10028;
    tUInt8 DEF_a__h10027;
    tUInt8 DEF_a__h12019;
    tUInt8 DEF_b__h12022;
    tUInt8 DEF_a__h12021;
    tUInt8 DEF_b__h6228;
    tUInt8 DEF_a__h6227;
    tUInt8 DEF_a__h8141;
    tUInt8 DEF_b__h8144;
    tUInt8 DEF_a__h8143;
    tUInt8 DEF_a__h10083;
    tUInt8 DEF_b__h10086;
    tUInt8 DEF_a__h10085;
    tUInt8 DEF_a__h12077;
    tUInt8 DEF_b__h12080;
    tUInt8 DEF_a__h12079;
    tUInt8 DEF_b__h6286;
    tUInt8 DEF_a__h6285;
    tUInt8 DEF_a__h8199;
    tUInt8 DEF_b__h8202;
    tUInt8 DEF_a__h8201;
    tUInt8 DEF_a__h10141;
    tUInt8 DEF_b__h10144;
    tUInt8 DEF_a__h10143;
    tUInt8 DEF_a__h12135;
    tUInt8 DEF_b__h12138;
    tUInt8 DEF_a__h12137;
    tUInt8 DEF_b__h6344;
    tUInt8 DEF_a__h6343;
    tUInt8 DEF_a__h8257;
    tUInt8 DEF_b__h8260;
    tUInt8 DEF_a__h8259;
    tUInt8 DEF_a__h10199;
    tUInt8 DEF_b__h10202;
    tUInt8 DEF_a__h10201;
    tUInt8 DEF_a__h12193;
    tUInt8 DEF_b__h12196;
    tUInt8 DEF_a__h12195;
    tUInt8 DEF_b__h6402;
    tUInt8 DEF_a__h6401;
    tUInt8 DEF_a__h8315;
    tUInt8 DEF_b__h8318;
    tUInt8 DEF_a__h8317;
    tUInt8 DEF_a__h10257;
    tUInt8 DEF_b__h10260;
    tUInt8 DEF_a__h10259;
    tUInt8 DEF_a__h12251;
    tUInt8 DEF_b__h12254;
    tUInt8 DEF_a__h12253;
    tUInt8 DEF_b__h6460;
    tUInt8 DEF_a__h6459;
    tUInt8 DEF_a__h8373;
    tUInt8 DEF_b__h8376;
    tUInt8 DEF_a__h8375;
    tUInt8 DEF_a__h10315;
    tUInt8 DEF_b__h10318;
    tUInt8 DEF_a__h10317;
    tUInt8 DEF_a__h12309;
    tUInt8 DEF_b__h12312;
    tUInt8 DEF_a__h12311;
    tUInt8 DEF_b__h6518;
    tUInt8 DEF_a__h6517;
    tUInt8 DEF_a__h8431;
    tUInt8 DEF_b__h8434;
    tUInt8 DEF_a__h8433;
    tUInt8 DEF_a__h10373;
    tUInt8 DEF_b__h10376;
    tUInt8 DEF_a__h10375;
    tUInt8 DEF_a__h12367;
    tUInt8 DEF_b__h12370;
    tUInt8 DEF_a__h12369;
    tUInt8 DEF_b__h6576;
    tUInt8 DEF_a__h6575;
    tUInt8 DEF_a__h8489;
    tUInt8 DEF_b__h8492;
    tUInt8 DEF_a__h8491;
    tUInt8 DEF_a__h10431;
    tUInt8 DEF_b__h10434;
    tUInt8 DEF_a__h10433;
    tUInt8 DEF_a__h12425;
    tUInt8 DEF_b__h12428;
    tUInt8 DEF_a__h12427;
    tUInt8 DEF_b__h6634;
    tUInt8 DEF_a__h6633;
    tUInt8 DEF_a__h8547;
    tUInt8 DEF_b__h8550;
    tUInt8 DEF_a__h8549;
    tUInt8 DEF_a__h10489;
    tUInt8 DEF_b__h10492;
    tUInt8 DEF_a__h10491;
    tUInt8 DEF_a__h12483;
    tUInt8 DEF_b__h12486;
    tUInt8 DEF_a__h12485;
    tUInt8 DEF_b__h6692;
    tUInt8 DEF_a__h6691;
    tUInt8 DEF_a__h8605;
    tUInt8 DEF_b__h8608;
    tUInt8 DEF_a__h8607;
    tUInt8 DEF_a__h10547;
    tUInt8 DEF_b__h10550;
    tUInt8 DEF_a__h10549;
    tUInt8 DEF_a__h12541;
    tUInt8 DEF_b__h12544;
    tUInt8 DEF_a__h12543;
    tUInt8 DEF_b__h6750;
    tUInt8 DEF_a__h6749;
    tUInt8 DEF_a__h8663;
    tUInt8 DEF_b__h8666;
    tUInt8 DEF_a__h8665;
    tUInt8 DEF_a__h10605;
    tUInt8 DEF_b__h10608;
    tUInt8 DEF_a__h10607;
    tUInt8 DEF_a__h12599;
    tUInt8 DEF_b__h12602;
    tUInt8 DEF_a__h12601;
    tUInt8 DEF_b__h6808;
    tUInt8 DEF_a__h6807;
    tUInt8 DEF_a__h8721;
    tUInt8 DEF_b__h8724;
    tUInt8 DEF_a__h8723;
    tUInt8 DEF_a__h10663;
    tUInt8 DEF_b__h10666;
    tUInt8 DEF_a__h10665;
    tUInt8 DEF_a__h12657;
    tUInt8 DEF_b__h12660;
    tUInt8 DEF_a__h12659;
    tUInt8 DEF_b__h6866;
    tUInt8 DEF_a__h6865;
    tUInt8 DEF_a__h8779;
    tUInt8 DEF_b__h8782;
    tUInt8 DEF_a__h8781;
    tUInt8 DEF_a__h10721;
    tUInt8 DEF_b__h10724;
    tUInt8 DEF_a__h10723;
    tUInt8 DEF_a__h12715;
    tUInt8 DEF_b__h12718;
    tUInt8 DEF_a__h12717;
    tUInt8 DEF_b__h6924;
    tUInt8 DEF_a__h6923;
    tUInt8 DEF_a__h8837;
    tUInt8 DEF_b__h8840;
    tUInt8 DEF_a__h8839;
    tUInt8 DEF_a__h10779;
    tUInt8 DEF_b__h10782;
    tUInt8 DEF_a__h10781;
    tUInt8 DEF_a__h12773;
    tUInt8 DEF_b__h12776;
    tUInt8 DEF_a__h12775;
    tUInt32 DEF_trueResultL__h1695;
    tUInt8 DEF_a__h2556;
    tUInt8 DEF_a__h1714;
    tUInt8 DEF_a__h3398;
    tUInt8 DEF_a__h4240;
    tUInt8 DEF_a__h5082;
    tUInt8 DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d493;
    tUInt32 DEF_x__h1708;
    tUInt8 DEF_sel__h4297;
    tUInt8 DEF_sel__h3455;
    tUInt8 DEF_sel__h2613;
    tUInt8 DEF_sel__h1771;
    tUInt8 DEF_a__h6921;
    tUInt8 DEF_a__h6863;
    tUInt8 DEF_a__h6805;
    tUInt8 DEF_a__h6747;
    tUInt8 DEF_a__h6689;
    tUInt8 DEF_a__h6631;
    tUInt8 DEF_a__h6573;
    tUInt8 DEF_a__h6515;
    tUInt8 DEF_a__h6457;
    tUInt8 DEF_a__h6399;
    tUInt8 DEF_a__h6341;
    tUInt8 DEF_a__h6283;
    tUInt8 DEF_a__h6225;
    tUInt8 DEF_a__h6167;
    tUInt8 DEF_a__h6109;
    tUInt8 DEF_a__h6051;
    tUInt8 DEF_a__h5993;
    tUInt8 DEF_a__h5935;
    tUInt8 DEF_a__h5877;
    tUInt8 DEF_a__h5819;
    tUInt8 DEF_a__h5761;
    tUInt8 DEF_a__h5703;
    tUInt8 DEF_a__h5645;
    tUInt8 DEF_a__h5587;
    tUInt8 DEF_a__h5529;
    tUInt8 DEF_a__h5471;
    tUInt8 DEF_a__h5413;
    tUInt8 DEF_a__h5355;
    tUInt8 DEF_a__h5297;
    tUInt8 DEF_a__h5239;
    tUInt8 DEF_a__h5181;
    tUInt8 DEF_a__h5078;
    tUInt8 DEF_TASK_getRandom_0_BITS_4_TO_0___d497;
    tUInt8 DEF_a__h13595;
    tUInt8 DEF_a__h13711;
    tUInt8 DEF_a__h13597;
    tUInt8 DEF_b__h14758;
    tUInt8 DEF_a__h14757;
    tUInt8 DEF_a__h13131;
    tUInt8 DEF_a__h13133;
    tUInt8 DEF_a__h13189;
    tUInt8 DEF_a__h13191;
    tUInt8 DEF_a__h13247;
    tUInt8 DEF_a__h13249;
    tUInt8 DEF_a__h13305;
    tUInt8 DEF_a__h13307;
    tUInt8 DEF_a__h13363;
    tUInt8 DEF_a__h13365;
    tUInt8 DEF_a__h13421;
    tUInt8 DEF_a__h13423;
    tUInt8 DEF_a__h13479;
    tUInt8 DEF_a__h13481;
    tUInt8 DEF_a__h13537;
    tUInt8 DEF_a__h13539;
    tUInt8 DEF_a__h13653;
    tUInt8 DEF_a__h13655;
    tUInt8 DEF_a__h13713;
    tUInt8 DEF_a__h13769;
    tUInt8 DEF_a__h13771;
    tUInt8 DEF_a__h13827;
    tUInt8 DEF_a__h13829;
    tUInt8 DEF_a__h13885;
    tUInt8 DEF_a__h13887;
    tUInt8 DEF_a__h13943;
    tUInt8 DEF_a__h13945;
    tUInt8 DEF_a__h14001;
    tUInt8 DEF_b__h14004;
    tUInt8 DEF_a__h14003;
    tUInt8 DEF_a__h14059;
    tUInt8 DEF_b__h14062;
    tUInt8 DEF_a__h14061;
    tUInt8 DEF_a__h14117;
    tUInt8 DEF_b__h14120;
    tUInt8 DEF_a__h14119;
    tUInt8 DEF_a__h14175;
    tUInt8 DEF_b__h14178;
    tUInt8 DEF_a__h14177;
    tUInt8 DEF_a__h14233;
    tUInt8 DEF_b__h14236;
    tUInt8 DEF_a__h14235;
    tUInt8 DEF_a__h14291;
    tUInt8 DEF_b__h14294;
    tUInt8 DEF_a__h14293;
    tUInt8 DEF_a__h14349;
    tUInt8 DEF_b__h14352;
    tUInt8 DEF_a__h14351;
    tUInt8 DEF_a__h14407;
    tUInt8 DEF_b__h14410;
    tUInt8 DEF_a__h14409;
    tUInt8 DEF_a__h14465;
    tUInt8 DEF_b__h14468;
    tUInt8 DEF_a__h14467;
    tUInt8 DEF_a__h14523;
    tUInt8 DEF_b__h14526;
    tUInt8 DEF_a__h14525;
    tUInt8 DEF_a__h14581;
    tUInt8 DEF_b__h14584;
    tUInt8 DEF_a__h14583;
    tUInt8 DEF_a__h14639;
    tUInt8 DEF_b__h14642;
    tUInt8 DEF_a__h14641;
    tUInt8 DEF_a__h14697;
    tUInt8 DEF_b__h14700;
    tUInt8 DEF_a__h14699;
    tUInt8 DEF_a__h14755;
    tUInt8 DEF_a__h14813;
    tUInt8 DEF_b__h14816;
    tUInt8 DEF_a__h14815;
    tUInt8 DEF_a__h14871;
    tUInt8 DEF_b__h14874;
    tUInt8 DEF_a__h14873;
    tUInt32 DEF_v__h834;
    tUInt8 DEF_NOT_cycle_EQ_128___d9;
    tUInt8 DEF_sel__h905;
    DEF_x__h370 = INST_cycle.METH_read();
    DEF_cycle_EQ_128___d6 = DEF_x__h370 == 128u;
    DEF_NOT_cycle_EQ_128___d9 = !DEF_cycle_EQ_128___d6;
    DEF_x__h15089 = DEF_x__h370 + 1u;
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      if (DEF_cycle_EQ_128___d6)
	dollar_display(this, "s", &__str_literal_1);
      if (DEF_cycle_EQ_128___d6)
	dollar_finish("32", 1u);
      if (DEF_NOT_cycle_EQ_128___d9)
	DEF_TASK_getRandom___d495 = getRandom();
    }
    DEF_a__h5078 = (tUInt8)(DEF_TASK_getRandom___d495 >> 31u);
    DEF_a__h5181 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 30u));
    DEF_a__h5239 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 29u));
    DEF_a__h5297 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 28u));
    DEF_a__h5355 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 27u));
    DEF_a__h5413 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 26u));
    DEF_a__h5471 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 25u));
    DEF_a__h5529 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 24u));
    DEF_a__h5587 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 23u));
    DEF_a__h5645 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 22u));
    DEF_a__h5703 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 21u));
    DEF_a__h5761 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 20u));
    DEF_a__h5819 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 19u));
    DEF_a__h5877 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 18u));
    DEF_a__h5993 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 16u));
    DEF_a__h5935 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 17u));
    DEF_a__h6051 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 15u));
    DEF_a__h6109 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 14u));
    DEF_a__h6167 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 13u));
    DEF_a__h6225 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 12u));
    DEF_a__h6283 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 11u));
    DEF_a__h6399 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 9u));
    DEF_a__h6341 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 10u));
    DEF_a__h6457 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 8u));
    DEF_a__h6515 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 7u));
    DEF_a__h6573 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 6u));
    DEF_a__h6631 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 5u));
    DEF_a__h6689 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 4u));
    DEF_a__h6805 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 2u));
    DEF_a__h6747 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 3u));
    DEF_a__h6863 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d495 >> 1u));
    DEF_a__h6921 = (tUInt8)((tUInt8)1u & DEF_TASK_getRandom___d495);
    if (!(PORT_RST_N == (tUInt8)0u))
      if (DEF_NOT_cycle_EQ_128___d9)
	DEF_TASK_getRandom___d496 = getRandom();
    DEF_sel__h905 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d496 >> 4u));
    DEF_TASK_getRandom_0_BITS_4_TO_0___d497 = (tUInt8)((tUInt8)31u & DEF_TASK_getRandom___d496);
    DEF_sel__h1771 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d496 >> 3u));
    DEF_sel__h2613 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d496 >> 2u));
    DEF_sel__h3455 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d496 >> 1u));
    DEF_sel__h4297 = (tUInt8)((tUInt8)1u & DEF_TASK_getRandom___d496);
    DEF_a__h5082 = (tUInt8)1u & ~DEF_sel__h4297;
    DEF_a__h4240 = (tUInt8)1u & ~DEF_sel__h3455;
    DEF_a__h3398 = (tUInt8)1u & ~DEF_sel__h2613;
    DEF_a__h1714 = (tUInt8)1u & ~DEF_sel__h905;
    DEF_a__h2556 = (tUInt8)1u & ~DEF_sel__h1771;
    DEF_trueResultL__h1695 = primShiftR32(32u,
					  32u,
					  (tUInt32)(DEF_TASK_getRandom___d495),
					  5u,
					  (tUInt8)(DEF_TASK_getRandom_0_BITS_4_TO_0___d497));
    DEF_a__h6923 = DEF_a__h5082 & DEF_a__h6921;
    DEF_b__h6924 = DEF_sel__h4297 & DEF_a__h6863;
    DEF_a__h8837 = DEF_a__h6923 | DEF_b__h6924;
    DEF_a__h8839 = DEF_a__h4240 & DEF_a__h8837;
    DEF_a__h6865 = DEF_a__h5082 & DEF_a__h6863;
    DEF_b__h6866 = DEF_sel__h4297 & DEF_a__h6805;
    DEF_a__h8779 = DEF_a__h6865 | DEF_b__h6866;
    DEF_a__h8781 = DEF_a__h4240 & DEF_a__h8779;
    DEF_a__h6807 = DEF_a__h5082 & DEF_a__h6805;
    DEF_b__h6808 = DEF_sel__h4297 & DEF_a__h6747;
    DEF_a__h8721 = DEF_a__h6807 | DEF_b__h6808;
    DEF_b__h8840 = DEF_sel__h3455 & DEF_a__h8721;
    DEF_a__h10779 = DEF_a__h8839 | DEF_b__h8840;
    DEF_a__h10781 = DEF_a__h3398 & DEF_a__h10779;
    DEF_a__h8723 = DEF_a__h4240 & DEF_a__h8721;
    DEF_a__h6749 = DEF_a__h5082 & DEF_a__h6747;
    DEF_b__h6750 = DEF_sel__h4297 & DEF_a__h6689;
    DEF_a__h8663 = DEF_a__h6749 | DEF_b__h6750;
    DEF_b__h8782 = DEF_sel__h3455 & DEF_a__h8663;
    DEF_a__h10721 = DEF_a__h8781 | DEF_b__h8782;
    DEF_a__h10723 = DEF_a__h3398 & DEF_a__h10721;
    DEF_a__h8665 = DEF_a__h4240 & DEF_a__h8663;
    DEF_a__h6691 = DEF_a__h5082 & DEF_a__h6689;
    DEF_b__h6692 = DEF_sel__h4297 & DEF_a__h6631;
    DEF_a__h8605 = DEF_a__h6691 | DEF_b__h6692;
    DEF_b__h8724 = DEF_sel__h3455 & DEF_a__h8605;
    DEF_a__h10663 = DEF_a__h8723 | DEF_b__h8724;
    DEF_a__h10665 = DEF_a__h3398 & DEF_a__h10663;
    DEF_a__h8607 = DEF_a__h4240 & DEF_a__h8605;
    DEF_a__h6575 = DEF_a__h5082 & DEF_a__h6573;
    DEF_a__h6633 = DEF_a__h5082 & DEF_a__h6631;
    DEF_b__h6634 = DEF_sel__h4297 & DEF_a__h6573;
    DEF_a__h8547 = DEF_a__h6633 | DEF_b__h6634;
    DEF_b__h8666 = DEF_sel__h3455 & DEF_a__h8547;
    DEF_a__h10605 = DEF_a__h8665 | DEF_b__h8666;
    DEF_a__h10607 = DEF_a__h3398 & DEF_a__h10605;
    DEF_a__h8549 = DEF_a__h4240 & DEF_a__h8547;
    DEF_b__h6576 = DEF_sel__h4297 & DEF_a__h6515;
    DEF_a__h8489 = DEF_a__h6575 | DEF_b__h6576;
    DEF_b__h8608 = DEF_sel__h3455 & DEF_a__h8489;
    DEF_a__h10547 = DEF_a__h8607 | DEF_b__h8608;
    DEF_b__h10782 = DEF_sel__h2613 & DEF_a__h10547;
    DEF_a__h12773 = DEF_a__h10781 | DEF_b__h10782;
    DEF_a__h12775 = DEF_a__h2556 & DEF_a__h12773;
    DEF_a__h10549 = DEF_a__h3398 & DEF_a__h10547;
    DEF_a__h8491 = DEF_a__h4240 & DEF_a__h8489;
    DEF_a__h6517 = DEF_a__h5082 & DEF_a__h6515;
    DEF_b__h6518 = DEF_sel__h4297 & DEF_a__h6457;
    DEF_a__h8431 = DEF_a__h6517 | DEF_b__h6518;
    DEF_b__h8550 = DEF_sel__h3455 & DEF_a__h8431;
    DEF_a__h10489 = DEF_a__h8549 | DEF_b__h8550;
    DEF_b__h10724 = DEF_sel__h2613 & DEF_a__h10489;
    DEF_a__h12715 = DEF_a__h10723 | DEF_b__h10724;
    DEF_a__h12717 = DEF_a__h2556 & DEF_a__h12715;
    DEF_a__h10491 = DEF_a__h3398 & DEF_a__h10489;
    DEF_a__h8433 = DEF_a__h4240 & DEF_a__h8431;
    DEF_a__h6459 = DEF_a__h5082 & DEF_a__h6457;
    DEF_b__h6460 = DEF_sel__h4297 & DEF_a__h6399;
    DEF_a__h8373 = DEF_a__h6459 | DEF_b__h6460;
    DEF_b__h8492 = DEF_sel__h3455 & DEF_a__h8373;
    DEF_a__h10431 = DEF_a__h8491 | DEF_b__h8492;
    DEF_b__h10666 = DEF_sel__h2613 & DEF_a__h10431;
    DEF_a__h12657 = DEF_a__h10665 | DEF_b__h10666;
    DEF_a__h12659 = DEF_a__h2556 & DEF_a__h12657;
    DEF_a__h10433 = DEF_a__h3398 & DEF_a__h10431;
    DEF_a__h8375 = DEF_a__h4240 & DEF_a__h8373;
    DEF_a__h6401 = DEF_a__h5082 & DEF_a__h6399;
    DEF_b__h6402 = DEF_sel__h4297 & DEF_a__h6341;
    DEF_a__h8315 = DEF_a__h6401 | DEF_b__h6402;
    DEF_b__h8434 = DEF_sel__h3455 & DEF_a__h8315;
    DEF_a__h10373 = DEF_a__h8433 | DEF_b__h8434;
    DEF_b__h10608 = DEF_sel__h2613 & DEF_a__h10373;
    DEF_a__h12599 = DEF_a__h10607 | DEF_b__h10608;
    DEF_a__h12601 = DEF_a__h2556 & DEF_a__h12599;
    DEF_a__h10375 = DEF_a__h3398 & DEF_a__h10373;
    DEF_a__h8317 = DEF_a__h4240 & DEF_a__h8315;
    DEF_a__h6343 = DEF_a__h5082 & DEF_a__h6341;
    DEF_b__h6344 = DEF_sel__h4297 & DEF_a__h6283;
    DEF_a__h8257 = DEF_a__h6343 | DEF_b__h6344;
    DEF_b__h8376 = DEF_sel__h3455 & DEF_a__h8257;
    DEF_a__h10315 = DEF_a__h8375 | DEF_b__h8376;
    DEF_b__h10550 = DEF_sel__h2613 & DEF_a__h10315;
    DEF_a__h12541 = DEF_a__h10549 | DEF_b__h10550;
    DEF_a__h12543 = DEF_a__h2556 & DEF_a__h12541;
    DEF_a__h10317 = DEF_a__h3398 & DEF_a__h10315;
    DEF_a__h8259 = DEF_a__h4240 & DEF_a__h8257;
    DEF_a__h6285 = DEF_a__h5082 & DEF_a__h6283;
    DEF_b__h6286 = DEF_sel__h4297 & DEF_a__h6225;
    DEF_a__h8199 = DEF_a__h6285 | DEF_b__h6286;
    DEF_b__h8318 = DEF_sel__h3455 & DEF_a__h8199;
    DEF_a__h10257 = DEF_a__h8317 | DEF_b__h8318;
    DEF_b__h10492 = DEF_sel__h2613 & DEF_a__h10257;
    DEF_a__h12483 = DEF_a__h10491 | DEF_b__h10492;
    DEF_a__h12485 = DEF_a__h2556 & DEF_a__h12483;
    DEF_a__h10259 = DEF_a__h3398 & DEF_a__h10257;
    DEF_a__h8201 = DEF_a__h4240 & DEF_a__h8199;
    DEF_a__h6227 = DEF_a__h5082 & DEF_a__h6225;
    DEF_b__h6228 = DEF_sel__h4297 & DEF_a__h6167;
    DEF_a__h8141 = DEF_a__h6227 | DEF_b__h6228;
    DEF_b__h8260 = DEF_sel__h3455 & DEF_a__h8141;
    DEF_a__h10199 = DEF_a__h8259 | DEF_b__h8260;
    DEF_b__h10434 = DEF_sel__h2613 & DEF_a__h10199;
    DEF_a__h12425 = DEF_a__h10433 | DEF_b__h10434;
    DEF_a__h12427 = DEF_a__h2556 & DEF_a__h12425;
    DEF_a__h10201 = DEF_a__h3398 & DEF_a__h10199;
    DEF_a__h8143 = DEF_a__h4240 & DEF_a__h8141;
    DEF_a__h6169 = DEF_a__h5082 & DEF_a__h6167;
    DEF_b__h6170 = DEF_sel__h4297 & DEF_a__h6109;
    DEF_a__h8083 = DEF_a__h6169 | DEF_b__h6170;
    DEF_b__h8202 = DEF_sel__h3455 & DEF_a__h8083;
    DEF_a__h10141 = DEF_a__h8201 | DEF_b__h8202;
    DEF_b__h10376 = DEF_sel__h2613 & DEF_a__h10141;
    DEF_a__h12367 = DEF_a__h10375 | DEF_b__h10376;
    DEF_a__h12369 = DEF_a__h2556 & DEF_a__h12367;
    DEF_a__h10143 = DEF_a__h3398 & DEF_a__h10141;
    DEF_a__h8085 = DEF_a__h4240 & DEF_a__h8083;
    DEF_a__h5821 = DEF_a__h5082 & DEF_a__h5819;
    DEF_a__h6111 = DEF_a__h5082 & DEF_a__h6109;
    DEF_b__h6112 = DEF_sel__h4297 & DEF_a__h6051;
    DEF_a__h8025 = DEF_a__h6111 | DEF_b__h6112;
    DEF_b__h8144 = DEF_sel__h3455 & DEF_a__h8025;
    DEF_a__h10083 = DEF_a__h8143 | DEF_b__h8144;
    DEF_b__h10318 = DEF_sel__h2613 & DEF_a__h10083;
    DEF_a__h12309 = DEF_a__h10317 | DEF_b__h10318;
    DEF_b__h12776 = DEF_sel__h1771 & DEF_a__h12309;
    DEF_a__h14871 = DEF_a__h12775 | DEF_b__h12776;
    DEF_a__h14873 = DEF_a__h1714 & DEF_a__h14871;
    DEF_a__h12311 = DEF_a__h2556 & DEF_a__h12309;
    DEF_a__h10085 = DEF_a__h3398 & DEF_a__h10083;
    DEF_a__h8027 = DEF_a__h4240 & DEF_a__h8025;
    DEF_a__h6053 = DEF_a__h5082 & DEF_a__h6051;
    DEF_b__h6054 = DEF_sel__h4297 & DEF_a__h5993;
    DEF_a__h7967 = DEF_a__h6053 | DEF_b__h6054;
    DEF_b__h8086 = DEF_sel__h3455 & DEF_a__h7967;
    DEF_a__h10025 = DEF_a__h8085 | DEF_b__h8086;
    DEF_b__h10260 = DEF_sel__h2613 & DEF_a__h10025;
    DEF_a__h12251 = DEF_a__h10259 | DEF_b__h10260;
    DEF_b__h12718 = DEF_sel__h1771 & DEF_a__h12251;
    DEF_a__h14813 = DEF_a__h12717 | DEF_b__h12718;
    DEF_a__h14815 = DEF_a__h1714 & DEF_a__h14813;
    DEF_a__h12253 = DEF_a__h2556 & DEF_a__h12251;
    DEF_a__h10027 = DEF_a__h3398 & DEF_a__h10025;
    DEF_a__h7969 = DEF_a__h4240 & DEF_a__h7967;
    DEF_a__h5995 = DEF_a__h5082 & DEF_a__h5993;
    DEF_b__h5996 = DEF_sel__h4297 & DEF_a__h5935;
    DEF_a__h7909 = DEF_a__h5995 | DEF_b__h5996;
    DEF_b__h8028 = DEF_sel__h3455 & DEF_a__h7909;
    DEF_a__h9967 = DEF_a__h8027 | DEF_b__h8028;
    DEF_b__h10202 = DEF_sel__h2613 & DEF_a__h9967;
    DEF_a__h12193 = DEF_a__h10201 | DEF_b__h10202;
    DEF_b__h12660 = DEF_sel__h1771 & DEF_a__h12193;
    DEF_a__h14755 = DEF_a__h12659 | DEF_b__h12660;
    DEF_a__h14757 = DEF_a__h1714 & DEF_a__h14755;
    DEF_a__h12195 = DEF_a__h2556 & DEF_a__h12193;
    DEF_a__h9969 = DEF_a__h3398 & DEF_a__h9967;
    DEF_a__h7911 = DEF_a__h4240 & DEF_a__h7909;
    DEF_a__h5937 = DEF_a__h5082 & DEF_a__h5935;
    DEF_b__h5938 = DEF_sel__h4297 & DEF_a__h5877;
    DEF_a__h7851 = DEF_a__h5937 | DEF_b__h5938;
    DEF_b__h7970 = DEF_sel__h3455 & DEF_a__h7851;
    DEF_a__h9909 = DEF_a__h7969 | DEF_b__h7970;
    DEF_b__h10144 = DEF_sel__h2613 & DEF_a__h9909;
    DEF_a__h12135 = DEF_a__h10143 | DEF_b__h10144;
    DEF_b__h12602 = DEF_sel__h1771 & DEF_a__h12135;
    DEF_a__h14697 = DEF_a__h12601 | DEF_b__h12602;
    DEF_a__h14699 = DEF_a__h1714 & DEF_a__h14697;
    DEF_a__h12137 = DEF_a__h2556 & DEF_a__h12135;
    DEF_a__h9911 = DEF_a__h3398 & DEF_a__h9909;
    DEF_a__h7853 = DEF_a__h4240 & DEF_a__h7851;
    DEF_a__h5879 = DEF_a__h5082 & DEF_a__h5877;
    DEF_b__h5880 = DEF_sel__h4297 & DEF_a__h5819;
    DEF_a__h7793 = DEF_a__h5879 | DEF_b__h5880;
    DEF_b__h7912 = DEF_sel__h3455 & DEF_a__h7793;
    DEF_a__h9851 = DEF_a__h7911 | DEF_b__h7912;
    DEF_b__h10086 = DEF_sel__h2613 & DEF_a__h9851;
    DEF_a__h12077 = DEF_a__h10085 | DEF_b__h10086;
    DEF_b__h12544 = DEF_sel__h1771 & DEF_a__h12077;
    DEF_a__h14639 = DEF_a__h12543 | DEF_b__h12544;
    DEF_a__h14641 = DEF_a__h1714 & DEF_a__h14639;
    DEF_a__h12079 = DEF_a__h2556 & DEF_a__h12077;
    DEF_a__h9853 = DEF_a__h3398 & DEF_a__h9851;
    DEF_a__h7795 = DEF_a__h4240 & DEF_a__h7793;
    DEF_b__h5822 = DEF_sel__h4297 & DEF_a__h5761;
    DEF_a__h7735 = DEF_a__h5821 | DEF_b__h5822;
    DEF_b__h7854 = DEF_sel__h3455 & DEF_a__h7735;
    DEF_a__h9793 = DEF_a__h7853 | DEF_b__h7854;
    DEF_b__h10028 = DEF_sel__h2613 & DEF_a__h9793;
    DEF_a__h12019 = DEF_a__h10027 | DEF_b__h10028;
    DEF_b__h12486 = DEF_sel__h1771 & DEF_a__h12019;
    DEF_a__h14581 = DEF_a__h12485 | DEF_b__h12486;
    DEF_a__h14583 = DEF_a__h1714 & DEF_a__h14581;
    DEF_a__h12021 = DEF_a__h2556 & DEF_a__h12019;
    DEF_a__h9795 = DEF_a__h3398 & DEF_a__h9793;
    DEF_a__h7737 = DEF_a__h4240 & DEF_a__h7735;
    DEF_a__h5763 = DEF_a__h5082 & DEF_a__h5761;
    DEF_b__h5764 = DEF_sel__h4297 & DEF_a__h5703;
    DEF_a__h7677 = DEF_a__h5763 | DEF_b__h5764;
    DEF_b__h7796 = DEF_sel__h3455 & DEF_a__h7677;
    DEF_a__h9735 = DEF_a__h7795 | DEF_b__h7796;
    DEF_b__h9970 = DEF_sel__h2613 & DEF_a__h9735;
    DEF_a__h11961 = DEF_a__h9969 | DEF_b__h9970;
    DEF_b__h12428 = DEF_sel__h1771 & DEF_a__h11961;
    DEF_a__h14523 = DEF_a__h12427 | DEF_b__h12428;
    DEF_a__h14525 = DEF_a__h1714 & DEF_a__h14523;
    DEF_a__h11963 = DEF_a__h2556 & DEF_a__h11961;
    DEF_a__h9737 = DEF_a__h3398 & DEF_a__h9735;
    DEF_a__h7679 = DEF_a__h4240 & DEF_a__h7677;
    DEF_a__h5705 = DEF_a__h5082 & DEF_a__h5703;
    DEF_b__h5706 = DEF_sel__h4297 & DEF_a__h5645;
    DEF_a__h7619 = DEF_a__h5705 | DEF_b__h5706;
    DEF_b__h7738 = DEF_sel__h3455 & DEF_a__h7619;
    DEF_a__h9677 = DEF_a__h7737 | DEF_b__h7738;
    DEF_b__h9912 = DEF_sel__h2613 & DEF_a__h9677;
    DEF_a__h11903 = DEF_a__h9911 | DEF_b__h9912;
    DEF_b__h12370 = DEF_sel__h1771 & DEF_a__h11903;
    DEF_a__h14465 = DEF_a__h12369 | DEF_b__h12370;
    DEF_a__h14467 = DEF_a__h1714 & DEF_a__h14465;
    DEF_a__h11905 = DEF_a__h2556 & DEF_a__h11903;
    DEF_a__h9679 = DEF_a__h3398 & DEF_a__h9677;
    DEF_a__h7621 = DEF_a__h4240 & DEF_a__h7619;
    DEF_a__h5647 = DEF_a__h5082 & DEF_a__h5645;
    DEF_b__h5648 = DEF_sel__h4297 & DEF_a__h5587;
    DEF_a__h7561 = DEF_a__h5647 | DEF_b__h5648;
    DEF_b__h7680 = DEF_sel__h3455 & DEF_a__h7561;
    DEF_a__h9619 = DEF_a__h7679 | DEF_b__h7680;
    DEF_b__h9854 = DEF_sel__h2613 & DEF_a__h9619;
    DEF_a__h11845 = DEF_a__h9853 | DEF_b__h9854;
    DEF_b__h12312 = DEF_sel__h1771 & DEF_a__h11845;
    DEF_a__h14407 = DEF_a__h12311 | DEF_b__h12312;
    DEF_a__h14409 = DEF_a__h1714 & DEF_a__h14407;
    DEF_a__h11847 = DEF_a__h2556 & DEF_a__h11845;
    DEF_a__h9621 = DEF_a__h3398 & DEF_a__h9619;
    DEF_a__h7563 = DEF_a__h4240 & DEF_a__h7561;
    DEF_a__h5589 = DEF_a__h5082 & DEF_a__h5587;
    DEF_b__h5590 = DEF_sel__h4297 & DEF_a__h5529;
    DEF_a__h7503 = DEF_a__h5589 | DEF_b__h5590;
    DEF_b__h7622 = DEF_sel__h3455 & DEF_a__h7503;
    DEF_a__h9561 = DEF_a__h7621 | DEF_b__h7622;
    DEF_b__h9796 = DEF_sel__h2613 & DEF_a__h9561;
    DEF_a__h11787 = DEF_a__h9795 | DEF_b__h9796;
    DEF_b__h12254 = DEF_sel__h1771 & DEF_a__h11787;
    DEF_a__h14349 = DEF_a__h12253 | DEF_b__h12254;
    DEF_a__h14351 = DEF_a__h1714 & DEF_a__h14349;
    DEF_a__h11789 = DEF_a__h2556 & DEF_a__h11787;
    DEF_a__h9563 = DEF_a__h3398 & DEF_a__h9561;
    DEF_a__h7505 = DEF_a__h4240 & DEF_a__h7503;
    DEF_a__h5531 = DEF_a__h5082 & DEF_a__h5529;
    DEF_b__h5532 = DEF_sel__h4297 & DEF_a__h5471;
    DEF_a__h7445 = DEF_a__h5531 | DEF_b__h5532;
    DEF_b__h7564 = DEF_sel__h3455 & DEF_a__h7445;
    DEF_a__h9503 = DEF_a__h7563 | DEF_b__h7564;
    DEF_b__h9738 = DEF_sel__h2613 & DEF_a__h9503;
    DEF_a__h11729 = DEF_a__h9737 | DEF_b__h9738;
    DEF_b__h12196 = DEF_sel__h1771 & DEF_a__h11729;
    DEF_a__h14291 = DEF_a__h12195 | DEF_b__h12196;
    DEF_a__h14293 = DEF_a__h1714 & DEF_a__h14291;
    DEF_a__h11731 = DEF_a__h2556 & DEF_a__h11729;
    DEF_a__h9505 = DEF_a__h3398 & DEF_a__h9503;
    DEF_a__h7447 = DEF_a__h4240 & DEF_a__h7445;
    DEF_a__h5473 = DEF_a__h5082 & DEF_a__h5471;
    DEF_b__h5474 = DEF_sel__h4297 & DEF_a__h5413;
    DEF_a__h7387 = DEF_a__h5473 | DEF_b__h5474;
    DEF_b__h7506 = DEF_sel__h3455 & DEF_a__h7387;
    DEF_a__h9445 = DEF_a__h7505 | DEF_b__h7506;
    DEF_b__h9680 = DEF_sel__h2613 & DEF_a__h9445;
    DEF_a__h11671 = DEF_a__h9679 | DEF_b__h9680;
    DEF_b__h12138 = DEF_sel__h1771 & DEF_a__h11671;
    DEF_a__h14233 = DEF_a__h12137 | DEF_b__h12138;
    DEF_a__h14235 = DEF_a__h1714 & DEF_a__h14233;
    DEF_a__h11673 = DEF_a__h2556 & DEF_a__h11671;
    DEF_a__h9447 = DEF_a__h3398 & DEF_a__h9445;
    DEF_a__h7389 = DEF_a__h4240 & DEF_a__h7387;
    DEF_a__h5415 = DEF_a__h5082 & DEF_a__h5413;
    DEF_b__h5416 = DEF_sel__h4297 & DEF_a__h5355;
    DEF_a__h7329 = DEF_a__h5415 | DEF_b__h5416;
    DEF_b__h7448 = DEF_sel__h3455 & DEF_a__h7329;
    DEF_a__h9387 = DEF_a__h7447 | DEF_b__h7448;
    DEF_b__h9622 = DEF_sel__h2613 & DEF_a__h9387;
    DEF_a__h11613 = DEF_a__h9621 | DEF_b__h9622;
    DEF_b__h12080 = DEF_sel__h1771 & DEF_a__h11613;
    DEF_a__h14175 = DEF_a__h12079 | DEF_b__h12080;
    DEF_a__h14177 = DEF_a__h1714 & DEF_a__h14175;
    DEF_a__h11615 = DEF_a__h2556 & DEF_a__h11613;
    DEF_a__h9389 = DEF_a__h3398 & DEF_a__h9387;
    DEF_a__h7331 = DEF_a__h4240 & DEF_a__h7329;
    DEF_a__h5357 = DEF_a__h5082 & DEF_a__h5355;
    DEF_b__h5358 = DEF_sel__h4297 & DEF_a__h5297;
    DEF_a__h7271 = DEF_a__h5357 | DEF_b__h5358;
    DEF_b__h7390 = DEF_sel__h3455 & DEF_a__h7271;
    DEF_a__h9329 = DEF_a__h7389 | DEF_b__h7390;
    DEF_b__h9564 = DEF_sel__h2613 & DEF_a__h9329;
    DEF_a__h11555 = DEF_a__h9563 | DEF_b__h9564;
    DEF_b__h12022 = DEF_sel__h1771 & DEF_a__h11555;
    DEF_a__h14117 = DEF_a__h12021 | DEF_b__h12022;
    DEF_a__h14119 = DEF_a__h1714 & DEF_a__h14117;
    DEF_a__h11557 = DEF_a__h2556 & DEF_a__h11555;
    DEF_a__h9331 = DEF_a__h3398 & DEF_a__h9329;
    DEF_a__h7273 = DEF_a__h4240 & DEF_a__h7271;
    DEF_a__h5299 = DEF_a__h5082 & DEF_a__h5297;
    DEF_b__h5300 = DEF_sel__h4297 & DEF_a__h5239;
    DEF_a__h7213 = DEF_a__h5299 | DEF_b__h5300;
    DEF_b__h7332 = DEF_sel__h3455 & DEF_a__h7213;
    DEF_a__h9271 = DEF_a__h7331 | DEF_b__h7332;
    DEF_b__h9506 = DEF_sel__h2613 & DEF_a__h9271;
    DEF_a__h11497 = DEF_a__h9505 | DEF_b__h9506;
    DEF_b__h11964 = DEF_sel__h1771 & DEF_a__h11497;
    DEF_a__h14059 = DEF_a__h11963 | DEF_b__h11964;
    DEF_a__h14061 = DEF_a__h1714 & DEF_a__h14059;
    DEF_a__h11499 = DEF_a__h2556 & DEF_a__h11497;
    DEF_a__h9273 = DEF_a__h3398 & DEF_a__h9271;
    DEF_a__h7215 = DEF_a__h4240 & DEF_a__h7213;
    DEF_a__h5241 = DEF_a__h5082 & DEF_a__h5239;
    DEF_b__h5242 = DEF_sel__h4297 & DEF_a__h5181;
    DEF_a__h7155 = DEF_a__h5241 | DEF_b__h5242;
    DEF_b__h7274 = DEF_sel__h3455 & DEF_a__h7155;
    DEF_a__h9213 = DEF_a__h7273 | DEF_b__h7274;
    DEF_b__h9448 = DEF_sel__h2613 & DEF_a__h9213;
    DEF_a__h11439 = DEF_a__h9447 | DEF_b__h9448;
    DEF_b__h11906 = DEF_sel__h1771 & DEF_a__h11439;
    DEF_a__h14001 = DEF_a__h11905 | DEF_b__h11906;
    DEF_a__h14003 = DEF_a__h1714 & DEF_a__h14001;
    DEF_a__h11441 = DEF_a__h2556 & DEF_a__h11439;
    DEF_a__h9215 = DEF_a__h3398 & DEF_a__h9213;
    DEF_a__h7157 = DEF_a__h4240 & DEF_a__h7155;
    DEF_a__h5183 = DEF_a__h5082 & DEF_a__h5181;
    DEF_b__h5184 = DEF_sel__h4297 & DEF_a__h5078;
    DEF_a__h7097 = DEF_a__h5183 | DEF_b__h5184;
    DEF_b__h7216 = DEF_sel__h3455 & DEF_a__h7097;
    DEF_a__h9155 = DEF_a__h7215 | DEF_b__h7216;
    DEF_b__h9390 = DEF_sel__h2613 & DEF_a__h9155;
    DEF_a__h11381 = DEF_a__h9389 | DEF_b__h9390;
    DEF_a__h13479 = DEF_a__h2556 & DEF_a__h11381;
    DEF_b__h14410 = DEF_sel__h905 & DEF_a__h13479;
    DEF_a__h13481 = DEF_a__h1714 & DEF_a__h13479;
    DEF_b__h11848 = DEF_sel__h1771 & DEF_a__h11381;
    DEF_a__h13943 = DEF_a__h11847 | DEF_b__h11848;
    DEF_b__h14874 = DEF_sel__h905 & DEF_a__h13943;
    DEF_a__h13945 = DEF_a__h1714 & DEF_a__h13943;
    DEF_a__h11149 = DEF_a__h3398 & DEF_a__h9155;
    DEF_a__h13247 = DEF_a__h2556 & DEF_a__h11149;
    DEF_b__h14178 = DEF_sel__h905 & DEF_a__h13247;
    DEF_a__h13249 = DEF_a__h1714 & DEF_a__h13247;
    DEF_b__h11616 = DEF_sel__h1771 & DEF_a__h11149;
    DEF_a__h13711 = DEF_a__h11615 | DEF_b__h11616;
    DEF_b__h14642 = DEF_sel__h905 & DEF_a__h13711;
    DEF_a__h13713 = DEF_a__h1714 & DEF_a__h13711;
    DEF_a__h9039 = DEF_a__h4240 & DEF_a__h7097;
    DEF_b__h9274 = DEF_sel__h2613 & DEF_a__h9039;
    DEF_a__h11265 = DEF_a__h9273 | DEF_b__h9274;
    DEF_a__h13363 = DEF_a__h2556 & DEF_a__h11265;
    DEF_b__h14294 = DEF_sel__h905 & DEF_a__h13363;
    DEF_a__h13365 = DEF_a__h1714 & DEF_a__h13363;
    DEF_b__h11732 = DEF_sel__h1771 & DEF_a__h11265;
    DEF_a__h13827 = DEF_a__h11731 | DEF_b__h11732;
    DEF_a__h13829 = DEF_a__h1714 & DEF_a__h13827;
    DEF_b__h14758 = DEF_sel__h905 & DEF_a__h13827;
    DEF_a__h11033 = DEF_a__h3398 & DEF_a__h9039;
    DEF_a__h13131 = DEF_a__h2556 & DEF_a__h11033;
    DEF_b__h14062 = DEF_sel__h905 & DEF_a__h13131;
    DEF_a__h13133 = DEF_a__h1714 & DEF_a__h13131;
    DEF_b__h11500 = DEF_sel__h1771 & DEF_a__h11033;
    DEF_a__h13595 = DEF_a__h11499 | DEF_b__h11500;
    DEF_b__h14526 = DEF_sel__h905 & DEF_a__h13595;
    DEF_a__h13597 = DEF_a__h1714 & DEF_a__h13595;
    DEF_b__h7156 = DEF_a__h5082 & DEF_a__h5078;
    DEF_b__h7158 = DEF_sel__h3455 & DEF_b__h7156;
    DEF_a__h9097 = DEF_a__h7157 | DEF_b__h7158;
    DEF_b__h9332 = DEF_sel__h2613 & DEF_a__h9097;
    DEF_a__h11323 = DEF_a__h9331 | DEF_b__h9332;
    DEF_a__h13421 = DEF_a__h2556 & DEF_a__h11323;
    DEF_b__h14352 = DEF_sel__h905 & DEF_a__h13421;
    DEF_a__h13423 = DEF_a__h1714 & DEF_a__h13421;
    DEF_b__h11790 = DEF_sel__h1771 & DEF_a__h11323;
    DEF_a__h13885 = DEF_a__h11789 | DEF_b__h11790;
    DEF_b__h14816 = DEF_sel__h905 & DEF_a__h13885;
    DEF_a__h13887 = DEF_a__h1714 & DEF_a__h13885;
    DEF_a__h11091 = DEF_a__h3398 & DEF_a__h9097;
    DEF_a__h13189 = DEF_a__h2556 & DEF_a__h11091;
    DEF_b__h14120 = DEF_sel__h905 & DEF_a__h13189;
    DEF_a__h13191 = DEF_a__h1714 & DEF_a__h13189;
    DEF_b__h11558 = DEF_sel__h1771 & DEF_a__h11091;
    DEF_a__h13653 = DEF_a__h11557 | DEF_b__h11558;
    DEF_b__h14584 = DEF_sel__h905 & DEF_a__h13653;
    DEF_a__h13655 = DEF_a__h1714 & DEF_a__h13653;
    DEF_b__h9214 = DEF_a__h4240 & DEF_b__h7156;
    DEF_b__h9216 = DEF_sel__h2613 & DEF_b__h9214;
    DEF_a__h11207 = DEF_a__h9215 | DEF_b__h9216;
    DEF_a__h13305 = DEF_a__h2556 & DEF_a__h11207;
    DEF_b__h14236 = DEF_sel__h905 & DEF_a__h13305;
    DEF_a__h13307 = DEF_a__h1714 & DEF_a__h13305;
    DEF_b__h11674 = DEF_sel__h1771 & DEF_a__h11207;
    DEF_a__h13769 = DEF_a__h11673 | DEF_b__h11674;
    DEF_b__h14700 = DEF_sel__h905 & DEF_a__h13769;
    DEF_a__h13771 = DEF_a__h1714 & DEF_a__h13769;
    DEF_b__h11440 = DEF_a__h3398 & DEF_b__h9214;
    DEF_b__h11442 = DEF_sel__h1771 & DEF_b__h11440;
    DEF_a__h13537 = DEF_a__h11441 | DEF_b__h11442;
    DEF_b__h14468 = DEF_sel__h905 & DEF_a__h13537;
    DEF_a__h13539 = DEF_a__h1714 & DEF_a__h13537;
    DEF_b__h14002 = DEF_a__h2556 & DEF_b__h11440;
    DEF_b__h14004 = DEF_sel__h905 & DEF_b__h14002;
    DEF_a__h1712 = DEF_a__h1714 & DEF_b__h14002;
    DEF_v__h834 = ((65535u & ((((tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & ((DEF_a__h1712 << 1u) | DEF_a__h13133)) << 2u) | ((tUInt8)3u & ((DEF_a__h13191 << 1u) | DEF_a__h13249)))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & ((DEF_a__h13307 << 1u) | DEF_a__h13365)) << 2u) | ((tUInt8)3u & ((DEF_a__h13423 << 1u) | DEF_a__h13481))))))) << 8u) | (tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & ((DEF_a__h13539 << 1u) | DEF_a__h13597)) << 2u) | ((tUInt8)3u & ((DEF_a__h13655 << 1u) | DEF_a__h13713)))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & ((DEF_a__h13771 << 1u) | DEF_a__h13829)) << 2u) | ((tUInt8)3u & ((DEF_a__h13887 << 1u) | DEF_a__h13945)))))))) << 16u) | (65535u & ((((tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14003 | DEF_b__h14004) << 1u) | (DEF_a__h14061 | DEF_b__h14062))) << 2u) | ((tUInt8)3u & (((DEF_a__h14119 | DEF_b__h14120) << 1u) | (DEF_a__h14177 | DEF_b__h14178))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14235 | DEF_b__h14236) << 1u) | (DEF_a__h14293 | DEF_b__h14294))) << 2u) | ((tUInt8)3u & (((DEF_a__h14351 | DEF_b__h14352) << 1u) | (DEF_a__h14409 | DEF_b__h14410)))))))) << 8u) | (tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14467 | DEF_b__h14468) << 1u) | (DEF_a__h14525 | DEF_b__h14526))) << 2u) | ((tUInt8)3u & (((DEF_a__h14583 | DEF_b__h14584) << 1u) | (DEF_a__h14641 | DEF_b__h14642))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14699 | DEF_b__h14700) << 1u) | (DEF_a__h14757 | DEF_b__h14758))) << 2u) | ((tUInt8)3u & (((DEF_a__h14815 | DEF_b__h14816) << 1u) | (DEF_a__h14873 | DEF_b__h14874)))))))));
    DEF_x__h1708 = DEF_v__h834 ^ DEF_trueResultL__h1695;
    DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d493 = DEF_NOT_cycle_EQ_128___d9 && !(DEF_x__h1708 == 0u);
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      if (DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d493)
	dollar_display(this,
		       "s,32,5,32,32",
		       &__str_literal_2,
		       DEF_TASK_getRandom___d495,
		       DEF_TASK_getRandom_0_BITS_4_TO_0___d497,
		       DEF_v__h834,
		       DEF_trueResultL__h1695);
      if (DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d493)
	dollar_finish("32", 1u);
    }
    if (DEF_NOT_cycle_EQ_128___d9)
      INST_cycle.METH_write(DEF_x__h15089);
  }
  
  
  /* Methods */
  
  
  /* Reset routines */
  
  void MOD_mkTbRightLogical::reset_RST_N(tUInt8 ARG_rst_in)
  {
    PORT_RST_N = ARG_rst_in;
    INST_randomVal_init.reset_RST_N(ARG_rst_in);
    INST_randomShift_init.reset_RST_N(ARG_rst_in);
    INST_cycle.reset_RST_N(ARG_rst_in);
  }
  
  
  /* Static handles to reset routines */
  
  
  /* Functions for the parent module to register its reset fns */
  
  
  /* Functions to set the elaborated clock id */
  
  void MOD_mkTbRightLogical::set_clk_0(char const *s)
  {
    __clk_handle_0 = bk_get_or_define_clock(s);
  }
  
  
  /* State dumping routine */
  void MOD_mkTbRightLogical::dump_state(unsigned int indent)
  {
    printf("%*s%s:\n", indent, "", inst_name);
    INST_cycle.dump_state(indent + 2u);
    INST_randomShift_init.dump_state(indent + 2u);
    INST_randomVal_init.dump_state(indent + 2u);
  }
  
  
  /* VCD dumping routines */
  
  unsigned int MOD_mkTbRightLogical::dump_VCD_defs(unsigned int levels)
  {
    fprintf(vcd_file, "$scope module %s $end\n", inst_name);
    vcd_num = vcd_reserve_ids(8u);
    unsigned int num = vcd_num;
    for (unsigned int hdl = 0u; hdl < bk_num_clocks(); ++hdl)
      vcd_add_clock_def(this, bk_clock_name(hdl), bk_clock_vcd_num(hdl));
    vcd_write_def(bk_clock_vcd_num(__clk_handle_0), "CLK", 1u);
    vcd_write_def(num++, "RST_N", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d495", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d496", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "cycle_EQ_128___d6", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "x__h370", 32u);
    num = INST_cycle.dump_VCD_defs(num);
    num = INST_randomShift_init.dump_VCD_defs(num);
    num = INST_randomVal_init.dump_VCD_defs(num);
    fprintf(vcd_file, "$upscope $end\n");
    return num;
  }
  
  void MOD_mkTbRightLogical::dump_VCD(tVCDDumpType dt,
				      unsigned int levels,
				      MOD_mkTbRightLogical &backing)
  {
    vcd_defs(dt, backing);
    vcd_prims(dt, backing);
  }
  
  void MOD_mkTbRightLogical::vcd_defs(tVCDDumpType dt, MOD_mkTbRightLogical &backing)
  {
    unsigned int num = vcd_num;
    if (dt == VCD_DUMP_XS)
    {
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 32u);
    }
    else
      if (dt == VCD_DUMP_CHANGES)
      {
	if ((backing.PORT_RST_N) != PORT_RST_N)
	{
	  vcd_write_val(num, PORT_RST_N, 1u);
	  backing.PORT_RST_N = PORT_RST_N;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d495) != DEF_TASK_getRandom___d495)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d495, 32u);
	  backing.DEF_TASK_getRandom___d495 = DEF_TASK_getRandom___d495;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d496) != DEF_TASK_getRandom___d496)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d496, 32u);
	  backing.DEF_TASK_getRandom___d496 = DEF_TASK_getRandom___d496;
	}
	++num;
	if ((backing.DEF_cycle_EQ_128___d6) != DEF_cycle_EQ_128___d6)
	{
	  vcd_write_val(num, DEF_cycle_EQ_128___d6, 1u);
	  backing.DEF_cycle_EQ_128___d6 = DEF_cycle_EQ_128___d6;
	}
	++num;
	if ((backing.DEF_x__h370) != DEF_x__h370)
	{
	  vcd_write_val(num, DEF_x__h370, 32u);
	  backing.DEF_x__h370 = DEF_x__h370;
	}
	++num;
      }
      else
      {
	vcd_write_val(num++, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
	vcd_write_val(num++, DEF_TASK_getRandom___d495, 32u);
	backing.DEF_TASK_getRandom___d495 = DEF_TASK_getRandom___d495;
	vcd_write_val(num++, DEF_TASK_getRandom___d496, 32u);
	backing.DEF_TASK_getRandom___d496 = DEF_TASK_getRandom___d496;
	vcd_write_val(num++, DEF_cycle_EQ_128___d6, 1u);
	backing.DEF_cycle_EQ_128___d6 = DEF_cycle_EQ_128___d6;
	vcd_write_val(num++, DEF_x__h370, 32u);
	backing.DEF_x__h370 = DEF_x__h370;
      }
  }
  
  void MOD_mkTbRightLogical::vcd_prims(tVCDDumpType dt, MOD_mkTbRightLogical &backing)
  {
    INST_cycle.dump_VCD(dt, backing.INST_cycle);
    INST_randomShift_init.dump_VCD(dt, backing.INST_randomShift_init);
    INST_randomVal_init.dump_VCD(dt, backing.INST_randomVal_init);
  }
}
