/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sat Jan 25 18:07:51 IST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbRightArith.h"
#include "imported_BDPI_functions.h"

namespace bluesim
{
  
  /* String declarations */
  static std::string const __str_literal_2("FAILED Arithmetic Shift %b >> %d gave %b instead of %b",
					   54u);
  static std::string const __str_literal_1("PASSED", 6u);
  
  
  /* Constructor */
  MOD_mkTbRightArith::MOD_mkTbRightArith(char const *name, Module *parent)
    : Module(name, parent),
      __clk_handle_0(BAD_CLOCK_HANDLE),
      INST_cycle("cycle", this, 32u, 0u, (tUInt8)0u),
      INST_randomShift_init("randomShift_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      INST_randomVal_init("randomVal_init", this, 1u, (tUInt8)0u, (tUInt8)0u),
      PORT_RST_N((tUInt8)1u),
      DEF_TASK_getRandom___d531(2863311530u),
      DEF_TASK_getRandom___d530(2863311530u)
  {
    symbol_count = 7u;
    symbols = new tSym[symbol_count];
    init_symbols_0();
  }
  
  
  /* Symbol init fns */
  
  void MOD_mkTbRightArith::init_symbols_0()
  {
    init_symbol(&symbols[0u], "cycle", SYM_MODULE, &INST_cycle);
    init_symbol(&symbols[1u], "RL_randomShift_initialize", SYM_RULE);
    init_symbol(&symbols[2u], "RL_randomVal_initialize", SYM_RULE);
    init_symbol(&symbols[3u], "RL_test", SYM_RULE);
    init_symbol(&symbols[4u], "randomShift_init", SYM_MODULE, &INST_randomShift_init);
    init_symbol(&symbols[5u], "randomVal_init", SYM_MODULE, &INST_randomVal_init);
    init_symbol(&symbols[6u], "x__h370", SYM_DEF, &DEF_x__h370, 32u);
  }
  
  
  /* Rule actions */
  
  void MOD_mkTbRightArith::RL_randomVal_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3735928559u);
    INST_randomVal_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkTbRightArith::RL_randomShift_initialize()
  {
    if (!(PORT_RST_N == (tUInt8)0u))
      setSeed(3405691582u);
    INST_randomShift_init.METH_write((tUInt8)1u);
  }
  
  void MOD_mkTbRightArith::RL_test()
  {
    tUInt32 DEF_x__h15090;
    tUInt8 DEF_a__h5081;
    tUInt8 DEF_b__h7181;
    tUInt8 DEF_b__h5210;
    tUInt8 DEF_a__h5209;
    tUInt8 DEF_a__h7122;
    tUInt8 DEF_a__h9063;
    tUInt8 DEF_a__h11048;
    tUInt8 DEF_b__h5674;
    tUInt8 DEF_a__h5673;
    tUInt8 DEF_a__h7586;
    tUInt8 DEF_b__h7589;
    tUInt8 DEF_a__h7588;
    tUInt8 DEF_a__h9525;
    tUInt8 DEF_b__h9528;
    tUInt8 DEF_a__h9527;
    tUInt8 DEF_a__h11512;
    tUInt8 DEF_b__h11515;
    tUInt8 DEF_a__h11514;
    tUInt8 DEF_a__h13595;
    tUInt8 DEF_b__h5790;
    tUInt8 DEF_a__h5789;
    tUInt8 DEF_a__h7702;
    tUInt8 DEF_b__h7705;
    tUInt8 DEF_a__h7704;
    tUInt8 DEF_a__h9641;
    tUInt8 DEF_b__h9644;
    tUInt8 DEF_a__h9643;
    tUInt8 DEF_a__h11628;
    tUInt8 DEF_b__h11631;
    tUInt8 DEF_a__h11630;
    tUInt8 DEF_a__h13711;
    tUInt8 DEF_a__h1713;
    tUInt8 DEF_a__h13597;
    tUInt8 DEF_b__h14758;
    tUInt8 DEF_a__h14757;
    tUInt8 DEF_a__h4239;
    tUInt8 DEF_b__h9236;
    tUInt8 DEF_a__h3397;
    tUInt8 DEF_b__h11455;
    tUInt8 DEF_a__h2555;
    tUInt8 DEF_a__h1711;
    tUInt8 DEF_b__h7125;
    tUInt8 DEF_a__h7124;
    tUInt8 DEF_a__h9061;
    tUInt8 DEF_a__h11050;
    tUInt8 DEF_a__h13131;
    tUInt8 DEF_a__h13133;
    tUInt8 DEF_b__h5268;
    tUInt8 DEF_a__h5267;
    tUInt8 DEF_a__h7180;
    tUInt8 DEF_b__h7183;
    tUInt8 DEF_a__h7182;
    tUInt8 DEF_a__h9119;
    tUInt8 DEF_a__h9121;
    tUInt8 DEF_a__h11106;
    tUInt8 DEF_a__h11108;
    tUInt8 DEF_a__h13189;
    tUInt8 DEF_a__h13191;
    tUInt8 DEF_b__h5326;
    tUInt8 DEF_a__h5325;
    tUInt8 DEF_a__h7238;
    tUInt8 DEF_b__h7241;
    tUInt8 DEF_a__h7240;
    tUInt8 DEF_a__h9177;
    tUInt8 DEF_b__h9180;
    tUInt8 DEF_a__h9179;
    tUInt8 DEF_a__h11164;
    tUInt8 DEF_a__h11166;
    tUInt8 DEF_a__h13247;
    tUInt8 DEF_a__h13249;
    tUInt8 DEF_b__h5384;
    tUInt8 DEF_a__h5383;
    tUInt8 DEF_a__h7296;
    tUInt8 DEF_b__h7299;
    tUInt8 DEF_a__h7298;
    tUInt8 DEF_a__h9235;
    tUInt8 DEF_b__h9238;
    tUInt8 DEF_a__h9237;
    tUInt8 DEF_a__h11222;
    tUInt8 DEF_a__h11224;
    tUInt8 DEF_a__h13305;
    tUInt8 DEF_a__h13307;
    tUInt8 DEF_b__h5442;
    tUInt8 DEF_a__h5441;
    tUInt8 DEF_a__h7354;
    tUInt8 DEF_b__h7357;
    tUInt8 DEF_a__h7356;
    tUInt8 DEF_a__h9293;
    tUInt8 DEF_b__h9296;
    tUInt8 DEF_a__h9295;
    tUInt8 DEF_a__h11280;
    tUInt8 DEF_a__h11282;
    tUInt8 DEF_a__h13363;
    tUInt8 DEF_a__h13365;
    tUInt8 DEF_b__h5500;
    tUInt8 DEF_a__h5499;
    tUInt8 DEF_a__h7412;
    tUInt8 DEF_b__h7415;
    tUInt8 DEF_a__h7414;
    tUInt8 DEF_a__h9351;
    tUInt8 DEF_b__h9354;
    tUInt8 DEF_a__h9353;
    tUInt8 DEF_a__h11338;
    tUInt8 DEF_a__h11340;
    tUInt8 DEF_a__h13421;
    tUInt8 DEF_a__h13423;
    tUInt8 DEF_b__h5558;
    tUInt8 DEF_a__h5557;
    tUInt8 DEF_a__h7470;
    tUInt8 DEF_b__h7473;
    tUInt8 DEF_a__h7472;
    tUInt8 DEF_a__h9409;
    tUInt8 DEF_b__h9412;
    tUInt8 DEF_a__h9411;
    tUInt8 DEF_a__h11396;
    tUInt8 DEF_b__h11399;
    tUInt8 DEF_a__h11398;
    tUInt8 DEF_a__h13479;
    tUInt8 DEF_a__h13481;
    tUInt8 DEF_b__h5616;
    tUInt8 DEF_a__h5615;
    tUInt8 DEF_a__h7528;
    tUInt8 DEF_b__h7531;
    tUInt8 DEF_a__h7530;
    tUInt8 DEF_a__h9467;
    tUInt8 DEF_b__h9470;
    tUInt8 DEF_a__h9469;
    tUInt8 DEF_a__h11454;
    tUInt8 DEF_b__h11457;
    tUInt8 DEF_a__h11456;
    tUInt8 DEF_a__h13537;
    tUInt8 DEF_a__h13539;
    tUInt8 DEF_b__h5732;
    tUInt8 DEF_a__h5731;
    tUInt8 DEF_a__h7644;
    tUInt8 DEF_b__h7647;
    tUInt8 DEF_a__h7646;
    tUInt8 DEF_a__h9583;
    tUInt8 DEF_b__h9586;
    tUInt8 DEF_a__h9585;
    tUInt8 DEF_a__h11570;
    tUInt8 DEF_b__h11573;
    tUInt8 DEF_a__h11572;
    tUInt8 DEF_a__h13653;
    tUInt8 DEF_a__h13655;
    tUInt8 DEF_a__h13713;
    tUInt8 DEF_b__h5848;
    tUInt8 DEF_a__h5847;
    tUInt8 DEF_a__h7760;
    tUInt8 DEF_b__h7763;
    tUInt8 DEF_a__h7762;
    tUInt8 DEF_a__h9699;
    tUInt8 DEF_b__h9702;
    tUInt8 DEF_a__h9701;
    tUInt8 DEF_a__h11686;
    tUInt8 DEF_b__h11689;
    tUInt8 DEF_a__h11688;
    tUInt8 DEF_a__h13769;
    tUInt8 DEF_a__h13771;
    tUInt8 DEF_b__h5906;
    tUInt8 DEF_a__h5905;
    tUInt8 DEF_a__h7818;
    tUInt8 DEF_b__h7821;
    tUInt8 DEF_a__h7820;
    tUInt8 DEF_a__h9757;
    tUInt8 DEF_b__h9760;
    tUInt8 DEF_a__h9759;
    tUInt8 DEF_a__h11744;
    tUInt8 DEF_b__h11747;
    tUInt8 DEF_a__h11746;
    tUInt8 DEF_a__h13827;
    tUInt8 DEF_a__h13829;
    tUInt8 DEF_b__h5964;
    tUInt8 DEF_a__h5963;
    tUInt8 DEF_a__h7876;
    tUInt8 DEF_b__h7879;
    tUInt8 DEF_a__h7878;
    tUInt8 DEF_a__h9815;
    tUInt8 DEF_b__h9818;
    tUInt8 DEF_a__h9817;
    tUInt8 DEF_a__h11802;
    tUInt8 DEF_b__h11805;
    tUInt8 DEF_a__h11804;
    tUInt8 DEF_a__h13885;
    tUInt8 DEF_a__h13887;
    tUInt8 DEF_b__h6022;
    tUInt8 DEF_a__h6021;
    tUInt8 DEF_a__h7934;
    tUInt8 DEF_b__h7937;
    tUInt8 DEF_a__h7936;
    tUInt8 DEF_a__h9873;
    tUInt8 DEF_b__h9876;
    tUInt8 DEF_a__h9875;
    tUInt8 DEF_a__h11860;
    tUInt8 DEF_b__h11863;
    tUInt8 DEF_a__h11862;
    tUInt8 DEF_a__h13943;
    tUInt8 DEF_b__h13888;
    tUInt8 DEF_a__h13945;
    tUInt8 DEF_b__h6080;
    tUInt8 DEF_a__h6079;
    tUInt8 DEF_a__h7992;
    tUInt8 DEF_b__h7995;
    tUInt8 DEF_a__h7994;
    tUInt8 DEF_a__h9931;
    tUInt8 DEF_b__h9934;
    tUInt8 DEF_a__h9933;
    tUInt8 DEF_a__h11918;
    tUInt8 DEF_b__h11921;
    tUInt8 DEF_a__h11920;
    tUInt8 DEF_a__h14001;
    tUInt8 DEF_b__h14004;
    tUInt8 DEF_a__h14003;
    tUInt8 DEF_b__h6138;
    tUInt8 DEF_a__h6137;
    tUInt8 DEF_a__h8050;
    tUInt8 DEF_b__h8053;
    tUInt8 DEF_a__h8052;
    tUInt8 DEF_a__h9989;
    tUInt8 DEF_b__h9992;
    tUInt8 DEF_a__h9991;
    tUInt8 DEF_a__h11976;
    tUInt8 DEF_b__h11979;
    tUInt8 DEF_a__h11978;
    tUInt8 DEF_a__h14059;
    tUInt8 DEF_b__h14062;
    tUInt8 DEF_a__h14061;
    tUInt8 DEF_b__h6196;
    tUInt8 DEF_a__h6195;
    tUInt8 DEF_a__h8108;
    tUInt8 DEF_b__h8111;
    tUInt8 DEF_a__h8110;
    tUInt8 DEF_a__h10047;
    tUInt8 DEF_b__h10050;
    tUInt8 DEF_a__h10049;
    tUInt8 DEF_a__h12034;
    tUInt8 DEF_b__h12037;
    tUInt8 DEF_a__h12036;
    tUInt8 DEF_a__h14117;
    tUInt8 DEF_b__h14120;
    tUInt8 DEF_a__h14119;
    tUInt8 DEF_b__h6254;
    tUInt8 DEF_a__h6253;
    tUInt8 DEF_a__h8166;
    tUInt8 DEF_b__h8169;
    tUInt8 DEF_a__h8168;
    tUInt8 DEF_a__h10105;
    tUInt8 DEF_b__h10108;
    tUInt8 DEF_a__h10107;
    tUInt8 DEF_a__h12092;
    tUInt8 DEF_b__h12095;
    tUInt8 DEF_a__h12094;
    tUInt8 DEF_a__h14175;
    tUInt8 DEF_b__h14178;
    tUInt8 DEF_a__h14177;
    tUInt8 DEF_b__h6312;
    tUInt8 DEF_a__h6311;
    tUInt8 DEF_a__h8224;
    tUInt8 DEF_b__h8227;
    tUInt8 DEF_a__h8226;
    tUInt8 DEF_a__h10163;
    tUInt8 DEF_b__h10166;
    tUInt8 DEF_a__h10165;
    tUInt8 DEF_a__h12150;
    tUInt8 DEF_b__h12153;
    tUInt8 DEF_a__h12152;
    tUInt8 DEF_a__h14233;
    tUInt8 DEF_b__h14236;
    tUInt8 DEF_a__h14235;
    tUInt8 DEF_b__h6370;
    tUInt8 DEF_a__h6369;
    tUInt8 DEF_a__h8282;
    tUInt8 DEF_b__h8285;
    tUInt8 DEF_a__h8284;
    tUInt8 DEF_a__h10221;
    tUInt8 DEF_b__h10224;
    tUInt8 DEF_a__h10223;
    tUInt8 DEF_a__h12208;
    tUInt8 DEF_b__h12211;
    tUInt8 DEF_a__h12210;
    tUInt8 DEF_a__h14291;
    tUInt8 DEF_b__h14294;
    tUInt8 DEF_a__h14293;
    tUInt8 DEF_b__h6428;
    tUInt8 DEF_a__h6427;
    tUInt8 DEF_a__h8340;
    tUInt8 DEF_b__h8343;
    tUInt8 DEF_a__h8342;
    tUInt8 DEF_a__h10279;
    tUInt8 DEF_b__h10282;
    tUInt8 DEF_a__h10281;
    tUInt8 DEF_a__h12266;
    tUInt8 DEF_b__h12269;
    tUInt8 DEF_a__h12268;
    tUInt8 DEF_a__h14349;
    tUInt8 DEF_b__h14352;
    tUInt8 DEF_a__h14351;
    tUInt8 DEF_b__h6486;
    tUInt8 DEF_a__h6485;
    tUInt8 DEF_a__h8398;
    tUInt8 DEF_b__h8401;
    tUInt8 DEF_a__h8400;
    tUInt8 DEF_a__h10337;
    tUInt8 DEF_b__h10340;
    tUInt8 DEF_a__h10339;
    tUInt8 DEF_a__h12324;
    tUInt8 DEF_b__h12327;
    tUInt8 DEF_a__h12326;
    tUInt8 DEF_a__h14407;
    tUInt8 DEF_b__h14410;
    tUInt8 DEF_a__h14409;
    tUInt8 DEF_b__h6544;
    tUInt8 DEF_a__h6543;
    tUInt8 DEF_a__h8456;
    tUInt8 DEF_b__h8459;
    tUInt8 DEF_a__h8458;
    tUInt8 DEF_a__h10395;
    tUInt8 DEF_b__h10398;
    tUInt8 DEF_a__h10397;
    tUInt8 DEF_a__h12382;
    tUInt8 DEF_b__h12385;
    tUInt8 DEF_a__h12384;
    tUInt8 DEF_a__h14465;
    tUInt8 DEF_b__h14468;
    tUInt8 DEF_a__h14467;
    tUInt8 DEF_b__h6602;
    tUInt8 DEF_a__h6601;
    tUInt8 DEF_a__h8514;
    tUInt8 DEF_b__h8517;
    tUInt8 DEF_a__h8516;
    tUInt8 DEF_a__h10453;
    tUInt8 DEF_b__h10456;
    tUInt8 DEF_a__h10455;
    tUInt8 DEF_a__h12440;
    tUInt8 DEF_b__h12443;
    tUInt8 DEF_a__h12442;
    tUInt8 DEF_a__h14523;
    tUInt8 DEF_b__h14526;
    tUInt8 DEF_a__h14525;
    tUInt8 DEF_b__h6660;
    tUInt8 DEF_a__h6659;
    tUInt8 DEF_a__h8572;
    tUInt8 DEF_b__h8575;
    tUInt8 DEF_a__h8574;
    tUInt8 DEF_a__h10511;
    tUInt8 DEF_b__h10514;
    tUInt8 DEF_a__h10513;
    tUInt8 DEF_a__h12498;
    tUInt8 DEF_b__h12501;
    tUInt8 DEF_a__h12500;
    tUInt8 DEF_a__h14581;
    tUInt8 DEF_b__h14584;
    tUInt8 DEF_a__h14583;
    tUInt8 DEF_b__h6718;
    tUInt8 DEF_a__h6717;
    tUInt8 DEF_a__h8630;
    tUInt8 DEF_b__h8633;
    tUInt8 DEF_a__h8632;
    tUInt8 DEF_a__h10569;
    tUInt8 DEF_b__h10572;
    tUInt8 DEF_a__h10571;
    tUInt8 DEF_a__h12556;
    tUInt8 DEF_b__h12559;
    tUInt8 DEF_a__h12558;
    tUInt8 DEF_a__h14639;
    tUInt8 DEF_b__h14642;
    tUInt8 DEF_a__h14641;
    tUInt8 DEF_b__h6776;
    tUInt8 DEF_a__h6775;
    tUInt8 DEF_a__h8688;
    tUInt8 DEF_b__h8691;
    tUInt8 DEF_a__h8690;
    tUInt8 DEF_a__h10627;
    tUInt8 DEF_b__h10630;
    tUInt8 DEF_a__h10629;
    tUInt8 DEF_a__h12614;
    tUInt8 DEF_b__h12617;
    tUInt8 DEF_a__h12616;
    tUInt8 DEF_a__h14697;
    tUInt8 DEF_b__h14700;
    tUInt8 DEF_a__h14699;
    tUInt8 DEF_b__h6834;
    tUInt8 DEF_a__h6833;
    tUInt8 DEF_a__h8746;
    tUInt8 DEF_b__h8749;
    tUInt8 DEF_a__h8748;
    tUInt8 DEF_a__h10685;
    tUInt8 DEF_b__h10688;
    tUInt8 DEF_a__h10687;
    tUInt8 DEF_a__h12672;
    tUInt8 DEF_b__h12675;
    tUInt8 DEF_a__h12674;
    tUInt8 DEF_a__h14755;
    tUInt8 DEF_b__h6892;
    tUInt8 DEF_a__h6891;
    tUInt8 DEF_a__h8804;
    tUInt8 DEF_b__h8807;
    tUInt8 DEF_a__h8806;
    tUInt8 DEF_a__h10743;
    tUInt8 DEF_b__h10746;
    tUInt8 DEF_a__h10745;
    tUInt8 DEF_a__h12730;
    tUInt8 DEF_b__h12733;
    tUInt8 DEF_a__h12732;
    tUInt8 DEF_a__h14813;
    tUInt8 DEF_b__h14816;
    tUInt8 DEF_a__h14815;
    tUInt8 DEF_b__h6950;
    tUInt8 DEF_a__h6949;
    tUInt8 DEF_a__h8862;
    tUInt8 DEF_b__h8865;
    tUInt8 DEF_a__h8864;
    tUInt8 DEF_a__h10801;
    tUInt8 DEF_b__h10804;
    tUInt8 DEF_a__h10803;
    tUInt8 DEF_a__h12788;
    tUInt8 DEF_b__h12791;
    tUInt8 DEF_a__h12790;
    tUInt8 DEF_a__h14871;
    tUInt8 DEF_b__h14874;
    tUInt8 DEF_a__h14873;
    tUInt32 DEF_v__h834;
    tUInt32 DEF_trueResultA__h1696;
    tUInt8 DEF_a__h2557;
    tUInt8 DEF_a__h1715;
    tUInt8 DEF_a__h3399;
    tUInt8 DEF_a__h4241;
    tUInt8 DEF_a__h5083;
    tUInt8 DEF_NOT_cycle_EQ_128___d9;
    tUInt8 DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d528;
    tUInt32 DEF_x__h1709;
    tUInt8 DEF_sel__h4298;
    tUInt8 DEF_sel__h3456;
    tUInt8 DEF_sel__h2614;
    tUInt8 DEF_sel__h1772;
    tUInt8 DEF_sel__h905;
    tUInt8 DEF_a__h6947;
    tUInt8 DEF_a__h6889;
    tUInt8 DEF_a__h6831;
    tUInt8 DEF_a__h6773;
    tUInt8 DEF_a__h6715;
    tUInt8 DEF_a__h6657;
    tUInt8 DEF_a__h6599;
    tUInt8 DEF_a__h6541;
    tUInt8 DEF_a__h6483;
    tUInt8 DEF_a__h6425;
    tUInt8 DEF_a__h6367;
    tUInt8 DEF_a__h6309;
    tUInt8 DEF_a__h6251;
    tUInt8 DEF_a__h6193;
    tUInt8 DEF_a__h6135;
    tUInt8 DEF_a__h6077;
    tUInt8 DEF_a__h6019;
    tUInt8 DEF_a__h5961;
    tUInt8 DEF_a__h5903;
    tUInt8 DEF_a__h5845;
    tUInt8 DEF_a__h5787;
    tUInt8 DEF_a__h5729;
    tUInt8 DEF_a__h5671;
    tUInt8 DEF_a__h5613;
    tUInt8 DEF_a__h5555;
    tUInt8 DEF_a__h5497;
    tUInt8 DEF_a__h5439;
    tUInt8 DEF_a__h5381;
    tUInt8 DEF_a__h5323;
    tUInt8 DEF_a__h5265;
    tUInt8 DEF_a__h5207;
    tUInt8 DEF_b__h5208;
    tUInt8 DEF_TASK_getRandom_0_BITS_4_TO_0___d532;
    DEF_x__h370 = INST_cycle.METH_read();
    DEF_cycle_EQ_128___d6 = DEF_x__h370 == 128u;
    DEF_NOT_cycle_EQ_128___d9 = !DEF_cycle_EQ_128___d6;
    DEF_x__h15090 = DEF_x__h370 + 1u;
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      if (DEF_cycle_EQ_128___d6)
	dollar_display(this, "s", &__str_literal_1);
      if (DEF_cycle_EQ_128___d6)
	dollar_finish("32", 1u);
      if (DEF_NOT_cycle_EQ_128___d9)
	DEF_TASK_getRandom___d530 = getRandom();
    }
    DEF_b__h5208 = (tUInt8)(DEF_TASK_getRandom___d530 >> 31u);
    DEF_a__h5207 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 30u));
    DEF_a__h5265 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 29u));
    DEF_a__h5323 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 28u));
    DEF_a__h5381 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 27u));
    DEF_a__h5439 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 26u));
    DEF_a__h5497 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 25u));
    DEF_a__h5555 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 24u));
    DEF_a__h5613 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 23u));
    DEF_a__h5729 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 21u));
    DEF_a__h5671 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 22u));
    DEF_a__h5787 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 20u));
    DEF_a__h5845 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 19u));
    DEF_a__h5961 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 17u));
    DEF_a__h5903 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 18u));
    DEF_a__h6019 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 16u));
    DEF_a__h6077 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 15u));
    DEF_a__h6193 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 13u));
    DEF_a__h6135 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 14u));
    DEF_a__h6251 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 12u));
    DEF_a__h6309 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 11u));
    DEF_a__h6367 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 10u));
    DEF_a__h6541 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 7u));
    DEF_a__h6425 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 9u));
    DEF_a__h6599 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 6u));
    DEF_a__h6483 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 8u));
    DEF_a__h6657 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 5u));
    DEF_a__h6715 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 4u));
    DEF_a__h6831 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 2u));
    DEF_a__h6773 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 3u));
    DEF_a__h6889 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d530 >> 1u));
    DEF_a__h6947 = (tUInt8)((tUInt8)1u & DEF_TASK_getRandom___d530);
    if (!(PORT_RST_N == (tUInt8)0u))
      if (DEF_NOT_cycle_EQ_128___d9)
	DEF_TASK_getRandom___d531 = getRandom();
    DEF_TASK_getRandom_0_BITS_4_TO_0___d532 = (tUInt8)((tUInt8)31u & DEF_TASK_getRandom___d531);
    DEF_sel__h905 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d531 >> 4u));
    DEF_sel__h1772 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d531 >> 3u));
    DEF_sel__h2614 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d531 >> 2u));
    DEF_sel__h3456 = (tUInt8)((tUInt8)1u & (DEF_TASK_getRandom___d531 >> 1u));
    DEF_sel__h4298 = (tUInt8)((tUInt8)1u & DEF_TASK_getRandom___d531);
    DEF_a__h5083 = (tUInt8)1u & ~DEF_sel__h4298;
    DEF_a__h4241 = (tUInt8)1u & ~DEF_sel__h3456;
    DEF_a__h1715 = (tUInt8)1u & ~DEF_sel__h905;
    DEF_a__h3399 = (tUInt8)1u & ~DEF_sel__h2614;
    DEF_a__h2557 = (tUInt8)1u & ~DEF_sel__h1772;
    DEF_trueResultA__h1696 = primShiftRA32(32u,
					   32u,
					   (tUInt32)(DEF_TASK_getRandom___d530),
					   5u,
					   (tUInt8)(DEF_TASK_getRandom_0_BITS_4_TO_0___d532));
    DEF_a__h6949 = DEF_a__h5083 & DEF_a__h6947;
    DEF_b__h6950 = DEF_sel__h4298 & DEF_a__h6889;
    DEF_a__h8862 = DEF_a__h6949 | DEF_b__h6950;
    DEF_a__h8864 = DEF_a__h4241 & DEF_a__h8862;
    DEF_a__h6891 = DEF_a__h5083 & DEF_a__h6889;
    DEF_b__h6892 = DEF_sel__h4298 & DEF_a__h6831;
    DEF_a__h8804 = DEF_a__h6891 | DEF_b__h6892;
    DEF_a__h8806 = DEF_a__h4241 & DEF_a__h8804;
    DEF_a__h6833 = DEF_a__h5083 & DEF_a__h6831;
    DEF_b__h6834 = DEF_sel__h4298 & DEF_a__h6773;
    DEF_a__h8746 = DEF_a__h6833 | DEF_b__h6834;
    DEF_b__h8865 = DEF_sel__h3456 & DEF_a__h8746;
    DEF_a__h10801 = DEF_a__h8864 | DEF_b__h8865;
    DEF_a__h10803 = DEF_a__h3399 & DEF_a__h10801;
    DEF_a__h8748 = DEF_a__h4241 & DEF_a__h8746;
    DEF_a__h6659 = DEF_a__h5083 & DEF_a__h6657;
    DEF_a__h6775 = DEF_a__h5083 & DEF_a__h6773;
    DEF_b__h6776 = DEF_sel__h4298 & DEF_a__h6715;
    DEF_a__h8688 = DEF_a__h6775 | DEF_b__h6776;
    DEF_b__h8807 = DEF_sel__h3456 & DEF_a__h8688;
    DEF_a__h10743 = DEF_a__h8806 | DEF_b__h8807;
    DEF_a__h10745 = DEF_a__h3399 & DEF_a__h10743;
    DEF_a__h8690 = DEF_a__h4241 & DEF_a__h8688;
    DEF_a__h6717 = DEF_a__h5083 & DEF_a__h6715;
    DEF_b__h6718 = DEF_sel__h4298 & DEF_a__h6657;
    DEF_a__h8630 = DEF_a__h6717 | DEF_b__h6718;
    DEF_b__h8749 = DEF_sel__h3456 & DEF_a__h8630;
    DEF_a__h10685 = DEF_a__h8748 | DEF_b__h8749;
    DEF_a__h10687 = DEF_a__h3399 & DEF_a__h10685;
    DEF_a__h8632 = DEF_a__h4241 & DEF_a__h8630;
    DEF_b__h6660 = DEF_sel__h4298 & DEF_a__h6599;
    DEF_a__h8572 = DEF_a__h6659 | DEF_b__h6660;
    DEF_b__h8691 = DEF_sel__h3456 & DEF_a__h8572;
    DEF_a__h10627 = DEF_a__h8690 | DEF_b__h8691;
    DEF_a__h10629 = DEF_a__h3399 & DEF_a__h10627;
    DEF_a__h8574 = DEF_a__h4241 & DEF_a__h8572;
    DEF_a__h6601 = DEF_a__h5083 & DEF_a__h6599;
    DEF_b__h6602 = DEF_sel__h4298 & DEF_a__h6541;
    DEF_a__h8514 = DEF_a__h6601 | DEF_b__h6602;
    DEF_b__h8633 = DEF_sel__h3456 & DEF_a__h8514;
    DEF_a__h10569 = DEF_a__h8632 | DEF_b__h8633;
    DEF_b__h10804 = DEF_sel__h2614 & DEF_a__h10569;
    DEF_a__h12788 = DEF_a__h10803 | DEF_b__h10804;
    DEF_a__h12790 = DEF_a__h2557 & DEF_a__h12788;
    DEF_a__h10571 = DEF_a__h3399 & DEF_a__h10569;
    DEF_a__h8516 = DEF_a__h4241 & DEF_a__h8514;
    DEF_a__h6427 = DEF_a__h5083 & DEF_a__h6425;
    DEF_a__h6543 = DEF_a__h5083 & DEF_a__h6541;
    DEF_b__h6544 = DEF_sel__h4298 & DEF_a__h6483;
    DEF_a__h8456 = DEF_a__h6543 | DEF_b__h6544;
    DEF_b__h8575 = DEF_sel__h3456 & DEF_a__h8456;
    DEF_a__h10511 = DEF_a__h8574 | DEF_b__h8575;
    DEF_b__h10746 = DEF_sel__h2614 & DEF_a__h10511;
    DEF_a__h12730 = DEF_a__h10745 | DEF_b__h10746;
    DEF_a__h12732 = DEF_a__h2557 & DEF_a__h12730;
    DEF_a__h10513 = DEF_a__h3399 & DEF_a__h10511;
    DEF_a__h8458 = DEF_a__h4241 & DEF_a__h8456;
    DEF_a__h6485 = DEF_a__h5083 & DEF_a__h6483;
    DEF_b__h6486 = DEF_sel__h4298 & DEF_a__h6425;
    DEF_a__h8398 = DEF_a__h6485 | DEF_b__h6486;
    DEF_b__h8517 = DEF_sel__h3456 & DEF_a__h8398;
    DEF_a__h10453 = DEF_a__h8516 | DEF_b__h8517;
    DEF_b__h10688 = DEF_sel__h2614 & DEF_a__h10453;
    DEF_a__h12672 = DEF_a__h10687 | DEF_b__h10688;
    DEF_a__h12674 = DEF_a__h2557 & DEF_a__h12672;
    DEF_a__h10455 = DEF_a__h3399 & DEF_a__h10453;
    DEF_a__h8400 = DEF_a__h4241 & DEF_a__h8398;
    DEF_b__h6428 = DEF_sel__h4298 & DEF_a__h6367;
    DEF_a__h8340 = DEF_a__h6427 | DEF_b__h6428;
    DEF_b__h8459 = DEF_sel__h3456 & DEF_a__h8340;
    DEF_a__h10395 = DEF_a__h8458 | DEF_b__h8459;
    DEF_b__h10630 = DEF_sel__h2614 & DEF_a__h10395;
    DEF_a__h12614 = DEF_a__h10629 | DEF_b__h10630;
    DEF_a__h12616 = DEF_a__h2557 & DEF_a__h12614;
    DEF_a__h10397 = DEF_a__h3399 & DEF_a__h10395;
    DEF_a__h8342 = DEF_a__h4241 & DEF_a__h8340;
    DEF_a__h6369 = DEF_a__h5083 & DEF_a__h6367;
    DEF_b__h6370 = DEF_sel__h4298 & DEF_a__h6309;
    DEF_a__h8282 = DEF_a__h6369 | DEF_b__h6370;
    DEF_b__h8401 = DEF_sel__h3456 & DEF_a__h8282;
    DEF_a__h10337 = DEF_a__h8400 | DEF_b__h8401;
    DEF_b__h10572 = DEF_sel__h2614 & DEF_a__h10337;
    DEF_a__h12556 = DEF_a__h10571 | DEF_b__h10572;
    DEF_a__h12558 = DEF_a__h2557 & DEF_a__h12556;
    DEF_a__h10339 = DEF_a__h3399 & DEF_a__h10337;
    DEF_a__h8284 = DEF_a__h4241 & DEF_a__h8282;
    DEF_a__h6311 = DEF_a__h5083 & DEF_a__h6309;
    DEF_b__h6312 = DEF_sel__h4298 & DEF_a__h6251;
    DEF_a__h8224 = DEF_a__h6311 | DEF_b__h6312;
    DEF_b__h8343 = DEF_sel__h3456 & DEF_a__h8224;
    DEF_a__h10279 = DEF_a__h8342 | DEF_b__h8343;
    DEF_b__h10514 = DEF_sel__h2614 & DEF_a__h10279;
    DEF_a__h12498 = DEF_a__h10513 | DEF_b__h10514;
    DEF_a__h12500 = DEF_a__h2557 & DEF_a__h12498;
    DEF_a__h10281 = DEF_a__h3399 & DEF_a__h10279;
    DEF_a__h8226 = DEF_a__h4241 & DEF_a__h8224;
    DEF_a__h6253 = DEF_a__h5083 & DEF_a__h6251;
    DEF_b__h6254 = DEF_sel__h4298 & DEF_a__h6193;
    DEF_a__h8166 = DEF_a__h6253 | DEF_b__h6254;
    DEF_b__h8285 = DEF_sel__h3456 & DEF_a__h8166;
    DEF_a__h10221 = DEF_a__h8284 | DEF_b__h8285;
    DEF_b__h10456 = DEF_sel__h2614 & DEF_a__h10221;
    DEF_a__h12440 = DEF_a__h10455 | DEF_b__h10456;
    DEF_a__h12442 = DEF_a__h2557 & DEF_a__h12440;
    DEF_a__h10223 = DEF_a__h3399 & DEF_a__h10221;
    DEF_a__h8168 = DEF_a__h4241 & DEF_a__h8166;
    DEF_a__h6195 = DEF_a__h5083 & DEF_a__h6193;
    DEF_b__h6196 = DEF_sel__h4298 & DEF_a__h6135;
    DEF_a__h8108 = DEF_a__h6195 | DEF_b__h6196;
    DEF_b__h8227 = DEF_sel__h3456 & DEF_a__h8108;
    DEF_a__h10163 = DEF_a__h8226 | DEF_b__h8227;
    DEF_b__h10398 = DEF_sel__h2614 & DEF_a__h10163;
    DEF_a__h12382 = DEF_a__h10397 | DEF_b__h10398;
    DEF_a__h12384 = DEF_a__h2557 & DEF_a__h12382;
    DEF_a__h10165 = DEF_a__h3399 & DEF_a__h10163;
    DEF_a__h8110 = DEF_a__h4241 & DEF_a__h8108;
    DEF_a__h6137 = DEF_a__h5083 & DEF_a__h6135;
    DEF_b__h6138 = DEF_sel__h4298 & DEF_a__h6077;
    DEF_a__h8050 = DEF_a__h6137 | DEF_b__h6138;
    DEF_b__h8169 = DEF_sel__h3456 & DEF_a__h8050;
    DEF_a__h10105 = DEF_a__h8168 | DEF_b__h8169;
    DEF_b__h10340 = DEF_sel__h2614 & DEF_a__h10105;
    DEF_a__h12324 = DEF_a__h10339 | DEF_b__h10340;
    DEF_b__h12791 = DEF_sel__h1772 & DEF_a__h12324;
    DEF_a__h14871 = DEF_a__h12790 | DEF_b__h12791;
    DEF_a__h14873 = DEF_a__h1715 & DEF_a__h14871;
    DEF_a__h12326 = DEF_a__h2557 & DEF_a__h12324;
    DEF_a__h10107 = DEF_a__h3399 & DEF_a__h10105;
    DEF_a__h8052 = DEF_a__h4241 & DEF_a__h8050;
    DEF_a__h6079 = DEF_a__h5083 & DEF_a__h6077;
    DEF_b__h6080 = DEF_sel__h4298 & DEF_a__h6019;
    DEF_a__h7992 = DEF_a__h6079 | DEF_b__h6080;
    DEF_b__h8111 = DEF_sel__h3456 & DEF_a__h7992;
    DEF_a__h10047 = DEF_a__h8110 | DEF_b__h8111;
    DEF_b__h10282 = DEF_sel__h2614 & DEF_a__h10047;
    DEF_a__h12266 = DEF_a__h10281 | DEF_b__h10282;
    DEF_b__h12733 = DEF_sel__h1772 & DEF_a__h12266;
    DEF_a__h14813 = DEF_a__h12732 | DEF_b__h12733;
    DEF_a__h14815 = DEF_a__h1715 & DEF_a__h14813;
    DEF_a__h12268 = DEF_a__h2557 & DEF_a__h12266;
    DEF_a__h10049 = DEF_a__h3399 & DEF_a__h10047;
    DEF_a__h7994 = DEF_a__h4241 & DEF_a__h7992;
    DEF_b__h13888 = DEF_sel__h905 & DEF_b__h5208;
    DEF_a__h6021 = DEF_a__h5083 & DEF_a__h6019;
    DEF_b__h6022 = DEF_sel__h4298 & DEF_a__h5961;
    DEF_a__h7934 = DEF_a__h6021 | DEF_b__h6022;
    DEF_b__h8053 = DEF_sel__h3456 & DEF_a__h7934;
    DEF_a__h9989 = DEF_a__h8052 | DEF_b__h8053;
    DEF_b__h10224 = DEF_sel__h2614 & DEF_a__h9989;
    DEF_a__h12208 = DEF_a__h10223 | DEF_b__h10224;
    DEF_b__h12675 = DEF_sel__h1772 & DEF_a__h12208;
    DEF_a__h14755 = DEF_a__h12674 | DEF_b__h12675;
    DEF_a__h12210 = DEF_a__h2557 & DEF_a__h12208;
    DEF_a__h9991 = DEF_a__h3399 & DEF_a__h9989;
    DEF_a__h7936 = DEF_a__h4241 & DEF_a__h7934;
    DEF_a__h5963 = DEF_a__h5083 & DEF_a__h5961;
    DEF_b__h5964 = DEF_sel__h4298 & DEF_a__h5903;
    DEF_a__h7876 = DEF_a__h5963 | DEF_b__h5964;
    DEF_b__h7995 = DEF_sel__h3456 & DEF_a__h7876;
    DEF_a__h9931 = DEF_a__h7994 | DEF_b__h7995;
    DEF_b__h10166 = DEF_sel__h2614 & DEF_a__h9931;
    DEF_a__h12150 = DEF_a__h10165 | DEF_b__h10166;
    DEF_b__h12617 = DEF_sel__h1772 & DEF_a__h12150;
    DEF_a__h14697 = DEF_a__h12616 | DEF_b__h12617;
    DEF_a__h14699 = DEF_a__h1715 & DEF_a__h14697;
    DEF_a__h12152 = DEF_a__h2557 & DEF_a__h12150;
    DEF_a__h9933 = DEF_a__h3399 & DEF_a__h9931;
    DEF_a__h7878 = DEF_a__h4241 & DEF_a__h7876;
    DEF_a__h5905 = DEF_a__h5083 & DEF_a__h5903;
    DEF_b__h5906 = DEF_sel__h4298 & DEF_a__h5845;
    DEF_a__h7818 = DEF_a__h5905 | DEF_b__h5906;
    DEF_b__h7937 = DEF_sel__h3456 & DEF_a__h7818;
    DEF_a__h9873 = DEF_a__h7936 | DEF_b__h7937;
    DEF_b__h10108 = DEF_sel__h2614 & DEF_a__h9873;
    DEF_a__h12092 = DEF_a__h10107 | DEF_b__h10108;
    DEF_b__h12559 = DEF_sel__h1772 & DEF_a__h12092;
    DEF_a__h14639 = DEF_a__h12558 | DEF_b__h12559;
    DEF_a__h14641 = DEF_a__h1715 & DEF_a__h14639;
    DEF_a__h12094 = DEF_a__h2557 & DEF_a__h12092;
    DEF_a__h9875 = DEF_a__h3399 & DEF_a__h9873;
    DEF_a__h7820 = DEF_a__h4241 & DEF_a__h7818;
    DEF_a__h5847 = DEF_a__h5083 & DEF_a__h5845;
    DEF_b__h5848 = DEF_sel__h4298 & DEF_a__h5787;
    DEF_a__h7760 = DEF_a__h5847 | DEF_b__h5848;
    DEF_b__h7879 = DEF_sel__h3456 & DEF_a__h7760;
    DEF_a__h9815 = DEF_a__h7878 | DEF_b__h7879;
    DEF_b__h10050 = DEF_sel__h2614 & DEF_a__h9815;
    DEF_a__h12034 = DEF_a__h10049 | DEF_b__h10050;
    DEF_b__h12501 = DEF_sel__h1772 & DEF_a__h12034;
    DEF_a__h14581 = DEF_a__h12500 | DEF_b__h12501;
    DEF_a__h14583 = DEF_a__h1715 & DEF_a__h14581;
    DEF_a__h12036 = DEF_a__h2557 & DEF_a__h12034;
    DEF_a__h9817 = DEF_a__h3399 & DEF_a__h9815;
    DEF_a__h7762 = DEF_a__h4241 & DEF_a__h7760;
    DEF_a__h5731 = DEF_a__h5083 & DEF_a__h5729;
    DEF_b__h5732 = DEF_sel__h4298 & DEF_a__h5671;
    DEF_a__h7644 = DEF_a__h5731 | DEF_b__h5732;
    DEF_b__h7763 = DEF_sel__h3456 & DEF_a__h7644;
    DEF_a__h9699 = DEF_a__h7762 | DEF_b__h7763;
    DEF_b__h9934 = DEF_sel__h2614 & DEF_a__h9699;
    DEF_a__h11918 = DEF_a__h9933 | DEF_b__h9934;
    DEF_b__h12385 = DEF_sel__h1772 & DEF_a__h11918;
    DEF_a__h14465 = DEF_a__h12384 | DEF_b__h12385;
    DEF_a__h14467 = DEF_a__h1715 & DEF_a__h14465;
    DEF_a__h11920 = DEF_a__h2557 & DEF_a__h11918;
    DEF_a__h9701 = DEF_a__h3399 & DEF_a__h9699;
    DEF_a__h7646 = DEF_a__h4241 & DEF_a__h7644;
    DEF_a__h5615 = DEF_a__h5083 & DEF_a__h5613;
    DEF_b__h5616 = DEF_sel__h4298 & DEF_a__h5555;
    DEF_a__h7528 = DEF_a__h5615 | DEF_b__h5616;
    DEF_b__h7647 = DEF_sel__h3456 & DEF_a__h7528;
    DEF_a__h9583 = DEF_a__h7646 | DEF_b__h7647;
    DEF_b__h9818 = DEF_sel__h2614 & DEF_a__h9583;
    DEF_a__h11802 = DEF_a__h9817 | DEF_b__h9818;
    DEF_b__h12269 = DEF_sel__h1772 & DEF_a__h11802;
    DEF_a__h14349 = DEF_a__h12268 | DEF_b__h12269;
    DEF_a__h14351 = DEF_a__h1715 & DEF_a__h14349;
    DEF_a__h11804 = DEF_a__h2557 & DEF_a__h11802;
    DEF_a__h9585 = DEF_a__h3399 & DEF_a__h9583;
    DEF_a__h7530 = DEF_a__h4241 & DEF_a__h7528;
    DEF_b__h11399 = DEF_sel__h1772 & DEF_b__h5208;
    DEF_a__h5557 = DEF_a__h5083 & DEF_a__h5555;
    DEF_b__h5558 = DEF_sel__h4298 & DEF_a__h5497;
    DEF_a__h7470 = DEF_a__h5557 | DEF_b__h5558;
    DEF_a__h7472 = DEF_a__h4241 & DEF_a__h7470;
    DEF_a__h5499 = DEF_a__h5083 & DEF_a__h5497;
    DEF_b__h5500 = DEF_sel__h4298 & DEF_a__h5439;
    DEF_a__h7412 = DEF_a__h5499 | DEF_b__h5500;
    DEF_b__h7531 = DEF_sel__h3456 & DEF_a__h7412;
    DEF_a__h9467 = DEF_a__h7530 | DEF_b__h7531;
    DEF_b__h9702 = DEF_sel__h2614 & DEF_a__h9467;
    DEF_a__h11686 = DEF_a__h9701 | DEF_b__h9702;
    DEF_b__h12153 = DEF_sel__h1772 & DEF_a__h11686;
    DEF_a__h14233 = DEF_a__h12152 | DEF_b__h12153;
    DEF_a__h14235 = DEF_a__h1715 & DEF_a__h14233;
    DEF_a__h11688 = DEF_a__h2557 & DEF_a__h11686;
    DEF_a__h9469 = DEF_a__h3399 & DEF_a__h9467;
    DEF_a__h7414 = DEF_a__h4241 & DEF_a__h7412;
    DEF_a__h5441 = DEF_a__h5083 & DEF_a__h5439;
    DEF_b__h5442 = DEF_sel__h4298 & DEF_a__h5381;
    DEF_a__h7354 = DEF_a__h5441 | DEF_b__h5442;
    DEF_b__h7473 = DEF_sel__h3456 & DEF_a__h7354;
    DEF_a__h9409 = DEF_a__h7472 | DEF_b__h7473;
    DEF_a__h9411 = DEF_a__h3399 & DEF_a__h9409;
    DEF_a__h7356 = DEF_a__h4241 & DEF_a__h7354;
    DEF_a__h5383 = DEF_a__h5083 & DEF_a__h5381;
    DEF_b__h5384 = DEF_sel__h4298 & DEF_a__h5323;
    DEF_a__h7296 = DEF_a__h5383 | DEF_b__h5384;
    DEF_b__h7415 = DEF_sel__h3456 & DEF_a__h7296;
    DEF_a__h9351 = DEF_a__h7414 | DEF_b__h7415;
    DEF_b__h9586 = DEF_sel__h2614 & DEF_a__h9351;
    DEF_a__h11570 = DEF_a__h9585 | DEF_b__h9586;
    DEF_b__h12037 = DEF_sel__h1772 & DEF_a__h11570;
    DEF_a__h14117 = DEF_a__h12036 | DEF_b__h12037;
    DEF_a__h14119 = DEF_a__h1715 & DEF_a__h14117;
    DEF_a__h11572 = DEF_a__h2557 & DEF_a__h11570;
    DEF_a__h9353 = DEF_a__h3399 & DEF_a__h9351;
    DEF_a__h7298 = DEF_a__h4241 & DEF_a__h7296;
    DEF_b__h9180 = DEF_sel__h2614 & DEF_b__h5208;
    DEF_a__h5325 = DEF_a__h5083 & DEF_a__h5323;
    DEF_b__h5326 = DEF_sel__h4298 & DEF_a__h5265;
    DEF_a__h7238 = DEF_a__h5325 | DEF_b__h5326;
    DEF_b__h7357 = DEF_sel__h3456 & DEF_a__h7238;
    DEF_a__h9293 = DEF_a__h7356 | DEF_b__h7357;
    DEF_a__h9295 = DEF_a__h3399 & DEF_a__h9293;
    DEF_a__h7240 = DEF_a__h4241 & DEF_a__h7238;
    DEF_a__h5267 = DEF_a__h5083 & DEF_a__h5265;
    DEF_b__h5268 = DEF_sel__h4298 & DEF_a__h5207;
    DEF_a__h7180 = DEF_a__h5267 | DEF_b__h5268;
    DEF_b__h7299 = DEF_sel__h3456 & DEF_a__h7180;
    DEF_a__h9235 = DEF_a__h7298 | DEF_b__h7299;
    DEF_b__h9470 = DEF_sel__h2614 & DEF_a__h9235;
    DEF_a__h11454 = DEF_a__h9469 | DEF_b__h9470;
    DEF_b__h11921 = DEF_sel__h1772 & DEF_a__h11454;
    DEF_a__h14001 = DEF_a__h11920 | DEF_b__h11921;
    DEF_a__h14003 = DEF_a__h1715 & DEF_a__h14001;
    DEF_a__h11456 = DEF_a__h2557 & DEF_a__h11454;
    DEF_a__h9237 = DEF_a__h3399 & DEF_a__h9235;
    DEF_a__h7182 = DEF_a__h4241 & DEF_a__h7180;
    DEF_b__h7125 = DEF_sel__h3456 & DEF_b__h5208;
    DEF_a__h14757 = DEF_a__h1715 & DEF_a__h14755;
    DEF_b__h9644 = DEF_sel__h2614 & DEF_a__h9409;
    DEF_a__h5789 = DEF_a__h5083 & DEF_a__h5787;
    DEF_b__h5790 = DEF_sel__h4298 & DEF_a__h5729;
    DEF_a__h7702 = DEF_a__h5789 | DEF_b__h5790;
    DEF_b__h7821 = DEF_sel__h3456 & DEF_a__h7702;
    DEF_a__h9757 = DEF_a__h7820 | DEF_b__h7821;
    DEF_b__h9992 = DEF_sel__h2614 & DEF_a__h9757;
    DEF_a__h11976 = DEF_a__h9991 | DEF_b__h9992;
    DEF_b__h12443 = DEF_sel__h1772 & DEF_a__h11976;
    DEF_a__h14523 = DEF_a__h12442 | DEF_b__h12443;
    DEF_a__h14525 = DEF_a__h1715 & DEF_a__h14523;
    DEF_a__h11978 = DEF_a__h2557 & DEF_a__h11976;
    DEF_a__h9759 = DEF_a__h3399 & DEF_a__h9757;
    DEF_a__h7704 = DEF_a__h4241 & DEF_a__h7702;
    DEF_b__h9528 = DEF_sel__h2614 & DEF_a__h9293;
    DEF_b__h7589 = DEF_sel__h3456 & DEF_a__h7470;
    DEF_a__h5673 = DEF_a__h5083 & DEF_a__h5671;
    DEF_b__h5674 = DEF_sel__h4298 & DEF_a__h5613;
    DEF_a__h7586 = DEF_a__h5673 | DEF_b__h5674;
    DEF_b__h7705 = DEF_sel__h3456 & DEF_a__h7586;
    DEF_a__h9641 = DEF_a__h7704 | DEF_b__h7705;
    DEF_b__h9876 = DEF_sel__h2614 & DEF_a__h9641;
    DEF_a__h11860 = DEF_a__h9875 | DEF_b__h9876;
    DEF_b__h12327 = DEF_sel__h1772 & DEF_a__h11860;
    DEF_a__h14407 = DEF_a__h12326 | DEF_b__h12327;
    DEF_a__h14409 = DEF_a__h1715 & DEF_a__h14407;
    DEF_a__h11862 = DEF_a__h2557 & DEF_a__h11860;
    DEF_a__h9643 = DEF_a__h3399 & DEF_a__h9641;
    DEF_a__h11628 = DEF_a__h9643 | DEF_b__h9644;
    DEF_b__h12095 = DEF_sel__h1772 & DEF_a__h11628;
    DEF_a__h14175 = DEF_a__h12094 | DEF_b__h12095;
    DEF_a__h14177 = DEF_a__h1715 & DEF_a__h14175;
    DEF_a__h11630 = DEF_a__h2557 & DEF_a__h11628;
    DEF_a__h7588 = DEF_a__h4241 & DEF_a__h7586;
    DEF_a__h9525 = DEF_a__h7588 | DEF_b__h7589;
    DEF_b__h9760 = DEF_sel__h2614 & DEF_a__h9525;
    DEF_a__h11744 = DEF_a__h9759 | DEF_b__h9760;
    DEF_b__h12211 = DEF_sel__h1772 & DEF_a__h11744;
    DEF_a__h14291 = DEF_a__h12210 | DEF_b__h12211;
    DEF_a__h14293 = DEF_a__h1715 & DEF_a__h14291;
    DEF_a__h11746 = DEF_a__h2557 & DEF_a__h11744;
    DEF_a__h9527 = DEF_a__h3399 & DEF_a__h9525;
    DEF_a__h11512 = DEF_a__h9527 | DEF_b__h9528;
    DEF_b__h11979 = DEF_sel__h1772 & DEF_a__h11512;
    DEF_a__h14059 = DEF_a__h11978 | DEF_b__h11979;
    DEF_a__h14061 = DEF_a__h1715 & DEF_a__h14059;
    DEF_a__h11514 = DEF_a__h2557 & DEF_a__h11512;
    DEF_a__h5209 = DEF_a__h5083 & DEF_a__h5207;
    DEF_b__h5210 = DEF_sel__h4298 & DEF_b__h5208;
    DEF_a__h7122 = DEF_a__h5209 | DEF_b__h5210;
    DEF_b__h7241 = DEF_sel__h3456 & DEF_a__h7122;
    DEF_a__h9177 = DEF_a__h7240 | DEF_b__h7241;
    DEF_b__h9412 = DEF_sel__h2614 & DEF_a__h9177;
    DEF_a__h11396 = DEF_a__h9411 | DEF_b__h9412;
    DEF_b__h11863 = DEF_sel__h1772 & DEF_a__h11396;
    DEF_a__h13943 = DEF_a__h11862 | DEF_b__h11863;
    DEF_b__h14874 = DEF_sel__h905 & DEF_a__h13943;
    DEF_a__h13945 = DEF_a__h1715 & DEF_a__h13943;
    DEF_a__h11398 = DEF_a__h2557 & DEF_a__h11396;
    DEF_a__h13479 = DEF_a__h11398 | DEF_b__h11399;
    DEF_b__h14410 = DEF_sel__h905 & DEF_a__h13479;
    DEF_a__h13481 = DEF_a__h1715 & DEF_a__h13479;
    DEF_a__h9179 = DEF_a__h3399 & DEF_a__h9177;
    DEF_a__h11164 = DEF_a__h9179 | DEF_b__h9180;
    DEF_a__h11166 = DEF_a__h2557 & DEF_a__h11164;
    DEF_a__h13247 = DEF_a__h11166 | DEF_b__h11399;
    DEF_b__h14178 = DEF_sel__h905 & DEF_a__h13247;
    DEF_a__h13249 = DEF_a__h1715 & DEF_a__h13247;
    DEF_a__h7124 = DEF_a__h4241 & DEF_a__h7122;
    DEF_a__h9061 = DEF_a__h7124 | DEF_b__h7125;
    DEF_b__h9296 = DEF_sel__h2614 & DEF_a__h9061;
    DEF_a__h11280 = DEF_a__h9295 | DEF_b__h9296;
    DEF_b__h11747 = DEF_sel__h1772 & DEF_a__h11280;
    DEF_a__h13827 = DEF_a__h11746 | DEF_b__h11747;
    DEF_a__h13829 = DEF_a__h1715 & DEF_a__h13827;
    DEF_a__h11282 = DEF_a__h2557 & DEF_a__h11280;
    DEF_a__h13363 = DEF_a__h11282 | DEF_b__h11399;
    DEF_b__h14294 = DEF_sel__h905 & DEF_a__h13363;
    DEF_a__h13365 = DEF_a__h1715 & DEF_a__h13363;
    DEF_b__h14758 = DEF_sel__h905 & DEF_a__h13827;
    DEF_b__h11631 = DEF_sel__h1772 & DEF_a__h11164;
    DEF_a__h13711 = DEF_a__h11630 | DEF_b__h11631;
    DEF_b__h14642 = DEF_sel__h905 & DEF_a__h13711;
    DEF_a__h13713 = DEF_a__h1715 & DEF_a__h13711;
    DEF_a__h9063 = DEF_a__h3399 & DEF_a__h9061;
    DEF_a__h11048 = DEF_a__h9063 | DEF_b__h9180;
    DEF_a__h11050 = DEF_a__h2557 & DEF_a__h11048;
    DEF_a__h13131 = DEF_a__h11050 | DEF_b__h11399;
    DEF_b__h14062 = DEF_sel__h905 & DEF_a__h13131;
    DEF_a__h13133 = DEF_a__h1715 & DEF_a__h13131;
    DEF_b__h11515 = DEF_sel__h1772 & DEF_a__h11048;
    DEF_a__h13595 = DEF_a__h11514 | DEF_b__h11515;
    DEF_b__h14526 = DEF_sel__h905 & DEF_a__h13595;
    DEF_a__h13597 = DEF_a__h1715 & DEF_a__h13595;
    DEF_a__h5081 = DEF_a__h5083 & DEF_b__h5208;
    DEF_b__h7181 = DEF_a__h5081 | DEF_b__h5210;
    DEF_b__h7183 = DEF_sel__h3456 & DEF_b__h7181;
    DEF_a__h9119 = DEF_a__h7182 | DEF_b__h7183;
    DEF_b__h9354 = DEF_sel__h2614 & DEF_a__h9119;
    DEF_a__h11338 = DEF_a__h9353 | DEF_b__h9354;
    DEF_b__h11805 = DEF_sel__h1772 & DEF_a__h11338;
    DEF_a__h13885 = DEF_a__h11804 | DEF_b__h11805;
    DEF_b__h14816 = DEF_sel__h905 & DEF_a__h13885;
    DEF_a__h13887 = DEF_a__h1715 & DEF_a__h13885;
    DEF_a__h11340 = DEF_a__h2557 & DEF_a__h11338;
    DEF_a__h13421 = DEF_a__h11340 | DEF_b__h11399;
    DEF_b__h14352 = DEF_sel__h905 & DEF_a__h13421;
    DEF_a__h13423 = DEF_a__h1715 & DEF_a__h13421;
    DEF_a__h9121 = DEF_a__h3399 & DEF_a__h9119;
    DEF_a__h11106 = DEF_a__h9121 | DEF_b__h9180;
    DEF_b__h11573 = DEF_sel__h1772 & DEF_a__h11106;
    DEF_a__h13653 = DEF_a__h11572 | DEF_b__h11573;
    DEF_b__h14584 = DEF_sel__h905 & DEF_a__h13653;
    DEF_a__h13655 = DEF_a__h1715 & DEF_a__h13653;
    DEF_a__h11108 = DEF_a__h2557 & DEF_a__h11106;
    DEF_a__h13189 = DEF_a__h11108 | DEF_b__h11399;
    DEF_b__h14120 = DEF_sel__h905 & DEF_a__h13189;
    DEF_a__h13191 = DEF_a__h1715 & DEF_a__h13189;
    DEF_a__h4239 = DEF_a__h4241 & DEF_b__h7181;
    DEF_b__h9236 = DEF_a__h4239 | DEF_b__h7125;
    DEF_b__h9238 = DEF_sel__h2614 & DEF_b__h9236;
    DEF_a__h11222 = DEF_a__h9237 | DEF_b__h9238;
    DEF_b__h11689 = DEF_sel__h1772 & DEF_a__h11222;
    DEF_a__h13769 = DEF_a__h11688 | DEF_b__h11689;
    DEF_b__h14700 = DEF_sel__h905 & DEF_a__h13769;
    DEF_a__h13771 = DEF_a__h1715 & DEF_a__h13769;
    DEF_a__h11224 = DEF_a__h2557 & DEF_a__h11222;
    DEF_a__h13305 = DEF_a__h11224 | DEF_b__h11399;
    DEF_b__h14236 = DEF_sel__h905 & DEF_a__h13305;
    DEF_a__h13307 = DEF_a__h1715 & DEF_a__h13305;
    DEF_a__h3397 = DEF_a__h3399 & DEF_b__h9236;
    DEF_b__h11455 = DEF_a__h3397 | DEF_b__h9180;
    DEF_b__h11457 = DEF_sel__h1772 & DEF_b__h11455;
    DEF_a__h13537 = DEF_a__h11456 | DEF_b__h11457;
    DEF_b__h14468 = DEF_sel__h905 & DEF_a__h13537;
    DEF_a__h13539 = DEF_a__h1715 & DEF_a__h13537;
    DEF_a__h2555 = DEF_a__h2557 & DEF_b__h11455;
    DEF_a__h1711 = DEF_a__h2555 | DEF_b__h11399;
    DEF_b__h14004 = DEF_sel__h905 & DEF_a__h1711;
    DEF_a__h1713 = DEF_a__h1715 & DEF_a__h1711;
    DEF_v__h834 = ((65535u & ((((tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h1713 | DEF_b__h13888) << 1u) | (DEF_a__h13133 | DEF_b__h13888))) << 2u) | ((tUInt8)3u & (((DEF_a__h13191 | DEF_b__h13888) << 1u) | (DEF_a__h13249 | DEF_b__h13888))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h13307 | DEF_b__h13888) << 1u) | (DEF_a__h13365 | DEF_b__h13888))) << 2u) | ((tUInt8)3u & (((DEF_a__h13423 | DEF_b__h13888) << 1u) | (DEF_a__h13481 | DEF_b__h13888)))))))) << 8u) | (tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h13539 | DEF_b__h13888) << 1u) | (DEF_a__h13597 | DEF_b__h13888))) << 2u) | ((tUInt8)3u & (((DEF_a__h13655 | DEF_b__h13888) << 1u) | (DEF_a__h13713 | DEF_b__h13888))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h13771 | DEF_b__h13888) << 1u) | (DEF_a__h13829 | DEF_b__h13888))) << 2u) | ((tUInt8)3u & (((DEF_a__h13887 | DEF_b__h13888) << 1u) | (DEF_a__h13945 | DEF_b__h13888))))))))) << 16u) | (65535u & ((((tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14003 | DEF_b__h14004) << 1u) | (DEF_a__h14061 | DEF_b__h14062))) << 2u) | ((tUInt8)3u & (((DEF_a__h14119 | DEF_b__h14120) << 1u) | (DEF_a__h14177 | DEF_b__h14178))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14235 | DEF_b__h14236) << 1u) | (DEF_a__h14293 | DEF_b__h14294))) << 2u) | ((tUInt8)3u & (((DEF_a__h14351 | DEF_b__h14352) << 1u) | (DEF_a__h14409 | DEF_b__h14410)))))))) << 8u) | (tUInt32)((tUInt8)255u & ((((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14467 | DEF_b__h14468) << 1u) | (DEF_a__h14525 | DEF_b__h14526))) << 2u) | ((tUInt8)3u & (((DEF_a__h14583 | DEF_b__h14584) << 1u) | (DEF_a__h14641 | DEF_b__h14642))))) << 4u) | ((tUInt8)15u & ((((tUInt8)3u & (((DEF_a__h14699 | DEF_b__h14700) << 1u) | (DEF_a__h14757 | DEF_b__h14758))) << 2u) | ((tUInt8)3u & (((DEF_a__h14815 | DEF_b__h14816) << 1u) | (DEF_a__h14873 | DEF_b__h14874)))))))));
    DEF_x__h1709 = DEF_v__h834 ^ DEF_trueResultA__h1696;
    DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d528 = DEF_NOT_cycle_EQ_128___d9 && !(DEF_x__h1709 == 0u);
    if (!(PORT_RST_N == (tUInt8)0u))
    {
      if (DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d528)
	dollar_display(this,
		       "s,32,5,32,32",
		       &__str_literal_2,
		       DEF_TASK_getRandom___d530,
		       DEF_TASK_getRandom_0_BITS_4_TO_0___d532,
		       DEF_v__h834,
		       DEF_trueResultA__h1696);
      if (DEF_NOT_cycle_EQ_128_AND_NOT_INV_TASK_getRandom_0__ETC___d528)
	dollar_finish("32", 1u);
    }
    if (DEF_NOT_cycle_EQ_128___d9)
      INST_cycle.METH_write(DEF_x__h15090);
  }
  
  
  /* Methods */
  
  
  /* Reset routines */
  
  void MOD_mkTbRightArith::reset_RST_N(tUInt8 ARG_rst_in)
  {
    PORT_RST_N = ARG_rst_in;
    INST_randomVal_init.reset_RST_N(ARG_rst_in);
    INST_randomShift_init.reset_RST_N(ARG_rst_in);
    INST_cycle.reset_RST_N(ARG_rst_in);
  }
  
  
  /* Static handles to reset routines */
  
  
  /* Functions for the parent module to register its reset fns */
  
  
  /* Functions to set the elaborated clock id */
  
  void MOD_mkTbRightArith::set_clk_0(char const *s)
  {
    __clk_handle_0 = bk_get_or_define_clock(s);
  }
  
  
  /* State dumping routine */
  void MOD_mkTbRightArith::dump_state(unsigned int indent)
  {
    printf("%*s%s:\n", indent, "", inst_name);
    INST_cycle.dump_state(indent + 2u);
    INST_randomShift_init.dump_state(indent + 2u);
    INST_randomVal_init.dump_state(indent + 2u);
  }
  
  
  /* VCD dumping routines */
  
  unsigned int MOD_mkTbRightArith::dump_VCD_defs(unsigned int levels)
  {
    fprintf(vcd_file, "$scope module %s $end\n", inst_name);
    vcd_num = vcd_reserve_ids(8u);
    unsigned int num = vcd_num;
    for (unsigned int hdl = 0u; hdl < bk_num_clocks(); ++hdl)
      vcd_add_clock_def(this, bk_clock_name(hdl), bk_clock_vcd_num(hdl));
    vcd_write_def(bk_clock_vcd_num(__clk_handle_0), "CLK", 1u);
    vcd_write_def(num++, "RST_N", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d530", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "TASK_getRandom___d531", 32u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "cycle_EQ_128___d6", 1u);
    vcd_set_clock(num, __clk_handle_0);
    vcd_write_def(num++, "x__h370", 32u);
    num = INST_cycle.dump_VCD_defs(num);
    num = INST_randomShift_init.dump_VCD_defs(num);
    num = INST_randomVal_init.dump_VCD_defs(num);
    fprintf(vcd_file, "$upscope $end\n");
    return num;
  }
  
  void MOD_mkTbRightArith::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbRightArith &backing)
  {
    vcd_defs(dt, backing);
    vcd_prims(dt, backing);
  }
  
  void MOD_mkTbRightArith::vcd_defs(tVCDDumpType dt, MOD_mkTbRightArith &backing)
  {
    unsigned int num = vcd_num;
    if (dt == VCD_DUMP_XS)
    {
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 32u);
      vcd_write_x(num++, 1u);
      vcd_write_x(num++, 32u);
    }
    else
      if (dt == VCD_DUMP_CHANGES)
      {
	if ((backing.PORT_RST_N) != PORT_RST_N)
	{
	  vcd_write_val(num, PORT_RST_N, 1u);
	  backing.PORT_RST_N = PORT_RST_N;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d530) != DEF_TASK_getRandom___d530)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d530, 32u);
	  backing.DEF_TASK_getRandom___d530 = DEF_TASK_getRandom___d530;
	}
	++num;
	if ((backing.DEF_TASK_getRandom___d531) != DEF_TASK_getRandom___d531)
	{
	  vcd_write_val(num, DEF_TASK_getRandom___d531, 32u);
	  backing.DEF_TASK_getRandom___d531 = DEF_TASK_getRandom___d531;
	}
	++num;
	if ((backing.DEF_cycle_EQ_128___d6) != DEF_cycle_EQ_128___d6)
	{
	  vcd_write_val(num, DEF_cycle_EQ_128___d6, 1u);
	  backing.DEF_cycle_EQ_128___d6 = DEF_cycle_EQ_128___d6;
	}
	++num;
	if ((backing.DEF_x__h370) != DEF_x__h370)
	{
	  vcd_write_val(num, DEF_x__h370, 32u);
	  backing.DEF_x__h370 = DEF_x__h370;
	}
	++num;
      }
      else
      {
	vcd_write_val(num++, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
	vcd_write_val(num++, DEF_TASK_getRandom___d530, 32u);
	backing.DEF_TASK_getRandom___d530 = DEF_TASK_getRandom___d530;
	vcd_write_val(num++, DEF_TASK_getRandom___d531, 32u);
	backing.DEF_TASK_getRandom___d531 = DEF_TASK_getRandom___d531;
	vcd_write_val(num++, DEF_cycle_EQ_128___d6, 1u);
	backing.DEF_cycle_EQ_128___d6 = DEF_cycle_EQ_128___d6;
	vcd_write_val(num++, DEF_x__h370, 32u);
	backing.DEF_x__h370 = DEF_x__h370;
      }
  }
  
  void MOD_mkTbRightArith::vcd_prims(tVCDDumpType dt, MOD_mkTbRightArith &backing)
  {
    INST_cycle.dump_VCD(dt, backing.INST_cycle);
    INST_randomShift_init.dump_VCD(dt, backing.INST_randomShift_init);
    INST_randomVal_init.dump_VCD(dt, backing.INST_randomVal_init);
  }
}
