/*
 * Generated by Bluespec Compiler, version 2011.06.D (build 24470, 2011-06-30)
 * 
 * On Sat Jan 25 14:11:44 IST 2014
 * 
 */

/* Generation options: */
#ifndef __schedule_h__
#define __schedule_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

namespace bluesim
{
  void schedule_posedge_CLK();
}

#endif /* ifndef __schedule_h__ */
